### ISSUE TITLE
[Question]: How to generate `rounding mode` in python base api?

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#10029]
hello

Recently, while using cvc5 python base API, I had to use rounding mode.
However, even if I want to create a rounding mode, I don't know how to create it. I tried something like this:
```
>>> solver.mkRoundingMode()
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "cvc5.pxi", line 1567, in cvc5_python_base.Solver.mkRoundingMode
TypeError: mkRoundingMode() takes exactly 1 positional argument (0 given)
>>> solver.mkRoundingMode(ROUND_NEAREST_TIES_TO_AWAY)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
NameError: name 'ROUND_NEAREST_TIES_TO_AWAY' is not defined
>>> solver.mkRoundingMode(Kind.ROUND_NEAREST_TIES_TO_AWAY)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
     raise AttributeError(name) from None
AttributeError: ROUND_NEAREST_TIES_TO_AWAY
>>> solver.mkRoundingMode(solver.ROUND_NEAREST_TIES_TO_AWAY)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
AttributeError: 'cvc5_python_base.Solver' object has no attribute 'ROUND_NEAREST_TIES_TO_AWAY'
```
But all my attempts failed. How can we create a Rounding mode object?

Additionally, I am referring to the cvc5 document (https://cvc5.github.io/docs/cvc5-1.0.0/api/python/base/kind.html) for information related to floating point, and I don't understand `FLOATINGPOINT_RTI`. The document says that all arities are floating point, but looking at smtlibv2, it seems that the arity should be rounding mode and fp. Which one is correct?

Thanks for reading.

**Comment by mpreiner** [comment]
As for the rounding mode try `RoundingMode.ROUND_NEAREST_TIES_TO_AWAY` (https://cvc5.github.io/docs/cvc5-1.0.0/api/python/base/roundingmode.html). `FLOATINGPOINT_RTI` expects the first argument to be a rounding mode, we'll fix the documentation.

**Comment by hagozaebii** [comment]
@mpreiner `FLOATINGPOINT_TO_SBV` and `FLOATINGPOINT_TO_UBV` look weird as well to me. I think `rounding mode` should be added as indices in those functions.

**Comment by mpreiner** [comment]
Yes, you are right. We'll fix this in the documentation. Thanks!
