### ISSUE TITLE
[Question]: How to generate bitvector larger than `2**32` in python base api?

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#10020]
hello

Recently, while using the cvc5 python base API, I confirmed that bit-vectors larger than `2**32` cannot be created with `mkBitVector` in cvc5 API.
The example code is below.
```
>>> solver.mkBitVector(384, 2**32)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "cvc5.pxi", line 1461, in cvc5_python_base.Solver.mkBitVector
OverflowError: value too large to convert to uint32_t
```
However, I would like to use bit-vectors larger than `2**32` in cvc5 API. Is there no way?

Thanks for reading.

**Comment by mpreiner** [comment]
If you use `mkBitVector(384, str(2**32), 10)` it should work. We maybe should consider doing this conversion internally though.

**Comment by hagozaebii** [comment]
@mpreiner thank you so much!
