### ISSUE TITLE
Java memory leak

### ISSUE THREAD

**Issue by Selebrator** [cvc5/cvc5#10052]
**Describe the bug**
I use the Java bindings to create a lot of solvers. It appears that some of that memory is not released. The process eats up all available memory on the system until the OS freezes and I have to reboot.

I made a small example program to reproduce the issue. The heap memory does not exceed 16 MB, But the Process uses all available 14 GB. Be aware, that **executing this example freezes my PC within about 30 seconds**, forcing me to reboot. I suggest to take precautions like running in a VM maybe, to avoid the pain.

```java
public class Leak {
  public static void main(String[] args) {
    while (true) {
      Solver solver = new Solver();
      Term x = solver.mkConst(solver.getIntegerSort());
      Term y = solver.mkConst(solver.getIntegerSort());
      Term two = solver.mkInteger(2);
      // x = 2 AND y = 2*x
      Term assertion = x.eqTerm(two).andTerm(y.eqTerm(solver.mkTerm(Kind.MULT, x, two)));
      solver.assertFormula(assertion);
      Result result = solver.checkSat();
      if (!result.isSat()) {
        System.exit(1);
      }
      //solver.deletePointer();
    }
  }
}
```

If the last line `solver.deletePointer()` is present, the memory leak persists, although it takes a lot longer to fill my ram. In my real application it is not sufficient to include that line; presumably because the terms are much larger.

Manually dropping all pointers from Java code is not a task I would trust Java developers with. We're not trained in manual memory management and would mess this up. Manually releasing just the solver is however feasible. The idiomatic pattern for that would be to add `Solver implements AutoClosable`. That would make the compiler warn about forgetting to close the solver and enable the try-with-resource syntax. 

On a related note: There is a good chance I should not be creating this many solvers. But I think I need to, because I use a breadth first search algorithm that has to check very long formulas in each node. The formula for checking if a node should be expanded is the conjunction of all predecessor nodes plus some extra. I feel like I the solver might be able to take advantage of reusing all that work. But since it has to be a breadth first search, that would eat all my memory even without a leak.

**cvc5 version/commit**: tag [cvc5-1.0.8](https://github.com/cvc5/cvc5/releases/tag/cvc5-1.0.8) = commit c8e12cd
**Operating system**: Arch Linux

**`configure.sh` options**  
```
./configure.sh production --static-binary --java-bindings --no-poly --auto-download --prefix=build/install
```

**`configure.sh` output**  
```
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.42.0")
-- Building Production build
-- Performing Test HAVE_C_FLAG_O3
-- Performing Test HAVE_C_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Performing Test HAVE_CXX_FLAG_O3
-- Performing Test HAVE_CXX_FLAG_O3 - Success
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_C_FLAG_Wall
-- Performing Test HAVE_C_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Performing Test HAVE_CXX_FLAG_Wall
-- Performing Test HAVE_CXX_FLAG_Wall - Success
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_C_FLAG_Wunused_private_field
-- Performing Test HAVE_C_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field
-- Performing Test HAVE_CXX_FLAG_Wunused_private_field - Failed
-- Performing Test HAVE_C_FLAG_fexceptions
-- Performing Test HAVE_C_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override
-- Performing Test HAVE_CXX_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_CXX_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_C_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_CXX_FLAG_Wimplicit_fallthrough - Success
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_C_FLAG_Wshadow
-- Performing Test HAVE_C_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_Wshadow
-- Performing Test HAVE_CXX_FLAG_Wshadow - Success
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init
-- Performing Test HAVE_CXX_FLAG_fno_extern_tls_init - Success
-- Configuring with CXX flag '-fno-extern-tls-init'
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess
-- Performing Test HAVE_CXX_FLAG_Wclass_memaccess - Success
-- Configuring with CXX flag '-Wno-class-memaccess'
-- Using GNU gold linker.
-- Disabling unit tests since assertions are disabled.
-- Found Python: /usr/bin/python3.11 (found version "3.11.5") found components: Interpreter
-- Found GMP (unknown version): /usr/lib/libgmp.so
-- Looking for getc_unlocked
-- Looking for getc_unlocked - not found
-- Building CaDiCaL rel-1.5.2: /home/lukas/ma/code/master/build/cvc5/build/deps/lib/libcadical.a
-- Building SymFPU: /home/lukas/ma/code/master/build/cvc5/build/deps/include/
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS
-- Performing Test CVC5_NEED_INT64_T_OVERLOADS - Failed
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC5_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/wait.h
-- Looking for sys/wait.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ffs
-- Looking for ffs - found
-- Looking for optreset
-- Looking for optreset - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found Java: /usr/bin/java (found version "17.0.8") found components: Development
-- Found JNI: /usr/lib/jvm/default/include  found components: AWT JVM
-- JAVA_AWT_LIBRARY     : /usr/lib/jvm/default/lib/libjawt.so
-- JNI_INCLUDE_DIRS     : /usr/lib/jvm/default/include;/usr/lib/jvm/default/include/linux;/usr/lib/jvm/default/include
-- JNI_LIBRARIES        : /usr/lib/jvm/default/lib/libjawt.so;/usr/lib/jvm/default/lib/server/libjvm.so
-- JNI_FOUND            : TRUE
-- JAVA_AWT_LIBRARY     : /usr/lib/jvm/default/lib/libjawt.so
-- JAVA_JVM_LIBRARY     : /usr/lib/jvm/default/lib/server/libjvm.so
-- JAVA_INCLUDE_PATH    : /usr/lib/jvm/default/include
-- JAVA_INCLUDE_PATH2   : /usr/lib/jvm/default/include/linux
-- JAVA_AWT_INCLUDE_PATH: /usr/lib/jvm/default/include

cvc5 1.0.8

Build profile             : production

Assertions                : off
Debug symbols             : off
Debug context mem mgr     : off

Muzzle                    : off
Statistics                : on
Tracing                   : off

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : off
Valgrind                  : off

Shared build              : on
Python bindings           : off
Java bindings             : on
Interprocedural opt.      : off

CryptoMiniSat             : off
GLPK                      : off
Kissat                    : off
LibPoly                   : off
CoCoALib                  : off
MP library                : gmp (system)
Editline                  : off

Api docs                  : off


CPPLAGS (-D...): NDEBUG CVC5_STATISTICS_ON
CXXFLAGS       : -O3 -Wall -Wsuggest-override -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow -fno-extern-tls-init -Wno-class-memaccess
CFLAGS         : -O3 -Wall -fexceptions -Wimplicit-fallthrough -Wshadow
Linker flags   :  -fuse-ld=gold

Install prefix : /home/lukas/ma/code/master/build/cvc5/build/install

cvc5 license: modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  To build against GPL'ed
libraries which can improve cvc5's performance on arithmetic and bit-vector
logics, use the 'configure.sh' script to re-configure with '--best --gpl'.

Now change to 'build' and type 'make', followed by 'make check' or 'make install'.

-- Configuring done (5.3s)
-- Generating done (0.2s)
-- Build files have been written to: /home/lukas/ma/code/master/build/cvc5/build
```

**Comment by Selebrator** [comment]
Thanks for the fast reply.

> I agree this is not convenient for Java developers, and we may revisit this decision with your issue.

That's great to hear :)

> For now, may be you can store the terms in a collection and call `deletePointer` on them when you are done with them.
Hopefully this fixes your problem.

I thought about this solution and would dislike implementing it at my applications layer. I would need to write my own wrapper around the cvc5 Solver to be sure I missed no locations; present or future. While that would not be a bad idea anyways, I decided against it because every consumer of the cvc5 Solver API would need to do the same to circumvent this issue. So instead I made a small edit to the cvc5 Solver implementation to build that collection for me.
You can find that commit here: https://github.com/Selebrator/cvc5/commit/af95516379f3d6afbe2216c69081b644053906ed

I also modified my example from above to no longer use functions like `term.andTerm(term)`, and instead use `solver.mkTerm(Kind.AND, term, term)`.
```java
public static void main(String[] args) {
  while (true) {
    Solver solver = new Solver();
    Term x = solver.mkConst(solver.getIntegerSort());
    Term y = solver.mkConst(solver.getIntegerSort());
    Term two = solver.mkInteger(2);
    // x = 2 AND y = 2*x
    Term assertion = solver.mkTerm(Kind.AND, solver.mkTerm(Kind.EQUAL, x, two), solver.mkTerm(Kind.EQUAL, y, solver.mkTerm(Kind.MULT, x, two)));
    solver.assertFormula(assertion);
    Result result = solver.checkSat();
    if (!result.isSat()) {
      System.exit(1);
    }
    solver.deleteAllPointers();
  }
```
This solved almost all memory leaks. I'm not sure where the remaining leak is. But now I'm only leaking at a rate of 2 GB per hour, compared to the previous 16 GB per 30 seconds. This is a major improvement both in term of efficiency and developer experience; at minimal cost in my opinion.
With this change my consuming code needs to chance by only 1 line and my tool is able to handle much harder problems. It also has the benefit that my computer no longer crashes when I accidentally load a large example and forget to monitor the ram usage closely.

With this change it would be feasible to implement `AutoClosable` for `Solver` and call `deleteAllPointers` on `close`. I believe this would benefit most developers. Those who want to do manual memory management could just ignore the close method and not use a try-with-resource block.

**Comment by mudathirmahgoub** [comment]
Hi @Selebrator ,

Sorry, I totally forgot that we added this function [deletePointers](https://github.com/Selebrator/cvc5/blob/main/src/api/java/io/github/cvc5/Context.java#L34) specifically for removing all these pointers. 
I think this is better than modifying the solver as you did. Can you check it?

**Comment by Selebrator** [comment]
> But as far as I can tell Context is not used anywhere yet, so that list is empty and that function does nothing.

Nevermind, my IDE was not configured apparently. it is populated [here](https://github.com/cvc5/cvc5/blob/6687df721d31278fdec6cc62bc35962cd2b54a07/src/api/java/io/github/cvc5/AbstractPointer.java#L49C38-L49C38). That solves the issue for me until I want to introduce multi-threading.

**Comment by Selebrator** [comment]
Thanks for helping me. May I suggest adding a reference to `Context` in the documentation, so the next poor soul has an easier time than me?
I think the [Java Quickstart Guide](https://cvc5.github.io/docs/cvc5-1.0.8/api/java/quickstart.html) would be a good place.
