### ISSUE TITLE
`(set-option :dump-unsat-cores-full true)` not working

### ISSUE THREAD

**Issue by someplaceguy** [cvc5/cvc5#10119]
**Describe the bug**

When following the [Quickstart Guide](https://cvc5.github.io/docs/cvc5-1.0.8/binary/quickstart.html), it is suggested to use `(set-option :dump-unsat-cores-full true)` to include assertions in the unsat core that have not been named.

This does not seem to be working. Instead, cvc5 prints `unsupported` and the requested unsat core returns an empty list.

Minimal example:
```smt
(set-logic ALL)
(set-option :produce-unsat-cores true)
(set-option :dump-unsat-cores-full true)
(declare-const a Int)
(assert (< 0 a))
(assert (> 0 a))
(check-sat)
(get-unsat-core)
```

cvc5 output:
```smt
unsupported
unsat
(
)
```

**Command line arguments**: `cvc5 --lang smt test.smt`
**cvc5 version/commit**: `cvc5 version 1.0.8`
**Operating system**: NixOS 23.05

**Comment by someplaceguy** [comment]
I was able to find PR #7314 and #9776, which renamed this option (twice).

It now seems to work when I use `(set-option :print-cores-full true)` instead of `dump-unsat-cores-full`.

So I guess only the quickstart guide needs to be fixed.

**Comment by ajreynol** [comment]
Thanks for pointing this out. I've sent a PR to correct this.
