### ISSUE TITLE
bvsnego

### ISSUE THREAD

**Issue by LeventErkok** [cvc5/cvc5#10173]
Since the overflow predicates aren't quite formalized in SMTLib yet, perhaps this is a non-issue.

The best source I can find defining these predicates is an email to the mailing list: https://cs.nyu.edu/pipermail/smt-lib/2015/000954.html

This e-mail stipulates `bvsnego` for checking overflow of signed-unary-negation. Looks like cvc5 implemented all others, but skipped this one? It's fairly simple to implement (only overflows if the argument is `-(2^(sz-1))` for a bit-vector of size `sz`). 

Would be nice to have it for completeness.

**Comment by LeventErkok** [comment]
@mpreiner Based on the discussion elsewhere, apparently the "agreed upon" name of this is `bvnego`. (I'm sure you were aware of this, but just wanted to make sure.)

**Comment by LeventErkok** [comment]
Hi @barrettcw 

Is this available now? I just tried the nightly build, and that doesn't seem to be the case:

```
$ cat a.smt2
(set-logic ALL)
(declare-fun s0 () (_ BitVec 8))
(define-fun s1 () Bool (bvnego s0))
(assert s1)
(check-sat)
$ cvc5 a.smt2
(error "Parse Error: a.smt2:3.34: Symbol 'bvnego' not declared as a variable")
$ cvc5 -V
This is cvc5 version 1.0.8
compiled with GCC version Apple LLVM 14.0.0 (clang-1400.0.29.202)
on Nov 28 2023 18:27:44
```

**Comment by barrettcw** [comment]
You are right - let me find out why this isn't available yet.

**Comment by aniemetz** [comment]
`bvnego` is not implemented yet (that's why @mpreiner added the `feature` label).

**Comment by aniemetz** [comment]
We will add this feature shortly (probably by the end of next week), we'll keep you posted here.

**Comment by aniemetz** [comment]
@LeventErkok `bvnego` is now available on main.
