### ISSUE TITLE
Global declarations behavior differs when piping from stdin vs a file

### ISSUE THREAD

**Issue by kjcjohnson** [cvc5/cvc5#10258]
**Describe the bug**
Reading SMT2 commands from stdin appears to set the global-declarations option to true unconditionally, while reading from a file properly respects the options. It works "differently" in cvc5 v1.0.4 and doesn't work with cvc5 1.1.0; not sure about other versions.

Example file (push-pop.smt):
```smt
(set-logic ALL)
(push 1)
(declare-const z Int)
(pop 1)
(push 1)
(declare-const z Int)
(pop 1)
```

v1.0.4 apparently ignores the flag and sets global declarations to off:
```
PS D:\bin> Get-Content .\push-pop.smt | .\cvc5-1.0.4.exe --lang smt2 --incremental
; No error (expected)
PS D:\bin> Get-Content .\push-pop.smt | .\cvc5-1.0.4.exe --lang smt2 --incremental --global-declarations
; No error (not expected?)
```

v1.1.0 apparently ignores the flag and sets global declarations to on:
```
PS D:\bin> Get-Content .\push-pop.smt | .\cvc5-1.1.0.exe --lang smt2 --incremental
(error "Cannot bind z to symbol of type Int, maybe the symbol has already been defined?")   ; <-- Error (not expected)
PS D:\bin> Get-Content .\push-pop.smt | .\cvc5-1.1.0.exe --lang smt2 --incremental --no-global-declarations
(error "Cannot bind z to symbol of type Int, maybe the symbol has already been defined?")   ; <-- Error (not expected)
```

However, v1.1.0 works as expected when reading directly from a file:
```
PS D:\bin> .\cvc5-1.1.0.exe --lang smt2 --incremental .\push-pop.smt
; No error (expected)
PS D:\bin> .\cvc5-1.1.0.exe --lang smt2 --incremental --global-declarations .\push-pop.smt
(error "Cannot bind z to symbol of type Int, maybe the symbol has already been defined?")   ; <-- Error (expected)
PS D:\bin> .\cvc5-1.1.0.exe --lang smt2 --incremental --no-global-declarations .\push-pop.smt
; No error (expected)
```

**Command line arguments**: `--lang smt2 --incremental`  
**cvc5 version/commit**: v1.1.0 (from GitHub)
**Operating system**: Windows 10 22H2

**Comment by ajreynol** [comment]
Thanks for pointing this out, this is fixed in https://github.com/cvc5/cvc5/pull/10267.
