### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by JC-Chen1** [cvc5/cvc5#10289]
I am following the instruction [here](https://cvc5.github.io/docs/cvc5-1.0.0/installation/installation.html) to build `cvc5`, but when I trigger `make` command after running `./configure.sh --auto-download` successfully, something went error as follows. 

```
[ 92%] Building CXX object src/CMakeFiles/cvc5-obj.dir/util/statistics_public.cpp.o
/home/chenjiacheng/tmp/cvc5/src/util/real_algebraic_number_poly_imp.cpp: In member function ‘cvc5::internal::RealAlgebraicNumber cvc5::internal::RealAlgebraicNumber::operator/(const cvc5::internal::RealAlgebraicNumber&) const’:
/home/chenjiacheng/tmp/cvc5/src/util/real_algebraic_number_poly_imp.cpp:272:33: error: no match for ‘operator/’ (operand types are ‘poly::AlgebraicNumber’ and ‘poly::AlgebraicNumber’)
  272 |     return convertToPoly(*this) / convertToPoly(rhs);
      |            ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
      |                         |                      |
      |                         poly::AlgebraicNumber  poly::AlgebraicNumber
```
The error message confused me and I don't know how to fix it.
Plus: the operating system I am using is `Ubuntu 20.04.6 LTS`
Thanks a lot if you could give me some instruction!

**Comment by daniel-larraz** [comment]
It seems that you have an old version of libpoly installed on your system (< 0.1.13). Either uninstall libpoly from your system (e.g. `sudo apt remove libpoly-dev`?) or apply the change in PR #10290 to force the build system to download and link against the version of libpoly cvc5 supports.
