### ISSUE TITLE
Proof regressions since 1.0.5

### ISSUE THREAD

**Issue by kanigsson** [cvc5/cvc5#10303]
[bench.tar.gz](https://github.com/cvc5/cvc5/files/14045976/bench.tar.gz)

Hello cvc5 team,

On the attached list of VCs, we see a regression between cvc5 1.0.5 and 1.1.0 in the sense that the old version proved them quickly, and the new version doesn't. This is with the option `--prenex-quant=none`.

Removing the option `--prenex-quant=none` recovers a lot of those VCs, but this option is beneficial for us in general so we would like to keep it ... Or possibly are there other options that could help us with quantifier instantiation? Do you have any suggestions on how to improve performance in our case?

**Comment by ajreynol** [comment]
I believe this is due to https://github.com/ajreynol/CVC4/commit/7d0db1ab430e211b1b37595c0033a848d09c7b5f.

We are dropping some of your user patterns due to the way the quantified formulas are being expressed, I'm looking into a fix.

**Comment by ajreynol** [comment]
All benchmarks from this issue are solved quickly with https://github.com/cvc5/cvc5/pull/10305.

**Comment by kanigsson** [comment]
That's great! I will try this patch ASAP.
