### ISSUE TITLE
Python package license 

### ISSUE THREAD

**Issue by dddejan** [cvc5/cvc5#10327]
I was looking at the [python package](https://pypi.org/project/cvc5/) licensing. It states BSD-3-Clause.

When I look at the libraries packaged I get
```
ls -l .venv/lib/python3.11/site-packages/cvc5/.dylibs/
total 57784
-rwxr-xr-x  1 dejajov  staff  27674448 Jan 31 13:19 libcvc5.1.dylib
-rwxr-xr-x  1 dejajov  staff    811952 Jan 31 13:19 libcvc5parser.1.dylib
-rw-r--r--  1 dejajov  staff    486384 Jan 31 13:19 libgmp.10.dylib
-rwxr-xr-x  1 dejajov  staff    321040 Jan 31 13:19 libpoly.0.1.13.dylib
-rwxr-xr-x  1 dejajov  staff    280480 Jan 31 13:19 libpolyxx.0.1.13.dylib
```

In particular LibPoly is licensed as LGPL3 and distributed with the package. Not an expert but this doesn't feel right.

If a downstream package picks up CVC5 it will assume it is BSD3 and not know that it also includes LGPL libraries. Just wanted to point this out to double check what is the correct thing to do.

**Comment by daniel-larraz** [comment]
@dddejan. Thank you for reporting this issue. I created a PR (#10348) that updates the license of the Python packages to reflect that the packages include artifacts under three different licenses.
