### ISSUE TITLE
FindCLN.cmake doesn't work with CLN 1.3.7 (system package)

### ISSUE THREAD

**Issue by swt2c** [cvc5/cvc5#10370]
In CLN 1.3.7, the format of the CLN_VERSION in cln.h has changed:

```
#define CL_VERSION \
	CL_STR(CL_VERSION_MAJOR) "." \
	CL_STR(CL_VERSION_MINOR) "." \
	CL_STR(CL_VERSION_PATCHLEVEL)

```
and the regex in FindCLN.cmake doesn't parse this properly:

```
  file(STRINGS ${CLN_INCLUDE_DIR}/cln/version.h CLN_VERSION
       REGEX "^#define[\t ]+CL_VERSION .*"
  )
  string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" CLN_VERSION "${CLN_VERSION}")
```
It seems like it would be better to just compile this file and get the version, or perhaps even better, just use pkg-config.  I'll send a PR.

**Comment by daniel-larraz** [comment]
@swt2c. Thank you for reporting this issue.

Currently, our CMake scripts do not rely on pkg-config for building cvc5 with default settings. I'd rather keep it this way if possible. I've submitted a PR (#10372) that fixes the issue using regular expressions.
