### ISSUE TITLE
Too long clauses on QF_BV benchmarks (Bugzilla #825)

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5#1038]
**Imported from Bugzilla**
Reporter: *Andres Noetzli*
Status: *NEW*
Severity: *major*
Assigned to: *Andres Noetzli*
Component: *Bitvectors*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2017-06-17 08:50:27 -0700, Andres Noetzli wrote:
> The following 13 benchmarks produce clauses that are too long (note: the issue appears after 450s\+, so it is difficult to debug):
> 
> QF\_BV/asp/KnightTour/knightTour.in10.smt2
> QF\_BV/asp/Labyrinth/laby\_17\_17\_02.lp.smt2
> QF\_BV/asp/Labyrinth/laby\_17\_17\_07.lp.smt2
> QF\_BV/asp/Labyrinth/laby\_17\_17\_09.lp.smt2
> QF\_BV/brummayerbiere/nextpoweroftwo512.smt2
> QF\_BV/Sage2/bench\_13528.smt2
> QF\_BV/Sage2/bench\_1471.smt2
> QF\_BV/Sage2/bench\_16265.smt2
> QF\_BV/Sage2/bench\_16718.smt2
> QF\_BV/Sage2/bench\_16831.smt2
> QF\_BV/Sage2/bench\_17801.smt2
> QF\_BV/Sage2/bench\_3774.smt2
> QF\_BV/Sage2/bench\_4663.smt2 (this should be the fastest to fail)

**Comment by aniemetz** [comment]
Can't reproduce with cvc5.
