### ISSUE TITLE
Parse error for `define-funs-rec` with only whitespace changes in some cases

### ISSUE THREAD

**Issue by kjcjohnson** [cvc5/cvc5#10398]
**Describe the bug**
In some cases, it appears that cvc5 is incorrectly parsing `define-funs-rec` and `define-fun-rec` commands that contain newlines. I can reproduce it directly from the terminal and another program that opens cvc5 as a subprocess, but not when reading or piping from a file. See the terminal session below for an example.

**Command line arguments**: N/A  
**cvc5 version/commit**: 1.1.1 (release version cvc5-Win64-static) 
**Operating system**: Windows 10 

```
PS D:\bin> .\cvc5-1.1.1.exe
cvc5 1.1.1 [git tag 1.1.1 branch HEAD] assertions:off

<...trim...>

cvc5> (set-logic ALL)
cvc5> (define-funs-rec ((f ((o Bool)) Bool)) (o))
cvc5> (define-funs-rec
... > ((g ((o Bool)) Bool))
... > (o))
(error "Parse Error: <shell>:2.3: Symbol 'g' previously declared as a variable")
cvc5>
```
Note how the definition of `g` throws a parse error, even though the only difference from `f` is white space. Same thing happens with `define-fun-rec`:
```
cvc5> (define-fun-rec p () Bool true)
cvc5> (define-fun-rec
... > q () Bool
... > true)
(error "Parse Error: <shell>:2.6: Cannot bind q to symbol of type Bool, maybe the symbol has already been defined?")
cvc5>
```
But defining a non-recursive function in this style works fine:
```
cvc5> (define-fun
... > h ((o Bool)) Bool
... > o)
cvc5>
```

**Comment by ajreynol** [comment]
Thanks for the report.  This is a known issue, I will prioritize fixing this.
