### ISSUE TITLE
#10330 uses non-3.12 CMake features

### ISSUE THREAD

**Issue by aytey** [cvc5/cvc5#10427]
When I implemented https://github.com/cvc5/cvc5/pull/10330, I used:

```
SOURCE_FROM_CONTENT
```

Not realising this was new in CMake 3.25.

As such, `cvc5` fails to build with CMake 3.12, which is the documented minimum for the project.

This was reported by @BrunoDutertre here: https://github.com/cvc5/cvc5/commit/f77908cdb196f75fbc63f7c3d05ea35a1e4c7f44#commitcomment-139003709

**Comment by aytey** [comment]
@mpreiner I suggest we just rip-out the `SOURCE_FROM_CONTENT` block and go back to using a "standalone" file (in the top-level `cmake` folder) -- are you okay with that?

**Comment by aytey** [comment]
@BrunoDutertre could you give the whole error you're getting? I'd like to check that it is only `SOURCE_FROM_CONTENT` that causes the problem, or if there's more to fix.

**Comment by BrunoDutertre** [comment]
Here's the error message:
```
CMake Error: The source directory "CaDiCaL_version.cpp" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at cmake/FindCaDiCaL.cmake:27 (try_run):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:445 (find_package)


CMake Error: TRY_COMPILE attempt to remove -rf directory that does not contain CMakeTmp:SOURCE_FROM_CONTENT
```

**Comment by BrunoDutertre** [comment]
I can also confirm that `SOURCE_FROM_CONTENT` is the problem and using older-style `try_run` with a
test file in `cmake/deps-utils/` fixes it.

**Comment by aytey** [comment]
Thanks for confirming, @BrunoDutertre.

I’ll try to fix this on Monday (travelling without a laptop this weekend).
