### ISSUE TITLE
Allow for relocatable builds

### ISSUE THREAD

**Issue by gussmith23** [cvc5/cvc5#10440]
**Describe the bug**
After installing cvc5, it cannot be relocated. There does not seem to be a way to enable relocatable builds during the build process. Currently, my solution is to manually set the RPATH for the cvc5 binary and its libraries after they're installed and moved.

**Comment by gussmith23** [comment]
exactly! this is necessary when packaging up cvc5 as part of a larger
software release. ie cvc5 will be installed into a folder, zipped up, and
then unzipped on someone else's machine. FYI, this can be accomplished with
cmake and other build systems by ensuring that they use relatively-defined
RUNPATHs.

now that I'm saying this, I'm realizing that cvc5 does releases itself, so
it must already achieve this somehow. that is, I can go download a zipped
cvc5 release and unzip it on my system and the binary works fine. how does
it acheve this?

**Comment by daniel-larraz** [comment]
It doesn't. We have recently begun publishing zipped cvc5 releases. For the dynamically linked version, you need to either put the libraries in a standard location or add the location to LD_LIBRARY_PATH. I agree this isn't ideal, so I'll look into making the build relocatable.
