### ISSUE TITLE
Some tests are skipped without any obvious reason

### ISSUE THREAD

**Issue by yurivict** [cvc5/cvc5#10456]
**Describe the bug**
See this log fragment:
```
3509/3580 Test  #754: regress0/ff/as.smt2 ..........................................................................***Skipped   2.17 sec
          Start  760: regress0/ff/ctx.smt2
3510/3580 Test  #757: regress0/ff/bool_nary_or_sound.smt2 ..........................................................***Skipped   2.26 sec
          Start  761: regress0/ff/ff_is_zero_sound.smt2
3511/3580 Test  #756: regress0/ff/bigff_is_zero_unsound.smt2 .......................................................***Skipped   2.67 sec
          Start  762: regress0/ff/ff_is_zero_unsound.smt2
3512/3580 Test   #49: regress0/arith/issue5219-conflict-rewrite.smt2 ...............................................***Skipped   3.05 sec
```

Nowhere in the log there is an explanation for why are these tests skipped.

**cvc5 version/commit**: 1.1.2
**Operating system**: FreeBSD 14.0

**Comment by mpreiner** [comment]
Regression tests that need a special build flag have a REQUIRES line. If the requirements are not met, the test is skipped. For example, `test/regress/cli/regress0/ff/as.smt2` requires `cocoa`. If your cvc5 version is not build with cocoa, it will skip the test. Similarly, `regress0/arith/issue5219-conflict-rewrite.smt2` requires a `poly` enabled build.

**Comment by yurivict** [comment]
Maybe tests can print the reason it is skipped in the log?

**Comment by mpreiner** [comment]
If you run ctest with -V it actually does report why the test was skipped. For example, in the case of `regress0/ff/as.smt2` it prints:
![snap0126](https://github.com/cvc5/cvc5/assets/4653598/b9dca129-dc70-43b6-ab6e-0a97106e89cf)
