### ISSUE TITLE
solution unsoundness on small instance involving trigonometric function

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#10541]
Commit: https://github.com/cvc5/cvc5/commit/2cf2797d4a5f54ecadf08711e8040a42bda4c7ac
OS: Ubuntu 22.04

```
[604] % cvc4-1.8 -q small.smt2 
unsat
[605] % cvc5n -q small.smt2 
sat
[606] % cat small.smt2 
(declare-const a Real)
(assert (< (arccos a) 0.0))
(check-sat)
```

**Comment by ajreynol** [comment]
"sat" is the correct answer here.

The issue is if `a` is out of the interval `[-1,1]`, then `(arccos a)` is uninterpreted. It seems that cvc4-1.8 had a refutation soundness bug.
