### ISSUE TITLE
Some questions about --minisat-dump-dimacs.

### ISSUE THREAD

**Issue by Se4ky** [cvc5/cvc5#10551]
### Discussed in https://github.com/cvc5/cvc5/discussions/10548

<div type='discussions-op-text'>

<sup>Originally posted by **TraceShadow** March 26, 2024</sup>
Hi,
I'm trying to translate the smt2 files to dimacs, so I use `--minisat-dump-dimacs`.
Then I found that even I give different smt2 files to cvc5, it generates the same dimacs to me.
I'm sure the smt2 files are different, even though they only have very small differences.
Is that a bug or I do something wrong?
The smt2 files are shown as follow.
https://paste.ubuntu.com/p/9xPhZhsTGf/
https://paste.ubuntu.com/p/xTqrn5PThd/</div>

----------------------------------------------------------------------------------
I had this problem before and my command is `cvc5 --minisat-dump-dimacs my_file.smt2`.

**Comment by ajreynol** [comment]
It is possible that two SMT files can have the same SAT representation, so this may be expected behavior.

**Comment by Se4ky** [comment]
> It is possible that two SMT files can have the same SAT representation, so this may be expected behavior.

I'm grateful for your response, but I have examined the SAT representation and can confirm that they are distinct. Additionally, I have translated the smt2 files using yices and z3, and surprisingly, I did not encounter this issue.

**Comment by ajreynol** [comment]
cvc5 applies normalization to the input problem, so this may cause 2 distinct formulas in the input becoming the same internally. This could explain the behavior, although I did not confirm.

You can see the input formula after preprocessing with `-o post-asserts`, perhaps this output for the 2 versions explains why they have the same dimacs.
