### ISSUE TITLE
Build problem with CVC4

### ISSUE THREAD

**Issue by Anthonysdu** [cvc5/cvc5#10591]
Hi, I am building cvc4 using:

`pip3 install toml && git clone https://github.com/CVC4/CVC4.git && cd CVC4 && git reset --hard b826fc8ae95fc && ./contrib/get-antlr-3.4 && ./configure.sh --optimized --prefix=../cvc4 --static --no-static-binary && cd build && make -j4 && make install`

Here is the error log:
```
CVC4/src/expr/metakind_template.h:0: error: undefined replacement ${metakind_getConst_decls}
make[2]: *** [src/expr/CMakeFiles/gen-expr.dir/build.make:220: src/expr/metakind.h] Error 1
make[2]: *** Deleting file 'src/expr/metakind.h'
make[1]: *** [CMakeFiles/Makefile2:468: src/expr/CMakeFiles/gen-expr.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

Did I miss some packages? Thanks a lot.

**Comment by mpreiner** [comment]
This is an issue with newer versions of bash and was fixed in cvc5: https://github.com/cvc5/cvc5/pull/9233
