### ISSUE TITLE
Reduction of assumptions in (get-unsat-assumptions)

### ISSUE THREAD

**Issue by grhcj** [cvc5/cvc5#10619]
We noticed that CVC5 (v1.1.0, on Windows 10) returns the full set of assumptions when using (get-unsat-assumptions).
Consider the following SMT-Lib benchmark:

```
(set-logic QF_BVFP)
(set-option :produce-unsat-assumptions true)

(declare-fun a () Bool)
(declare-fun b () Bool)
(declare-fun c () Bool)
(declare-fun d () Bool)
(declare-fun e () Bool)

(assert (or a b))
(assert (or a (not b)))
(assert (or (or c d) e))

(check-sat-assuming ((not a) c d e))
(get-unsat-assumptions)
```

Bitwuzla, Mathsat 5 and Z3 all return ((not a)) as unsatisfiable assumption set.
CVC5 returns ((not a) c d e).
Is this expected behaviour in CVC5? Is it possible to retrieve a reduced assumption set?

Thanks in advance
Lukas

**Comment by ajreynol** [comment]
Can you try the latest version of cvc5 (1.1.2 or main)? I am getting that the latest version returns `((not a))` only.

We recently made some internal modifications to our bookkeeping for proofs that may have impacted unsat cores to be more precise.
