### ISSUE TITLE
Incorrect result with SQRT

### ISSUE THREAD

**Issue by Lizn-zn** [cvc5/cvc5#10655]
Hi,
for the following formula, cvc5 incorrectly returns `sat` with `x=1.0`.
```
(set-logic QF_NRAT)
(declare-fun x () Real)
(assert (> x 0))
(assert (<= (sqrt x) 0))
(check-sat)
(get-model)
(exit)
```

OS: Ubuntu 18.04
cvc5 version/commit: 1.1.2 (as downloaded from PyPI)

**Comment by ajreynol** [comment]
Thanks for the report.
Currently, the semantics of `(sqrt x)` is that is a value such that `(sqrt x) * (sqrt x) = x` when `x` is positive.
This means that the square root can be positive or negative.

We will clarify this in our documentation.
