### ISSUE TITLE
Incorrect model with sequences

### ISSUE THREAD

**Issue by barrettcw** [cvc5/cvc5#10674]
The following example gives a wrong model:

(set-logic ALL)
(set-option :produce-models true)

(declare-const x (Seq Int))
(declare-const y (Seq Int))
(declare-const z (Seq Int))

(assert (> (seq.len x) 0))
(assert (= (+ (seq.nth x 0) (seq.nth x (- (seq.len x) 1))) 9))

(assert (= y (seq.rev (seq.++ x x x))))
(assert (= z (seq.++ (seq.unit 3) (seq.unit 4))))
(assert (seq.contains y z))

(check-sat)
(get-model)

In particular, it says that z is (seq.++ (seq.unit 4) (seq.unit 3))

**Comment by ajreynol** [comment]
The printer for constant sequences was previously incorrect.
This was fixed in https://github.com/cvc5/cvc5/pull/10480.

**Comment by barrettcw** [comment]
Ah ok - I was using latest release
