### ISSUE TITLE
Wrong solution of Diophantine equation

### ISSUE THREAD

**Issue by nnarek** [cvc5/cvc5#10676]
cvc5 return that -2 is a solution of 2**x*(4-x)==2*x+4 while other smt solver return unsat

```
; EXPECT: unsat
(set-logic ALL)
(declare-fun x () Int)
(assert (and (= (* (^ 2 x) (- 4 x)) (+ (* 2 x) 4))  (= x (- 0 2))))
(check-sat)
(get-model)
```

same code in pythonic api

```
from cvc5.pythonic import *
x = Int("x")

s=Solver()
s.add(2**x*(4-x)==2*x+4,x==-2)
st=s.check()
if st==sat:
    m = s.model()
    print(m.eval(x,model_completion=True).as_long())
```

**Command line arguments**:  cvc5 --produce-models /tmp/ex1.smt2 
**cvc5 version/commit**: version 1.1.2 of Apr 24 2024 01:42:38 and also 1.1.2 version from PyPI
**Operating system**: WLS of windows

**Comment by ajreynol** [comment]
Thanks for the benchmark.

There is a disagreement in semantics for when the exponent is negative.  In this case, we are interpreting `(^ 2 n)` as `0` when `n` is negative.

**Comment by barrettcw** [comment]
Why are we doing that?

**Comment by yoni206** [comment]
This relates to our discussion here:
https://github.com/cvc5/cvc5/pull/10237#issuecomment-1864194880

Talked to andy: until we make pow2 return a rational, the simplest fix is to disable the translation from (pow 2 x) to (int.pow2 x) (the latter is our internal pow2 operator that can take variables as exponents).

I will do that.
