### ISSUE TITLE
The result of `get-value` is not a ground term

### ISSUE THREAD

**Issue by yav** [cvc5/cvc5#10770]
**Describe the bug**

When using a datatype selector on the wrong constructor, CVC5 prints a message and does not produce a ground term.
Both of these are undesirable when processing the output of CVC5 with other tools (and also violate the SMTLIB spec).

```                                                             
(declare-datatype list(par(a)((nil)(cons(head a)(tail(list a))))))                  
(define-const x (list Int) (as nil (list Int)))                                     
(define-const z Int (head x))                                                    
(check-sat)                                                                      
(get-value (z)) 
```
The output:
```
cvc5 --produce-models test.smt
sat
Could not evaluate (head (as nil (list Int))) in getValue.
((z (head (as nil (list Int)))))
```
In contrast, the output of `z3` is much simpler to process.
```
sat
((z 0))
```
The idea would be that selectors on the wrong constructor should produce an arbitrary ground value of the correct type.

**cvc5 version/commit**: Paste cvc5 version/commit here.  
This is cvc5 version 1.1.1 [git tag 1.1.1 branch HEAD]
compiled with GCC version 9.4.0
on Jan 25 2024 15:57:15

**Operating system**: Name/version of the operating system.  
Linux

**Comment by ajreynol** [comment]
Thanks for pointing this out. 

This issue is caused by cvc5 solving for z, which leads to the solver not deciding on a value for this term.  I will look into a fix soon.
