### ISSUE TITLE
Inconsistent solutions to equivalent formulas for sqrt

### ISSUE THREAD

**Issue by Heaven2024** [cvc5/cvc5#10891]
Hi!
cvc5 1.1.3-dev.291.900587976 [git 900587976 on branch main]
ubuntu:22.04

For the following examples：
```
(set-logic ALL)
(declare-const r0 Real)
(declare-const r1 Real)
(declare-const q36 Real)
(declare-const q37 Real)
(declare-const q38 Bool)
(declare-const q39 Bool)
(assert (exists ((q36 Real) (q37 Real) (q38 Bool) (q39 Bool))
   (and (ite q38 (= q36 (tan r0)) (= q36 (/ r1 2)))
        (ite q39 (> q37 (sqrt q36)) (< q37 (* r1 2.5))))))
(check-sat)

cvc5 test.smt2
unknown
```
And about an equivalent constraint solution，using sqrt with an assert statement：
```
(set-logic ALL)
(declare-const r0 Real)
(declare-const r1 Real)
(declare-const q36 Real)
(declare-const q37 Real)
(declare-const q38 Bool)
(declare-const q39 Bool)
(declare-const sqrt_q36 Real)
(assert (= (* sqrt_q36 sqrt_q36) q36))
(assert (exists ((q36 Real) (q37 Real) (q38 Bool) (q39 Bool))
   (and (ite q38 (= q36 (tan r0)) (= q36 (/ r1 2)))
       (ite q39 (> q37 sqrt_q36) (< q37 (* r1 2.5))))))
(check-sat)
(get-model)

cvc5   --produce-models --check-models  test2.smt2
sat
(
(define-fun r0 () Real 0.0)
(define-fun r1 () Real 0.0)
(define-fun q36 () Real 0.0)
(define-fun q37 () Real 0.0)
(define-fun q38 () Bool false)
(define-fun q39 () Bool false)
(define-fun sqrt_q36 () Real 0.0)
)
```
It seems that there is also a problem with this model. I hope it can be answered. Thanks:)

**Comment by ajreynol** [comment]
The benchmarks are not quite equivalent since our `sqrt` function is non-negative. The second formula potentially permits `sqrt_q36` to be negative.

Nevertheless this when cvc5 says "unknown" there is no guarantee about the model.

In the latter case, we say "sat". What do you think is wrong with the model? `cvc5 --check-models` passes without a failure in this case.

**Comment by Heaven2024** [comment]
> The benchmarks are not quite equivalent since our `sqrt` function is non-negative. The second formula potentially permits `sqrt_q36` to be negative.
> 
> Nevertheless this when cvc5 says "unknown" there is no guarantee about the model.
> 
> In the latter case, we say "sat". What do you think is wrong with the model? `cvc5 --check-models` passes without a failure in this case.

Thank you for your answer. What confuses me is this statement: (ite q39 (> q37 sqrt_q36) (< q37 (* r1 2.5)))))). Obviously, if the model is substituted into this statement to solve the problem, the result will be 0.0<0.0, is this sat?

**Comment by ajreynol** [comment]
You have some variable shadowing here.  The body of your quantified formula uses a variable `q39` which is not the same as the variable declared using `declare-fun`.  Based on https://smt-lib.org/papers/smt-lib-reference-v2.6-r2021-05-12.pdf, this shadowing is allowed, and will override previous definitions, see page 31.

**Comment by barrettcw** [comment]
Andy is right - note that the variables bound by the existential quantifier in the main assertion are *not* the same as the variable declared using declare-const, even though they have the same name.  If you do want these to represent the same thing, you can just get rid of the existential quantifier like so:
(assert
   (and (ite q38 (= q36 (tan r0)) (= q36 (/ r1 2)))
        (ite q39 (> q37 (sqrt q36)) (< q37 (* r1 2.5))))))
Then the model should be more like what you were expecting.
