### ISSUE TITLE
Finite Field theory Unexplained Polynomial failure

### ISSUE THREAD

**Issue by wintersmind** [cvc5/cvc5#10937]
**Describe the bug**

I am running the following program (which validates homomorphic addition of BDOZ/SPDZ MAC shares, fwiw):

```
### start
s = Solver()

mac1,mac2,m1,m2,k1,k2,d = FiniteFieldElems('mac1 mac2 m1 m2 k1 k2 d', 7)

s.add(mac1 == k1 + (d * m1))
s.add(mac2 == k2 + (d * m2))
s.add(mac1 + mac2 != (k1 + k2) + (d * (m1 + m2)))
s.check()
### end
```

This code produces the following output:

```
Fatal failure within std::vector<size_t> cvc5::internal::theory::ff::Tracer::trace(const CoCoA::RingElem &) const at /Users/ceskalka/csl/cvc5/cvc5/src/theory/ff/core.cpp:108
Check failure

 d_parents.count(t) > 0
Unexplained polynomial 1
zsh: abort      python3
```

**Command line arguments**: Command line arguments passed to cvc5 if applicable  

Just running python3 no arguments.

**cvc5 version/commit**: Paste cvc5 version/commit here.  

cvc5-main 

**Operating system**: Name/version of the operating system.  

MacOS 11.7.10

**`configure.sh` options**  

I used configure.sh --cocoa --auto-download.  I'll paste the full script after this. I'm not going to paste output of the run because I don't want to run it again and perhaps kludge something, but everything installed fine, except I needed to use g++ instead of c++ (default) since the latter causes verify-compiler.sh to fail for some reason. 

**`configure.sh` output**  
Paste the output of `configure.sh` here.

**Comment by mpreiner** [comment]
I removed the configure.sh contents since this is not useful :)

@alex-ozdemir can you take a look?

**Comment by alex-ozdemir** [comment]
Will do, thanks for the report, @wintersmind .

**Comment by alex-ozdemir** [comment]
This has been fixed on `main`, @wintersmind .
It was a small bug in the interface between cvc5 and CoCoA (the computer algebra system we use).
Let us know if you encounter other bugs.

And, it's cool that you're looking at SPDZ addition! It'd be great to have a verified MPC implementation.

**Comment by wintersmind** [comment]
That's great, I updated my build and now my code runs fine and behaves as expected. Thanks!
