### ISSUE TITLE
Compiling with CoCoA issues

### ISSUE THREAD

**Issue by alicorn0618** [cvc5/cvc5#11182]
**Describe the bug**
configure with command
`

**`configure.sh` options**  
```shell=
./configure.sh --cocoa --gpl --auto-download
``

**`configure.sh` output**  
cvc5/src/theory/ff/cocoa_util.cpp: In function ‘const std::vector<CoCoA::RingElem>& cvc5::internal::theory::ff::GBasisTimeout(const CoCoA::ideal&, const cvc5::internal::ResourceManager*)’:
cvc5/src/theory/ff/cocoa_util.cpp:115:12: error: ‘handlersEnabled’ is not a member of ‘CoCoA’
  115 |     CoCoA::handlersEnabled = false;
      |            ^~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/cvc5-obj.dir/build.make:4724：src/CMakeFiles/cvc5-obj.dir/theory/ff/cocoa_util.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:791：src/CMakeFiles/cvc5-obj.dir/all] error 2

**Comment by daniel-larraz** [comment]
cvc5 requires a patched version of the CoCoA library. This version is typically downloaded and built when the `--auto-download` option is provided. However, if the build system detects an existing copy of the library on the system, it uses it without checking whether it has been patched. PR #11183 addresses this issue by verifying if the installed CoCoA library has been patched and rebuilding it if necessary.
