### ISSUE TITLE
`int2bv` primitive support

### ISSUE THREAD

**Issue by iscas-zac** [cvc5/cvc5#11252]
**Describe the bug**

The SMT-LIB specifies the `int2bv` primitive, and I saw codes like `(bv2int (bvand ((_ int2bv k) i1) ((_ int2bv k) i2))))` during a rough code search.

However, when I input `(assert (= (bv2int (bvand ((_ int2bv 64) 2) ((_ int2bv 64) 4)))) 0)` into the REPL of `cvc5.exe`, it gives me `(error "Parse Error: <shell>:1.63: Symbol 'bv2int' not declared as a variable")` during parsing time.

Is this an intended behavior?

**Command line arguments**: `cvc5.exe`
**cvc5 version/commit**: `This is cvc5 version 1.1.2
compiled with GCC version 10-posix 20220113
on Apr 16 2024 23:36:07 `
**Operating system**: Windows 11

I also reproduce it with the cvc5's latest version 1.2.0 on Ubuntu 20.04.

**Comment by mpreiner** [comment]
What set-logic command did you use? If you don't include arithmetic, then bv2nat and int2bv are just interpreted as user-defined symbols.

**Comment by iscas-zac** [comment]
`(set-logic ALL)`

**Comment by barrettcw** [comment]
Hi  - operators for converting from int/nat to bv and back are not *yet* part of SMT-LIB.  They are planned to be included in the upcoming 2.7 release.  cvc5 already supports some of these, but it does not support bv2int.  Instead, it supports bv2nat.  Hope that helps.

**Comment by iscas-zac** [comment]
OK, I think I didn't read the document carefully enough and thanks for clarifying.
