### ISSUE TITLE
cvc5 says unknown for problem where z3 says sat

### ISSUE THREAD

**Issue by zeno-98** [cvc5/cvc5#11276]
**Describe the bug**
I try to use the pythonic API of cvc5 to solve the following constraints:

```
from cvc5.pythonic import *

if __name__ == '__main__':
    slv = Solver()
    BoolSort = BoolSort()
    IntSort = IntSort() 

    f = Function('f', IntSort, IntSort, BoolSort)

    a = Int('a')
    b = Int('b')
    c = Int('c')

    transitivity = ForAll([a, b, c], Implies(And(f(a, b), f(b, c)), f(a, c)))

    x = Int('x')
    y = Int('y')

    slv.add(transitivity)
    slv.add(x == y)

    outcome = slv.check()

    print(outcome)
    print(slv.model())
```
the output is:
```
unknown
[f = Lambda([$x1, $x2], True), x = 0, y = 0]
```
This looks strange because although the solver can give a solution, it still gives an "unknown" result.
Later, I replaced `from cvc5.pythonic import *` with `from z3 import *` to use Z3 solver, the output is:
```
sat
[y = 0, x = 0, f = [else -> False]]
```
Z3 also gives a solution, but the conclusion is "sat".

**Command line arguments**: 
Just run the python code.

**cvc5 version/commit**: 
cvc5 1.2.0

**Operating system**: 
ubuntu 22.04

**`configure.sh` options**  
I used `configure.sh --python-bindings --cocoa --auto-download --gpl`

**`configure.sh` output**  
I am very sorry that the `configure.sh` I used during compilation is lost. I used the command `cvc5 --show-config `and got the following.
```
This is cvc5 version 1.2.0
compiled with GCC version 11.4.0
on Aug 14 2024 23:43:57

Copyright (c) 2009-2024 by the authors and their institutional
affiliations listed at https://cvc5.github.io/people.html

This build of cvc5 uses GPLed libraries, and is thus covered by
the GNU General Public License (GPL) version 3.  Versions of cvc5
are available that are covered by the (modified) BSD license. If
you want to license cvc5 under this license, please configure cvc5
with the "--no-gpl" option before building from sources.

THIS SOFTWARE IS PROVIDED AS-IS, WITHOUT ANY WARRANTIES.
USE AT YOUR OWN RISK.

This version of cvc5 is linked against the following non-(L)GPL'ed
third party libraries.

  CaDiCaL - Simplified Satisfiability Solver
  See https://github.com/arminbiere/cadical for copyright information.

  SymFPU - The Symbolic Floating Point Unit
  See https://github.com/martin-cs/symfpu/tree/CVC4 for copyright information.

This version of cvc5 is linked against the following third party
libraries covered by the LGPLv3 license.
See licenses/lgpl-3.0.txt for more information.

  GMP - Gnu Multi Precision Arithmetic Library
  See http://gmplib.org for copyright information.

  LibPoly polynomial library
  See https://github.com/SRI-CSL/libpoly for copyright and
  licensing information.

This version of cvc5 is linked against the following third party
libraries covered by the GPLv3 license.
See licenses/gpl-3.0.txt for more information.

  CoCoALib - a computer algebra library
  See https://cocoa.dima.unige.it/cocoa/cocoalib/index.shtml for copyright information

See the file COPYING (distributed with the source code, and with
all binaries) for the full cvc5 copyright, licensing, and (lack of)
warranty information.

version       : 1.2.0
scm           : no

library       : 1.2.0

debug code    : no
statistics    : yes
tracing       : no
muzzled       : no
assertions    : no
coverage      : no
profiling     : no
asan          : no
ubsan         : no
tsan          : no
competition   : no
portfolio     : yes

cln           : no
glpk          : no
cryptominisat : no
gmp           : yes
kissat        : no
poly          : yes
cocoa         : yes
editline      : no
```

**Comment by ajreynol** [comment]
By default, cvc5 will not try to answer "sat" when quantified formulas are present. You can use options `--mbqi` or `--finite-model-find` to have cvc5 put more effort into answering "sat".

For more details, see this diagram of recommended options: https://homepage.cs.uiowa.edu/~ajreynol/flowchart-quantifiers.png

We are planning on making this point clearer in our documentation.

**Comment by zeno-98** [comment]
> By default, cvc5 will not try to answer "sat" when quantified formulas are present. You can use options `--mbqi` or `--finite-model-find` to have cvc5 put more effort into answering "sat".
> 
> For more details, see this diagram of recommended options: https://homepage.cs.uiowa.edu/~ajreynol/flowchart-quantifiers.png
> 
> We are planning on making this point clearer in our documentation.

Thank you for your response. The solution you provided has resolved the issue. I appreciate your help!
