### ISSUE TITLE
Interpolation is broken for simple queries

### ISSUE THREAD

**Issue by kfriedberger** [cvc5/cvc5#11332]
**Describe the bug**

The interpolation procedure returns `true` when it should not.
The documentation from [here](https://cvc5.github.io/docs/cvc5-1.0.1/api/java/io/github/cvc5/Solver.html#getInterpolant()) says `Returns a Term I such that A->I and I->B are valid`. However, this is not valid in current CVC5.

Example:
```
(set-logic ALL)
(set-option :produce-interpolants true)
(declare-fun x () Int)
(assert (= 0 x))
(get-interpolant A (= 0 x))
```

Expected: :heavy_check_mark: `(= 0 x)` or also `(and (<= x 0) (<= 0 x))` (returned from CVC5 in release version 1.1.2, or previous)

Received: :x: `true` (returned from CVC5 in release version 1.2.0, or later)

**Command line arguments**: None
**cvc5 version/commit**: release version 1.2.0, and also 2024-11-01-8bd4951
**Operating system**: Linux x64

**Comment by ajreynol** [comment]
Thanks for pointing this out, this is because cvc5 is solving/eliminating variables, which was introduced as a heuristic here https://github.com/cvc5/cvc5/pull/10252 to address performance from this issue https://github.com/cvc5/cvc5/issues/10788.

Indeed, this silently makes us return invalid interpolants. The solution is to always include equalities for the solved variables as part of the interpolant.  I will look into this fix.

Alternatively, you can use `--simplification=none` to avoid this issue on main.

**Comment by aniemetz** [comment]
As a follow up, I wonder why this is not caught with `--check-interpolants`. I checked, it is not, but should be. I ran into the same issue while working on adding support for bit-level interpolants to  Bitwuzla, and there my function to check interpolants catches this.

**Comment by ajreynol** [comment]
See the second comment in my description on https://github.com/cvc5/cvc5/pull/11340?

**Comment by ajreynol** [comment]
The interpolation solver was being given the substituted assertions, so it didn't even has access to what needed to be checked.

**Comment by aniemetz** [comment]
Btw, we output `(define-fun A () Bool (and (= x 0) true))` for this now. Shouldn't this be rewritten?

**Comment by ajreynol** [comment]
> That's what I'm saying, the check should be independent of this. It should only check, with separate solver instances, that `A -> I` and `I -> C`, where A and C should be the original assertions and conjecture prior to preprocessing.

Yes, that is what my fix on the PR ehsured.

**Comment by aniemetz** [comment]
You didn't fix the test, you fixed the assertion handling. My point is, the test **should have caught** this issue, which it didn't. So we can still not trust the test to catch other issues that might arise because of preprocessing.
