### ISSUE TITLE
Fix datatype-dump regression test

### ISSUE THREAD

**Issue by 4tXJ7f** [cvc5/cvc5#1649]
The following regression test is currently not passing (and disabled): https://github.com/CVC4/CVC4/blob/c6b2e085d4eb2c232a528a96e13fc7b65fd98fea/test/regress/regress0/datatypes/datatype-dump.cvc. Either the expected output needs to be fixed or the output of CVC4.

**Comment by ajreynol** [comment]
This was fixed in https://github.com/CVC4/CVC4/pull/1672

**Comment by ajreynol** [comment]
Reopened since its breaking nightly regressions.

**Comment by ajreynol** [comment]
Mathias is looking into this now.
