### ISSUE TITLE
Determine if TheoryBV is correctly ignoring the result for propagate

### ISSUE THREAD

**Issue by timothy-king** [cvc5/cvc5#2348]
https://github.com/CVC4/CVC4/blob/master/src/theory/bv/theory_bv.cpp#L866-L874
TheoryBV is ignoring the result of propagate for SUB_CORE. Determine whether this is the correct decision or not. Set `ok` if needed.

**Comment by aniemetz** [comment]
A lot of things moved around, affected part is here: https://github.com/cvc5/cvc5/blob/master/src/theory/bv/bv_solver_lazy.cpp#L539
Lazy solver is obsolete, won't fix.
