### ISSUE TITLE
API Documentation Not Accessible

### ISSUE THREAD

**Issue by MontyThibault** [cvc5/cvc5#2464]
The link below gives a 403 permission error.

http://cvc4.cs.stanford.edu/downloads/builds/documentation/public/latest-unstable

**Comment by MontyThibault** [comment]
This link is found on the homepage http://cvc4.cs.stanford.edu/web/ under the heading "Documentation" with link text "API documentation". The writeup also states "The fifth stable release of CVC4 (version 1.4) has been officially released." which appears to be outdated.

**Comment by 4tXJ7f** [comment]
Thank you for reporting this. We are planning to do an overhaul of how we generate documentation in the future. For now, you can get the most current version in the following folder: http://cvc4.cs.stanford.edu/downloads/builds/documentation/public/ . Please note that the current public documentation is not terribly useful (and we are planning to improve that situation, too). For now, if you are planning to use the API, your best bet is probably to use the [examples]( https://github.com/CVC4/CVC4/tree/master/examples) as a reference. If you have any issue with using the API, feel free to open another issue.

**Comment by nafur** [comment]
We have recently changed how we generate our documentation and are finally automatically generating documentation.
You can find the documentation for the current master (as well as PRs and other branches) at https://cvc5.github.io/docs-ci/.
Please note, though, that the documentation is very much work-in-progress right now. At some point, at the latest when we officially release cvc5, there will be a stable version of the documentation published at some more prominent place.

**Comment by aniemetz** [comment]
The link @nafur posted is incorrect. @nafur can you please remove it? This is for internal purposes only.
The correct link is https://cvc5.github.io/docs/.
