### ISSUE TITLE
Parsing from String (in Java) not supported?

### ISSUE THREAD

**Issue by kfriedberger** [cvc5/cvc5#3075]
I am currently strugling with parsing a SMTLib2-formatted String into an Expr (or a list of boolean Expressions). Is there support for such an operation in the Java-API of CVC4?

There is no public constructor for the Java-class `SWIGTYPE_p_CVC4__api__Solver` that is required by the `ParserBuilder`. Additionally, it seems that CVC4 can only parse from file, not from plain String. We could create a temporary file from the String, but perhaps the CVC4 developers might want to provide a direct method for this.

With one eye to the latest discussion in #3055, would a newly defined and parsed variable "x" be different from any existing variable "x" that was created directly before starting the parsing process? How could we add a `ExprManagerMapCollection`, such that the parser recognizes already existing variables?

Example:
Lets assume a String like 
<pre>
(declare-fun bv () (_ BitVec 4))
(declare-fun bv2 () (_ BitVec 4))
(assert (bvult bv (bvadd bv2 #x1)))
</pre>.
I want to parse this String and get an Expr like `bv < bv2 + 1` from it.

**Comment by 4tXJ7f** [comment]
Parsing from the Java API is actually a feature that we are working on, so hopefully we should support that soon. Yes, a parsed `x` would be different from a previously created `x`. However, parsing an `Expr` will probably look similar to the code [here](https://github.com/CVC4/CVC4/blob/master/test/unit/parser/parser_black.h#L135-L156). In that case, you can actually call [`Parser::defineVar()`](https://github.com/CVC4/CVC4/blob/master/src/parser/parser.h#L516-L523) to create your variable before parsing. The parser should then resolve any occurrence of a variable `name` to `val`.

Your example is actually a bit more than an `Expr`: The three lines are three commands, so you'd have to parse them as [`Command`s](https://github.com/CVC4/CVC4/blob/master/test/unit/parser/parser_black.h#L73-L87) and then extract the information that you need from that, e.g. via the [`AssertCommand::getExpr()`](https://github.com/CVC4/CVC4/blob/master/src/smt/command.h#L332) method.

**Comment by kfriedberger** [comment]
Any news on that topic?
The Java-class `ParserBuilder` depends on `SWIGTYPE_p_CVC4__api__Solver` that is not visible.

**Comment by dtwelch** [comment]
I second the call for news on this. It seems like the only option right now for users of the Java bindings is to convert our own ASTs to CVC4's Exprs directly. This is very inconvenient for those of us who already have a well-formed smtlib2 string ready to go and feed in.. (and a lot of extra work)

Am I missing something obvious here?

**Comment by singh-harish** [comment]
Hi developers,

Any updates on this feature. When can we expect this into release.

We have parseSMTLIB2String method in Z3 which does the same but I've recently switched to CVC5 from Z3 and I'm expecting one such method in CVC5 too.

**Comment by ajreynol** [comment]
We are planning to support this feature in the 1.1 release of cvc5.

We are in the process of adding parsing utilities to our API (a draft of the C++ API is already available on main: https://github.com/cvc5/cvc5/blob/main/include/cvc5/cvc5_parser.h), which we will make available to Java and Python as well.

**Comment by ajreynol** [comment]
This is now supported in the latest release. See https://github.com/cvc5/cvc5/blob/main/src/api/java/io/github/cvc5/InputParser.java#L122.

Example available here: https://cvc5.github.io/docs/cvc5-1.1.0/examples/parser.html.

**Comment by kmohanram** [comment]
This is useful, but somewhat frustrating. For example, if I have already have a CVC5 variable that is available using the following snippet in my Python codebase:

`x = solver.mkConst(solver.getIntegerSort(), "x")
`
and I proceed to parse a string of the form `"(= 1 x)"` using this new feature (preceded by the command `(declare-fun x () Int")`), the solver doesn't so much as prompt me that it is effectively being asked to reconcile two variables with the same name. I can happily `And` these two terms thereafter and the solver somehow magically keeps them separate. The only workaround that I have found is to forcefully cast `x` to `str(x)` before parsing it back into the solver, which kind of defeats the purpose (at least my purpose).

To wit, is there a way for the symbol table to reconcile variable names and recognize that the x I create inline in Python and the x I declare in using the parser are the same?

**Comment by ajreynol** [comment]
You should use `solver.declareFun` where `fresh` is set to `false`, see documentation here: https://cvc5.github.io/docs/cvc5-1.1.1/api/cpp/solver.html#_CPPv4NK4cvc56Solver10declareFunERKNSt6stringERKNSt6vectorI4SortEERK4Sortb

Conversely the documentation for `Solver::mkConst` says that the created function is always fresh (see https://cvc5.github.io/docs/cvc5-1.1.1/api/cpp/solver.html#_CPPv4NK4cvc56Solver7mkConstERK4SortRKNSt8optionalINSt6stringEEE).

You also need to set `fresh-declarations` to `false` in your solver. This means that any parser using that solver will also make calls to `declareFun` where `fresh` is `false`.

FYI, a similar discussion can be found here: https://github.com/cvc5/cvc5/discussions/8345
