### ISSUE TITLE
Fatal failure at sat_proof_implementation.h:681 (produce-unsat-cores, nl-ext-purify)

### ISSUE THREAD

**Issue by rainoftime** [cvc5/cvc5#4334]
Hi,
For the following formula:
[681.txt](https://github.com/CVC4/CVC4/files/4498398/681.txt)

CVC4 throws out a fatal failure:
~~~~
sat
sat
sat
Fatal failure within void CVC4::TSatProof<Solver>::removeRedundantFromRes(CVC4::ResChain<Solver>*, CVC4::ClauseId) [with Solver = CVC4::Minisat::Solver; CVC4::ClauseId = unsigned int] at /home/peisen/test/tofuzz/CVC4/src/./proof/sat_proof_implementation.h:681
Check failure

 isUnit(~lit)

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by nafur** [comment]
It seems this issue has been fixed in the meantime:
```
$ bin/cvc4 --produce-unsat-cores --incremental --nl-ext-purify test.smt2 
sat
sat
sat
sat

```

**Comment by nafur** [comment]
I can't reproduce this issue on the current master (with `cvc4 --incremental --produce-unsat-cores --nl-ext-purify` or variations thereof), however `asan` triggers on the following input with `cvc4 --incremental`:
```
(set-option :produce-unsat-cores true)
(assert (distinct 0 (mod 0 0)))
(check-sat)
(check-sat)
(check-sat)
(check-sat)
```

**Comment by ajreynol** [comment]
@nafur does this still trigger with asan on master?

**Comment by nafur** [comment]
> @nafur does this still trigger with asan on master?

I can't reproduce the issue on current master (neither the original nor the minimized input, neither with `--incremental` not with `--incremental --produce-unsat-cores --nl-ext-purify`)

**Comment by ajreynol** [comment]
Ok great, let's add regression and close.
