### ISSUE TITLE
"Fatal failure" when overwriting symbols with `:global-declarations true`

### ISSUE THREAD

**Issue by andrewvaughanj** [cvc5/cvc5#4767]
## Issue

For the following file:

```
(set-option :global-declarations true)
(push 1)
(declare-fun x!0 () Bool)
(assert x!0)
(check-sat)
(get-model)
(pop 1)
(push 1)
(declare-fun x!0 () (_ BitVec 32))
(assert (= x!0 (_ bv0 32)))
(check-sat)
(get-model)
```

CVC4 falls over as follows:

```
[avj@tempvm build]$ ./bin/cvc4 -m -i ../../../blah.smt2
../../../blah.smt2:2.5: No set-logic command was given before this point.
../../../blah.smt2:2.5: CVC4 will make all theories available.
../../../blah.smt2:2.5: Consider setting a stricter logic for (likely) better performance.
../../../blah.smt2:2.5: To suppress this warning in the future use (set-logic ALL).
sat
(model
(define-fun x!0 () Bool true)
)
Fatal failure within void CVC4::context::CDHashMap<Key, Data, HashFcn>::insertAtContextLevelZero(const Key&, const Data&) [with Key = std::__cxx11::basic_string<char>; Data = CVC4::Expr; HashFcn = std::hash<std::__cxx11::basic_string<char> >] at ../src/./context/cdhashmap.h:388
Check failure

 d_map.find(k) == d_map.end()

Aborted (core dumped)
```

`git rev-parse --short HEAD` == e8df6f67c

**Comment by andrewvaughanj** [comment]
Actually, it seems that global declarations also interferes with type-based overloading:

```
(set-option :global-declarations true)
(declare-fun x!0 () Bool)
(declare-fun x!0 () (_ BitVec 32))
```

```
[avj@tempvm build_debug]$ ./bin/cvc4 ../blah.smt2
../blah.smt2:2.12: No set-logic command was given before this point.
../blah.smt2:2.12: CVC4 will make all theories available.
../blah.smt2:2.12: Consider setting a stricter logic for (likely) better performance.
../blah.smt2:2.12: To suppress this warning in the future use (set-logic ALL).
Fatal failure within void CVC4::context::CDHashMap<Key, Data, HashFcn>::insertAtContextLevelZero(const Key&, const Data&) [with Key = std::__cxx11::basic_string<char>; Data = CVC4::Expr; HashFcn = std::hash<std::__cxx11::basic_string<char> >] at ../src/./context/cdhashmap.h:388
Check failure

 d_map.find(k) == d_map.end()

Aborted (core dumped)
```

but if you remove the `global-declarations`, then things are good:

```
(declare-fun x!0 () Bool)
(declare-fun x!0 () (_ BitVec 32))
(assert (as x!0 Bool))
(check-sat)
```

```
[avj@tempvm build_debug]$ ./bin/cvc4 ../blah.smt2
../blah.smt2:2.12: No set-logic command was given before this point.
../blah.smt2:2.12: CVC4 will make all theories available.
../blah.smt2:2.12: Consider setting a stricter logic for (likely) better performance.
../blah.smt2:2.12: To suppress this warning in the future use (set-logic ALL).
sat
```

(I'm purposefully not including the `set-logic`s to keep the files small)

**Comment by andrewvaughanj** [comment]
I took a look at this, and wondered if this is a reasonable fix:

- Add an extra argument to [`insertAtContextLevelZero`](https://github.com/CVC4/CVC4/blob/master/src/context/cdhashmap.h#L387) of `doOverload` (with a default value of `false`) 

- Change the [assertion](https://github.com/CVC4/CVC4/blob/master/src/context/cdhashmap.h#L388) in `insertAtContextLevelZero` to assert it is an error if the symbol **isn't overloaded**

- Pass in the `doOverload` parameter to `insertAtContextLevelZero` inside of [`SymbolTable::Implementation::bind`](https://github.com/CVC4/CVC4/blob/master/src/expr/symbol_table.cpp#L418)

Does this sound at all reasonable? I've made these changes and it no longer aborts 🤷

**Comment by 4tXJ7f** [comment]
Thanks for reporting and looking into this. I think whatever we fix we end up with should happen at the `SymbolTable` level because the `CDHashMap` is used in lots of different places in the code for different key types, so I'd prefer to keep overloading out of it. Btw. it is my understanding that SMT-LIB actually does not allow overloading user symbols (page 55 of SMT-LIB 2.6), so I don't think that your second example is valid unless I am missing something? I am also not quite sure if your fix would work for the second example, since you'd just end up overwriting something that was already there. I will take a closer look.

**Comment by andrewvaughanj** [comment]
Oh, hmm, so should CVC4 be reporting an error then when a user overloads symbols like that?

**Comment by 4tXJ7f** [comment]
I dug a bit into this and it looks like CVC4 is supposed to support this kind of overloading (if the comments are anything to go by). However, I think that this feature adds quite a bit of unnecessary complexity and is likely poorly tested. We should either fix the existing feature or remove it completely. Do you find function overloading useful?

**Comment by andrewvaughanj** [comment]
> Do you find function overloading useful?
>

Nope; not all.

I was doing some work for [STP](https://github.com/stp/stp/issues/365)/[Boolector](https://github.com/Boolector/boolector/issues/139) related to `global-declarations` and I wrote the *first* example when I was looking at that; this original example was purposefully an instance of "stress testing" global declarations.

The second example was then generated when I was investigating the first, and I was surprised that overloading works in the first place, but then it was interesting that `global-declarations` gets very messy when overloading exists (so I raised this issue).

While this isn't a feature that I would ever use, I think a choice needs to be made: either CVC4 should support overloading everywhere (e.g., in the case of `global-declarations`) or it should be supported nowhere (at least when using SMT2, if the standard doesn't allow it anyway). I believe this echos your second sentence.

**Comment by bobismijnnaam** [comment]
I am still running into this error with the following file: [cdhashmap_crash_cvc4.smt2.txt](https://github.com/CVC4/CVC4/files/6295482/cdhashmap_crash_cvc4.smt2.txt). Command: `$ ~/Downloads/cvc4-master --incremental --lang=smt2.6 cdhashmap_crash_cvc4.smt2.txt`. Unfortunately the file is quite big (1500 lines) as it is produced by another tool (the silicon verifier), and I'm not sure how to start with minimizing the file. I am using the nightly build from the website, has this fix not arrived there yet or is this another edge case/bug?

**Comment by nafur** [comment]
Minimized version:
```
$ cat out.smt2
(set-option :global-declarations true)
(declare-sort S 0)
(declare-fun S (S) Bool)
(declare-fun S () Bool)
$ bin/cvc4 out.smt2
Fatal failure within void cvc5::context::CDHashMap<std::__cxx11::basic_string<char>, cvc5::api::Term, std::hash<std::string> >::insertAtContextLevelZero(const Key &, const Data &) [Key = std::__cxx11::basic_string<char>, Data = cvc5::api::Term, HashFcn = std::hash<std::string>] at /home/gereon/cvc4_proof/src/./context/cdhashmap.h:387
Check failure

 d_map.find(k) == d_map.end()

Aborted (core dumped)
```

@bobismijnnaam I obtained this smaller input using a delta-debugging tool like ddSMT (https://github.com/ddsmt/ddSMT) or pyDelta (https://pydelta.readthedocs.io/en/latest/). They can be highly effective in minimizing such inputs.

**Comment by bobismijnnaam** [comment]
@nafur Thanks for minimizing the file! Next time I will give ddSMT a shot, looks very useful. Wish I had this for (program verifiers) viper/vercors as well...

**Comment by martin-cs** [comment]
@bobismijnnaam for program verifiers I have heard of people using CReduce and it's relative to good effect.

**Comment by andrewvaughanj** [comment]
My team uses [`cvise`](https://github.com/marxin/cvise) for doing "program reductions" as an input to our test-case generator (which supports C and C++) ... our test-case generator that uses CVC4 :)
