### ISSUE TITLE
Java bindings for the new API feature request 

### ISSUE THREAD

**Issue by nourj9** [cvc5/cvc5#5018]
Hello,

I am working on a framework (coded in Java) for parameterized reasoning about distributed systems. In order to support synthesis, I am trying to use CVC4 as a SyGuS engine to synthesize some expressions. 

Playing around with the online CVC4 interface, I believe that the solver is quite efficient and well maintained, and would be a good fit for our target applications.

I was wondering about your plans to implement the Java bindings for the new API (1.8). Is there a timeline for this?

Thanks in advance,
Nour

**Comment by 4tXJ7f** [comment]
@nourj9 That's great to hear! Yes, we have plans for implementing the new API in Java soon but no concrete timeline yet. The current plan is to implement the bindings by hand instead of using SWIG to make them more robust.

**Comment by nourj9** [comment]
Thanks for the quick reply. 

That would be great. Looking forward to incorporating CVC4 in our project.

**Comment by nourj9** [comment]
Hello again,

It seems we are determined to use CVC4 in the project :-) 

I have a few questions to try to see the best way to do this, and I would appreciate any input.

- How realistic it is to have the auto-generated SWIG bindings from the previous version working for CVC 1.8? 
- What is the latest version of CVC4 with working Java bindings?
- If we use that older version, how many features are we losing in the SyGuS front? I know that the SyGuS-IF v2 is somewhat recent, however, if the older solvers are as powerful feature-wise but use a different input format, we may be able to make it work.

Thanks,
Nour

**Comment by 4tXJ7f** [comment]
> How realistic it is to have the auto-generated SWIG bindings from the previous version working for CVC 1.8?

CVC4 1.8 is actually the last version of CVC4 that still supports the SWIG bindings. It would be a substantial amount of effort to get the SWIG bindings to work with newer versions or the new API, however. The deprecated C++ API is not really public anymore and the new C++ API never had SWIG bindings in the first place.

> What is the latest version of CVC4 with working Java bindings?

The legacy API in CVC4 1.8 is the latest and last version that is supported using SWIG bindings.

> If we use that older version, how many features are we losing in the SyGuS front? I know that the SyGuS-IF v2 is somewhat recent, however, if the older solvers are as powerful feature-wise but use a different input format, we may be able to make it work.

The CVC4 legacy API never had real SyGuS support. The new API has support for SyGuS but no Java bindings yet. We have had multiple requests for SyGuS Java bindings and we will try to get to it soon but unfortunately our bandwidth is limited. For the close future, your best bet is to rely on the textual interface if possible.

**Comment by kfriedberger** [comment]
The team of [JavaSMT](https://github.com/sosy-lab/java-smt) would also be happy about Java bindings for the latest version of CVC4. :-)

**Comment by kfriedberger** [comment]
Any news on that topic?

**Comment by mudathirmahgoub** [comment]
@nourj9 , @kfriedberger cvc5 now comes with Java API which supports sygus. 
Check these 3 examples
https://github.com/cvc5/cvc5/blob/master/examples/api/java/SygusFun.java
https://github.com/cvc5/cvc5/blob/master/examples/api/java/SygusGrammar.java
https://github.com/cvc5/cvc5/blob/master/examples/api/java/SygusInv.java
