### ISSUE TITLE
Tests fail on 32-bit architectures

### ISSUE THREAD

**Issue by FabianWolff** [cvc5/cvc5#5082]
While working on the Debian package for CVC4, I discovered that the test suite [doesn't pass](https://buildd.debian.org/status/logs.php?pkg=cvc4&ver=1.8-1) on many 32-bit architectures, including [x86](https://buildd.debian.org/status/fetch.php?pkg=cvc4&arch=i386&ver=1.8-1&stamp=1600253988&raw=0) and [ARM](https://buildd.debian.org/status/fetch.php?pkg=cvc4&arch=armhf&ver=1.8-1&stamp=1600254736&raw=0). In particular, the tests `regress1/fmf/issue3615.smt2`, `regress1/fmf/issue3689.smt2` and `regress2/strings/replaceall-len-c.smt2` seem to cause problems; the logs say something about an `std::bad_alloc()` exception being thrown, but since the build works fine on many other architectures, I doubt that it just ran out of memory (e.g. why should it run out of memory on x86 but not amd64?).

Have you tried building on x86 or ARM recently, and can you confirm/deny this issue?

Also, on MIPS, 53 tests [segfaulted](https://buildd.debian.org/status/fetch.php?pkg=cvc4&arch=mips64el&ver=1.8-1&stamp=1600265345&raw=0), so you might want to investigate this as well (perhaps via QEMU or something).

**Comment by mpreiner** [comment]
Hi @FabianWolff,

Sorry for the late reply. I'm currently in the progress of adding ARM support and will also set up QEMU to run the tests. I'll keep you posted.

**Comment by mpreiner** [comment]
We have x86_64, x86, and ARM64 nightly builds for a while now (https://cvc5-buildbot.stanford.edu/#/builders/33) and the issues of the x86 builds have been fixed. As for the other architectures they won't be a high priority unless users request support for them.
