### ISSUE TITLE
Assertion failure when mixing arrays and floating-point

### ISSUE THREAD

**Issue by nafur** [cvc5/cvc5#5094]
cvc4 gives an assertion failure on an input that uses both arrays and floating-point.

```
$ cat delta.out.smt2 
(declare-fun fpv () (_ FloatingPoint 8 24))
(declare-fun afp () (Array (_ FloatingPoint 8 24) (_ FloatingPoint 8 24)))
(assert (= fpv (select afp (fp.neg fpv))))
(check-sat)

$ bin/cvc4 delta.out.smt2 
Fatal failure within CVC4::Node CVC4::theory::fp::FpConverter::getValue(CVC4::theory::Valuation&, CVC4::TNode) at /home/gereon/cvc4/src/theory/fp/fp_converter.cpp:1708
Check failure

 Theory::isLeafOf(var, THEORY_FP)

Aborted (core dumped)
```

**Command line arguments**: none
**CVC4 version/commit**: 21439d98e9afe1541bb0f5371c4ab0011666bd5e
**Operating system**: Ubuntu 20.04

**`configure.sh` options** `--symfpu`

**Comment by martin-cs** [comment]
Interesting.  @nafur can I ask why you want an array indexed by floating-point numbers?

**Comment by nafur** [comment]
I was tasked with testing the capabilities of different solvers.
I tend to agree that this (most probably) does not reflect an actual use case, but it is allows by SMT-LIB and we should thus either support it or give a reasonable error message.

**Comment by martin-cs** [comment]
That's fair and yes, it should work.  I ask to get a feel of where it is on the "this should work and we should fix it before we ruin someone's application development" to "I am actively screwing up @nafur 's day" scale.  I presume you've chatted to people about the model based tester?

**Comment by nafur** [comment]
I guess this is pretty far on the "we should fix it at some point, but right now nobody really need this" side...
