### ISSUE TITLE
Is there a way to know which grammar rules are used to generate programs?

### ISSUE THREAD

**Issue by rrlcs** [cvc5/cvc5#5341]
I want to get the production rules used to generate the program by cvc4

**Comment by martin-cs** [comment]
Please can you give a little more explanation of what the problem is?  I'm guessing you are using the SyGuS interface to synthesise an expression from a grammar.  Is that correct?  Can you give an example of what you want to generate?

**Comment by rrlcs** [comment]
> Please can you give a little more explanation of what the problem is? I'm guessing you are using the SyGuS interface to synthesise an expression from a grammar. Is that correct? Can you give an example of what you want to generate?

Hi @martin-cs 
Sorry for not being clear in my question. I'll explain it using the following example

Suppose I'm looking at diff.sl from CLIA Track 
https://github.com/SyGuS-Org/benchmarks/blob/master/comp/2019/CLIA_Track/from_2018/diff.sl

CVC4 synthesizes the following program:
(define-fun f ((x Int) (y Int)) Int (ite (<= x y) (- x y) (- y x)))

The possible grammar productions would be as follows:
((I Int (x y
            (- I I)
            (ite B I I)))
(B Bool ((<= I I)))))

Which is a part of general CLIA grammar. 

What I want to know is that can we get the grammar rules used (as written above) to synthesize any program in cvc4?

Thanks in advance.

**Comment by ajreynol** [comment]
There isn't currently a way to get the grammar that CVC4 uses for a particular problem instance.

For a general idea of the grammars used for common theories, you can see Appendix B of https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf.  Notice that grammars for other theories like datatypes, arrays are more complex since they may involve combinations of grammars for multiple types.

Would it be useful to you if CVC4 could output the grammar it is using for a problem?  If so we may be able to add a debugging flag to do this.

**Comment by rrlcs** [comment]
> There isn't currently a way to get the grammar that CVC4 uses for a particular problem instance.
> 
> For a general idea of the grammars used for common theories, you can see Appendix B of https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf. Notice that grammars for other theories like datatypes, arrays are more complex since they may involve combinations of grammars for multiple types.
> 
> Would it be useful to you if CVC4 could output the grammar it is using for a problem? If so we may be able to add a debugging flag to do this.

@ajreynol Yes, please. That would be really helpful. Thank you for your time. Much appreciated.
