### ISSUE TITLE
Official PyPI packages

### ISSUE THREAD

**Issue by florianschanda** [cvc5/cvc5#5418]
Hi!

It would be awesome if there is a cross-platform (at least linux, windows, mac) official PyPI package for CVC4 + Python API.

There is https://pypi.org/project/cvc4-solver but that seems to be just a canned binary for Linux only, plus it seems to be not updated any more.

**Comment by nafur** [comment]
Just as a status report: we started publishing pypi packages for cvc5 with the official release (https://pypi.org/project/cvc5/ and https://cvc5.github.io/docs/latest/api/python/python.html) that support linux and macos on x86 platforms. We are currently working on arm builds for macos, as well as windows builds.

**Comment by florianschanda** [comment]
Awesome! I will give this a try as soon as I can :)

**Comment by CaptainBoggle** [comment]
Any progress on the ARM macOS builds?

**Comment by daniel-larraz** [comment]
@CaptainBoggle. Python bindings for macOS arm64 are now available in PyPI for the latest release of cvc5 (1.1.1).

**Comment by daniel-larraz** [comment]
With the latest release (1.2.0), we are also providing official PyPI packages for Windows. Closing this as resolved.

**Comment by florianschanda** [comment]
That's amazing!!! I will test it out as soon as I can!
