### ISSUE TITLE
Compilation for Windows using Visual Studio

### ISSUE THREAD

**Issue by fred26** [cvc5/cvc5#6036]
I there are way to compile CVC4 using Visual Studio Command Prompt or via CMAKE?
Thanks!

**Comment by mpreiner** [comment]
Compiling CVC4 natively on Windows is not support at the moment. We do support cross-compilation (on Linux) of 64-bit Window binaries via Mingw-w64.

**Comment by mpreiner** [comment]
> So this works only on Linux, correct?

Yes, currently you can natively compile CVC4 on Linux and macOS and you can cross-compile for Windows on a Linux host. 

> Where can I get x64 static libs builds if any?

If you have access to a Linux machine you can find the instruction for cross-compiling a Windows binary [here](https://github.com/CVC4/CVC4/blob/master/INSTALL.md#cross-compiling-for-windows). We also do nightly Windows builds, which you can find [here](http://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/).

**Comment by mpreiner** [comment]
@fred26 does this resolve your issue?

**Comment by fred26** [comment]
I don’t have a Linux host so will have to wait. The nightly windows builds are exe, they aren’t static Libs. Correct? I may need static builds for my project. Thanks

**Comment by mpreiner** [comment]
We should be able to publish the static Windows libraries too. I'll look into it.

**Comment by fred26** [comment]
@mpreiner that would be great and will solve this issue. Thanks
