### ISSUE TITLE
Is the SyGuS keyword `set-feature` supported in CVC4?

### ISSUE THREAD

**Issue by wonhyukchoi** [cvc5/cvc5#6182]
**Describe the bug**

Is the SyGuS keyword `set-feature` supported?
I can't seem to find documentation on whether it is or isn't supported by CVC4.

Ex)
```
$ ./cvc4 --lang=sygus
CVC4> (set-feature : recursion)
Parse Error: <shell>:1.11: expected SMT-LIBv2 command, got `set-feature'.
```
Or
```sh
./cvc4 --lang=sygus example.sl
error "Parse Error: ex.sl:2.12: expected SMT-LIBv2 command, got `set-feature'."
```

Perhaps I'm missing something, because I clearly see `--sygus-rec-fun` as a command line option. 

**Command line arguments**: `--lang=sygus` 
**CVC4 version/commit**:  `bdc92b3`
**Operating system**: Linux x86-64 5.9.16

**Comment by ajreynol** [comment]
Hi, we don't currently support the set-feature command currently, although we should add support for this for the sake of compliance.  I will fix this soon.

Right now, indeed, we support SyGuS in combination with recursive functions by default (`--sygus-rec-fun` is enabled by default).

**Comment by wonhyukchoi** [comment]
Is the `--sygus-rec-fun` a combination of SyGuS and `define-fun-rec`? 

I was referring to something like Example 4 from the [SyGuS Language Standard](https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf) (on bottom of page 15):

```
(set-logic LIA)
;; (set-feature :fwd-decls true)
;; (set-feature :recursion true)
(define-fun x_plus_one ((x Int)) Int (+ x 1))
(synth-fun f ((x Int)) Int
	((I Int))
	((I Int (0 1 x (x_plus_one I)))))
(define-fun fx_plus_one ((x Int)) Int (+ (f x) 1))
(synth-fun g ((x Int)) Int
	((I Int))
	((I Int (0 1 x (fx_plus_one I)))))
(synth-fun h (( x Int )) Int
	((I Int) (B Bool))
	((I Int (0 1 x (- I 1) (+ I I) (h I) (ite B I I)))
	(B Bool ((= I I) ( > I I)))))
(declare-var y Int)
(constraint (= (h y) (- (g y) (f y))))
(check-synth)
``` 
Commenting out the `set-feature` keywords results in 
```sh
(error "Parse Error: foo.sl:12.37: Symbol 'h' not declared as a variable")
```
As it has no definition of `h` to reference.

**Comment by ajreynol** [comment]
Ah sorry, I misspoke.

CVC4 allows for SyGuS problems in the presence of recursive functions, see for example one of our regression tests: https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/sygus/rec-fun-sygus.sy.

But synth-fun are not allowed to be recursive themselves.  This is future work.
