### ISSUE TITLE
Question about patterns

### ISSUE THREAD

**Issue by alebugariu** [cvc5/cvc5#6259]
If we have an input formula with universal quantifiers for which we do not manually specify patterns, is there a way in which a user can see which are the patterns CVC4 infers automatically?

Thank you very much for your help.

**Comment by ajreynol** [comment]
Unfortunately the only way to know this currently is if you have a trace enabled build, and use `-t trigger`. This will moreover output the internal representation of the trigger. For this example:
```
(set-logic ALL)
(declare-fun P (Int) Bool)
(assert (forall ((x Int)) (P x)))
(check-sat)
```
we output:
```
Trigger for (forall ((x Int)) (P x)): 
   (not (= (P INST_CONSTANT_325) true))
```

I can add a command line option to output this as:
```
(trigger (forall ((x Int)) (P x)) (not (= (P x) true)))
```

**Comment by alebugariu** [comment]
So what we see from the trace enabled build is the actual instantiation of the quantifier, no? And from this information we could then rewrite the input formula as:

```
(set-logic ALL)
(declare-fun P (Int) Bool)
(assert (! (forall ((x Int)) (P x)) :pattern (P x)))
(check-sat)
```
since the inferred trigger is `P(x)`, right?

I will try it out, thanks a lot!

**Comment by ajreynol** [comment]
Yes, the output of the trace `-t trigger` will tell you the triggers it is using, for each quantified formula. 

Notice that the semantics of internally used triggers in this example is a bit more complex: `(not (= (P x) true))` means "match occurrences of (P x) that are not currently equal to true".

Also be sure to use the syntax for patterns where they are applied to the body of the quantifier:
`(assert (forall ((x Int)) (! (P x) :pattern ((P x)))))`
