### ISSUE TITLE
Nightly builds out of date

### ISSUE THREAD

**Issue by remysucre** [cvc5/cvc5#6338]
FYI, the linux [nightly builds](http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/) are 3 weeks old now.

**Comment by nafur** [comment]
Indeed we are aware of this issue. But you are right, we really should fix this. @mpreiner 

Why I think the build fails:
The failing build uses clang on ubuntu 18.04, which means we have clang 6.0.1 using the gcc 7.1.0 standard library. I think we see the issue from Note 1 in https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017:

> Note 1: This feature is supported in GCC 7.1 and 7.2 but before GCC 7.3 the __cpp_lib macro is not defined, and compilation will fail if the header is included without using -std to enable C++17 support.

I would suggest to use a more recent gcc version. Note that ubuntu 18.04 has gcc 7.4 available (from security, 7.3 from ports for arm64 et al). I'm not sure why we only have 7.1 anyway... maybe it suffices to manually (re-)install gcc when building the docker container?

**Comment by mpreiner** [comment]
We are in the process of setting up new nightly infrastructure for cvc5. The current setup is outdated and has several issues, but we are currently working on fixing these issues.
As a general note: Binaries are only published if all nightly builds pass. There was one specific build that failed for quite some time, which was the reason why binaries didn't get uploaded. You should see new binaries being uploaded within next days :crossed_fingers:

**Comment by mpreiner** [comment]
Nightlies are fixed and a new binary was uploaded this morning.
