### ISSUE TITLE
Google Test seems not able to access private members with AppleClang 12.0.5 (LLVM 11.1.0)

### ISSUE THREAD

**Issue by Ouyancheng** [cvc5/cvc5#6467]
Google Test in cvc5 seems not able to access private members with AppleClang 12.0.5. 

Platform: Macbook Pro 2015
OS: macOS Big Sur 11.3 
Compiler: AppleClang 12.0.5 (Xcode 12.5 / swift 5.4), based on LLVM upstream version 11.1.0. 
I'm not sure if it's AppleClang 12.0.5 (Xcode 12.5)'s issue or just an issue on my own environment or something else. 

I tried forking and building clang from https://github.com/apple/llvm-project , 
1. with clang built from branch apple/main (clang 13.0, debug setting), it works. 
2. with clang built from branch swift/release/5.4 (AppleClang 12.0.5, clang 11.1.0, debug setting), it fails. 
3. with clang installed via $(brew install llvm) (clang 12.0.0), it works. 
4. with clang shipped with Xcode 12.5 (AppleClang 12.0.5), it fails. 

+ when building cvc5 with all these clang's, lots of warnings from #6453 occurs. 

Any clues on this?

**Comment by aniemetz** [comment]
Same issue on Linux with clang 11.0.1.

**Comment by Ouyancheng** [comment]
> Same issue on Linux with clang 11.0.1.

@aniemetz Thanks for confirming. It's probably clang's problem. 
For the next release of Xcode (branch swift/release/5.5), Apple LLVM would be based on LLVM 12.0.0 so it would probably be fixed. 
I would try to verify it. 
But it's still very far from the next release as Xcode 12.5 just released a few days ago. 

+ did you see deprecation warnings from std::allocator?

**Comment by Ouyancheng** [comment]
Branch:
```
shell% git branch 
  apple/main
  swift/release/5.4
* swift/release/5.5
```
Configuring with command: 
```
cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm 
```
and I will come back with results later on.

**Comment by Ouyancheng** [comment]
It works.

**Comment by aniemetz** [comment]
>     * did you see deprecation warnings from std::allocator?

No, no deprecation warnings.

**Comment by aniemetz** [comment]
I have llvm 11.0.1. installed

**Comment by aniemetz** [comment]
So I guess we'll have to wait for llvm 12.0.0.

**Comment by Ouyancheng** [comment]
I think it's better to add an entry at configure.sh specifying which C and C++ compiler it should use instead of invoking 
`CC=... CXX=... ./configure.sh ...`

**Comment by Ouyancheng** [comment]
> > ```
> > * did you see deprecation warnings from std::allocator?
> > ```
> 
> 
> No, no deprecation warnings.

Maybe you are using gcc's libstdc++? I used clang's libc++ and the warnings are emitted (and it's correct behavior since those APIs are actually deprecated).

**Comment by Ouyancheng** [comment]
Reopening this to remind people.

**Comment by nafur** [comment]
So we spent some time on this issue yesterday.

For our white-box tests, we rely on `-fno-access-control` which essentially disables checking of `private` such that the white-box tests can access private members as well. This is a general thing and unrelated to GTest.
Apparently, there were changes to a number of command line options in clang which lead to `-fno-access-control` being handled incorrectly in (the first few releases of) clang 11. Check the example at https://godbolt.org/z/Po5hKf3PP: it fails only for clang 11.0.0 and 11.0.1 (unfortunately, 11.1 is not available). Check https://reviews.llvm.org/D93104 for what went wrong within clang.
I've tried to workaround this to trigger the desired behavior with clang 11 anyway, but without any luck.

Unfortunately, there is note a lot we can do: it simply does not work for clang 11, and we decided to leave it at that for now.
The only reasonable option I see would be to disable the affected tests for these compiler versions. However, we have tried pretty hard in the past to not introduce such version-specific hacks, so we are reluctant to do it unless someone really needs it.

**Comment by nafur** [comment]
Closing this issue, as there really is nothing we can do (without abandoning the concept of white box tests).

**Comment by Ouyancheng** [comment]
> Closing this issue, as there really is nothing we can do (without abandoning the concept of white box tests).

Thanks for doing this. I thought it was closed already... A workaround could be manually make an exceptional case for clang 11 (and AppleClang 12.x), making -fno-access-control to -fno-no-access-control.

**Comment by nafur** [comment]
> > Closing this issue, as there really is nothing we can do (without abandoning the concept of white box tests).
> 
> Thanks for doing this. I thought it was closed already... A workaround could be manually make an exceptional case for clang 11 (and AppleClang 12.x), making -fno-access-control to -fno-no-access-control.

Unfortunately, this does not work. Check https://godbolt.org/z/Po5hKf3PP with clang 11 and the following command line options:
- no options: ` error: calling a private constructor of class 'A'`
- `-fno-access-control`: ` error: calling a private constructor of class 'A'`
- `-fno-no-access-control`: `error: unknown argument: '-fno-access-control'`

I've spent some time with this, and apparently the command line option simply does not work for clang 11 (in particular, it is not only inverted).

**Comment by Ouyancheng** [comment]
Thanks for putting time on this! This is probably the most interesting (and trivial) bug I've ever seen in a mature compiler...
