### ISSUE TITLE
Request: prebuilt binaries for mac

### ISSUE THREAD

**Issue by polgreen** [cvc5/cvc5#6474]
I think you used to have downloads of prebuilt binaries for mac on the CVC4 website, and now i can only find instructions for homebrew. Is there anywhere I can get the prebuilt binaries for mac?

Or do you have any suggestions for how best to use CVC4 in CI? 

I want to use CVC4 with github actions and it's much slower using brew (+ caching is not as easy https://stackoverflow.com/questions/63672189/use-github-actions-cache-with-brew-install).

**Comment by 4tXJ7f** [comment]
Which version of CVC4 are you interested in? We have binaries for the latest 1.8 release available [here](https://github.com/CVC4/CVC4/releases/tag/1.8) but we currently don't have macOS binaries for nightly builds. It is something that we are planning to support in the future, though, and I can look into it soon.

**Comment by polgreen** [comment]
Ok, great, thanks. Nightly builds would be great at some point in the future (I could have sworn these used to exist for mac? Did I imagine that?).

The release binaries aren't linked from https://cvc4.github.io/downloads.html for mac btw

**Comment by nafur** [comment]
While we still have no nightly builds for MacOS, we have static MacOS binaries attached to the github releases.

**Comment by 4tXJ7f** [comment]
We now have nightly macOS builds available on GitHub: https://github.com/cvc5/cvc5/releases/tag/latest.
