### ISSUE TITLE
Non-termination with rapid memory growth

### ISSUE THREAD

**Issue by wrwg** [cvc5/cvc5#6495]
The attached smt file lets cvc4 rapidly grow memory, as in 20g of RAM within 20 seconds. (Caution! Without memory quota it can easily freeze your machine. When running this, keep your fingers close to Ctrl-C.)  This file is generated via Boogie, which in turn is generated from the Move prover.

Repro: 
[bug.zip](https://github.com/CVC4/CVC4/files/6435445/bug.zip)

Command line:

```
cvc4 --lang smtlib2 -i memory_bug.smt 
```

Version:

```
https://cvc4.cs.stanford.edu/downloads/builds/minireleases/cvc4-aac53f51-x64-ubuntu.zip
```

OS: Linux/ubuntu

@barrettcw 
@shazqadeer

**Comment by martin-cs** [comment]
A quick look suggests this might be a quantifier instantiation problem, so paging @ajreynol .

**Comment by ajreynol** [comment]
There seems to be a strange user pattern in this quantified formula which is triggering some bad behavior.  I'm tracking this down now. 

For now, note that `--user-pat=ignore -i` solves this benchmark quickly.

**Comment by ajreynol** [comment]
Hi Wolfgang,

Thanks for the benchmark, I had not seen this kind of error before.  I will plan on making cvc5 robust for this case, but I'd like to ensure that the user-provided pattern is what you intended.

The quantified formula with `qid` `|outputbpl.1241:56|` which quantifies over an integer variable (call it `x`) is being given this pattern:

```
 :pattern ( 
(|Select__T@[Int]Int_| (|v#Vec_2846| $t0@5) x) 
(|Select__T@[Int]Int_| (|v#Vec_2846| $t0@5) x))
```

This is a multi-pattern containing 2 terms. I currently assume multi patterns are only used when each term contributes at least one new variable to the set of free variables of the pattern.  In this case, 2 terms are being provided that both only contain `x`.  This is what is leading to the unexpected behavior.

What was the intention in this pattern?  Do you intend for cvc5 to generate instantiations for `x` only when both of these patterns are matched?  Or should cvc5 generate instantiations that match either (in which case these should be separate single patterns)?

Let me know,
Andy

**Comment by wrwg** [comment]
> Hi Wolfgang,
> 
> Thanks for the benchmark, I had not seen this kind of error before. I will plan on making cvc5 robust for this case, but I'd like to ensure that the user-provided pattern is what you intended.
> 
> The quantified formula with `qid` `|outputbpl.1241:56|` which quantifies over an integer variable (call it `x`) is being given this pattern:
> 
> ```
>  :pattern ( 
> (|Select__T@[Int]Int_| (|v#Vec_2846| $t0@5) x) 
> (|Select__T@[Int]Int_| (|v#Vec_2846| $t0@5) x))
> ```
> 
> (Edit:) these two terms are identical. This is probably not intentional? I can make cvc5 discard duplicate terms in patterns, but just FYI, in case you wanted to fix this on your end.
> 
> -Andy

Thanks Andy for pointing this out (and the fix). In fact there was a strange test case this stems from which accidentally provided two identical patterns, and removing them from the Move source fixed this. Good to know cvc is now also more stable regards this.
