### ISSUE TITLE
Parse error on Boogie-generated SMT2 file

### ISSUE THREAD

**Issue by shazqadeer** [cvc5/cvc5#6500]
I am getting a parse error I don't understand:
```
shaz@shaz-mbp Downloads % cvc4 output.smt2  --incremental
unsupported
output.smt2:48.14: warning: Attribute ':skolemid' not supported (ignoring this and all following uses)
(error "Parse Error: output.smt2:212.151: Illegal argument detected
CVC4::ArrayStoreAll::ArrayStoreAll(const CVC4::TypeNode &, const CVC4::Node &)

  `value' is a bad argument; expected value.isConst() to hold
ArrayStoreAll requires a constant expression")
```
The file is generated by Boogie and is attached.  The file seems fine to me.  Any suggestion about how to fix the file would be helpful.
[output.smt2.gz](https://github.com/cvc5/cvc5/files/6437395/output.smt2.gz)
**Command line arguments**: --incremental
**CVC4 version/commit**: version 1.9-prerelease [git master aac53f51]
**Operating system**: macOS Big Sur 11.3.1

**Comment by barrettcw** [comment]
cvc4 does not currently support initializing an array with a non-constant value.  It looks like that is what you are trying to do here.  So, it's ok to say that an array contains all 0's, but it's not ok to say that every element is equal to x.  If this is crucial, we can look into supporting it.
