### ISSUE TITLE
Problems with nightly build windows 10

### ISSUE THREAD

**Issue by vladi7** [cvc5/cvc5#6641]
Not able to start the nightly build. I usually do something like "cvc4 helloworld.smt2", but now it is not starting at all. Also, in the previous version I am able to just do cvc4(or cvc5) and it will open the cvc4 terminal, but it is not working now. 

I am using windows 10 command line as admin. Please help, why is it not working anymore?

**Comment by 4tXJ7f** [comment]
@vladi7 Thank you for the report. I have been able to reproduce the issue and will look into it.

**Comment by vladi7** [comment]
@4tXJ7f  Thanks!

**Comment by 4tXJ7f** [comment]
@vladi7 Sorry about the delay. The newest nightly build should now work again on Windows. Feel free to reopen the issue or open a new one if you experience any issues.
