### ISSUE TITLE
Unknown result for String prefix and replace inside universal quantifier

### ISSUE THREAD

**Issue by priyanmuthu** [cvc5/cvc5#6778]
**Bug**
I'm trying to solve for string variables inside a universal quantifier. The solver returns unknown results even for very simple constraints. 

**CVC4 version/commit**: https://github.com/cvc5/cvc5/commit/4eb2234bccf033e3758a7fb7309f51f4864cba0a
**Operating system**: Windows 10

**SMT2 Code**

```
(set-logic ALL)
(set-option :strings-exp true)
(set-option :produce-models true)
(declare-fun str1 () String)
(declare-fun str2 () String)
(assert (forall ((z String) (out String))
    (and 
        (=> 
            (and 
                (str.prefixof "func one" z)
                (str.prefixof "func_one" out)
            ) 
            (= (str.replace z str1 str2) out)
        )
        (=> 
            (and  
                (str.prefixof "funct two" z)
                (str.prefixof "funct_two" out)
            )
            (= (str.replace z str1 str2) out)
        )
    ))
)
(check-sat)
(get-model)
```

**Output**
```
unknown
(model
(define-fun str1 () String "")
(define-fun str2 () String "")
)
```

**Result I Expect**
I expect the result to be:
```
sat
(model
(define-fun str1 () String " ")
(define-fun str2 () String "_")
)
```

*Explanation: * Since both `z` and `out` have a fixed prefix in each context, whatever the value variables `z` and `out` take, the value for `str1` and `str2` is decidable.

Edit: I made the code a bit more readable and added the result I expect.

**Comment by ajreynol** [comment]
Thanks for the benchmark.  For benchmarks with quantifiers over strings, I recommend to use `--sygus-inst`.

I'm not sure the problem is stated how you intended.  `cvc5 --sygus-inst` finds this problem "unsat".  I am getting this set of instantiations is inconsistent:

```
(instantiations (forall ((z String) (out String)) (let ((_let_1 (= out (str.replace z str1 str2)))) (and (or (not (= "func one" (str.substr z 0 8))) (not (= "func_one" (str.substr out 0 8))) _let_1) (or (not (= "funct two" (str.substr z 0 9))) (not (= "funct_two" (str.substr out 0 9))) _let_1))))
  ( "funct two" "funct_two" )
  ( "func one" "func_one" )
  ( "func one" (str.++ "func_one" str1) )
)
```
In particular the last instantiation is saying that if out is `(str.++ "func_one" str1)`, then this will not work no matter what `str1` is.

Perhaps `z` and `out` should be existentially quantified?

**Comment by peleghila** [comment]
Hi Andrew, can you walk us through how you got to this instantiations expression? 

In the original SMT2 code `z` and `out` are universally quantified so that they get their values from the implication. We don't want them assigned in the model.
