### ISSUE TITLE
Coverage statistics

### ISSUE THREAD

**Issue by Cyan-123** [cvc5/cvc5#6835]
Hello, I'd like to ask a question.
During the fuzzing cvc4 process, I generated a lot of smt2 test cases. I want to further count the cvc4 coverage of these generated test cases. What should I do? can you give me a answer? thank you.
I directly use the compilation option"--coverage" provided by cvc4, and then run the generated smt2 file directly with cvc4, such as "cvc4 test1.smt2", but no gcda file is generated. What should I do? Thank you

**Comment by 4tXJ7f** [comment]
Measuring coverage is covered in our [Developer Guide](https://github.com/cvc5/cvc5/wiki/Developer-Guide#code-coverage-reports). The guide applies to the state of current `master` (there have been some recent improvements related to how we do coverage). Hope this helps. Feel free to reopen this issue if you have any additional questions.
