### ISSUE TITLE
CVC4 Build Warning: No GPL'ed Libraries

### ISSUE THREAD

**Issue by GZGavinZhao** [cvc5/cvc5#6836]
Hi! I know this is probably not the best place to ask this question, but I'm not sure where else I can ask this.

When I try to build cvc4 1.8 from source following the instructions, this is a warning I get:
```
Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  This is, however, not the best
performing configuration of CVC4.  To build against GPL'ed libraries which
improve CVC4's performance, re-configure with '-DENABLE_GPL -DENABLE_BEST'.
```
Should I be concerned about this warning? If I really want to build against GPL'ed libraries, where should I append those flags? To the `CXXFLAGS` or the `CFLAGS`?

Thank you!

**Comment by 4tXJ7f** [comment]
> I know this is probably not the best place to ask this question, but I'm not sure where else I can ask this.

This is actually the perfect place :)

> Should I be concerned about this warning? If I really want to build against GPL'ed libraries, where should I append those flags? To the `CXXFLAGS` or the `CFLAGS`?

No need to be concerned about the warning. It is just to make it explicit that CVC4/cvc5 may not perform at its best (in some specific cases) without some of the optional GPL dependencies. If you are ok with GPL dependencies, you can use `--gpl` with the `configure.sh` script. The optional dependencies are listed [here](https://github.com/CVC4/CVC4-archived/blob/master/INSTALL.md#optional-dependencies).

What is your application/which logics are you interested in?

**Comment by GZGavinZhao** [comment]
Thanks for the quick reply! I'm building [solidity](https://github.com/ethereum/solidity/).

**Comment by 4tXJ7f** [comment]
From [Solidity's documentation](https://docs.soliditylang.org/en/latest/smtchecker.html#smt-encoding-and-types), it seems like it uses arrays, datatypes, and (non-)linear integer arithmetic. If GPL works for you, you could try using the GPL dependencies [CLN](https://github.com/CVC4/CVC4-archived/blob/master/INSTALL.md#cln--v13-class-library-for-numbers) and potentially [GLPK](https://github.com/CVC4/CVC4-archived/blob/master/INSTALL.md#glpk-cut-log-a-fork-of-the-gnu-linear-programming-kit). The latter is unlikely to make a difference, especially if Solidity does not invoke CVC4/cvc5 with specific flags (e.g., `--use-approx`). As a start, I'd suggest that you compile CVC4/cvc5 with CLN (could even do without it, if it doesn't seem to provide measurable performance improvement on the benchmarks that you are interested in) but without GLPK. If you run in to performance issues with that configuration, feel free to send us an example.

**Comment by GZGavinZhao** [comment]
Thank you so much for your help! Both look good. I've tested a few compiling tasks and I haven't seen any big disparities between those options. I'm building a package for my distro, so I guess I'll just use both to be safe. Again, thanks a lot for the help!
