### ISSUE TITLE
Cannot reference abstract value in get-value

### ISSUE THREAD

**Issue by djrenren** [cvc5/cvc5#6908]
**Describe the bug**
When an abstract value is produced as part of the model, that value cannot be referenced inside a `(get-value ...)` command.
Page 49 of the smt-lib 2.6 spec states that this ought to be doable.

Sample input:
```smt2
(set-option :produce-models true)
(declare-sort Foo 0)
(declare-fun f (Foo) Int)
(assert (exists ((x Foo)) (= (f x) 3)))
(check-sat)
(get-model)
(get-value (f @uc_Foo_0))
```

Output:
```
test.smt:2.13: No set-logic command was given before this point.
test.smt:2.13: cvc5 will make all theories available.
test.smt:2.13: Consider setting a stricter logic for (likely) better performance.
test.smt:2.13: To suppress this warning in the future use (set-logic ALL).
sat
(
; cardinality of Foo is 1
; rep: (as @uc_Foo_0 Foo)
(define-fun f ((_arg_1 Foo)) Int 3)
)
(error "Parse Error: test.smt:7.24: Symbol @uc_Foo_0 is not declared.

  (get-value ((f @uc_Foo_0)))
                 ^
")
```

**Command line arguments**: `--lang smt2`
**CVC5 version/commit**: Current master: 17fc4c975cefba7082e5557cb9c9515f16b44096
**Operating system**:  Archlinux

**Comment by djrenren** [comment]
Hopefully this is just an issue of variable resolution and not something deeper

**Comment by ajreynol** [comment]
Sorry for the long delay in reply.  This is unfortunately a bit of a tricky issue.

First, the syntax you are seeing is uninterpreted sort values which are concrete e.g. `@uc_T_1`, `@uc_T_2`, `@uc_T_3` denote values of type T that are assumed to be distinct.  In the above model, Foo is interpreted as the set containing the value `@uc_Foo_0`.  This is slightly different from SMT-LIB's abstract values, which refer to unspecified but not necessary distinct terms.  

Regardless, you are right that abstract values should be accepted (page 65 of https://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf) within calls to get-value.  

Internally, this would require pushing a scope on the symbol table after calls to get-model / get-value which is then popped at the next command that takes us out of SAT mode.  We do not currently implement this.

**Comment by djrenren** [comment]
Ah interesting. I hadn't thought about the fact that SMT-LIB doesn't enforce distinctness on these values.  From my understanding, pushing these values onto the scope would still be a compliant implementation, yes?

If so, are y'all open to a PR for this?

**Comment by ajreynol** [comment]
Yes, I think we should address this issue, although it will take some work. 

Thinking about this more, there two solutions:
(1) as mentioned above, dynamically open a scope with the allowable symbols in scope,
(2) always allow the symbols, but check that they are used properly, e.g. not added to assertions.

I believe (2) may actually be the easier solution to implement, I'll think about this some more.

FYI @4tXJ7f .
