### ISSUE TITLE
Partial function application error with Solver::simplify().

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5#6979]
The API call sequence below triggers the following error:
```
terminate called after throwing an instance of 'cvc5::api::CVC5ApiException'
  what():  Partial function applications are not supported in default mode, try --uf-ho.
Aborted (core dumped)
```
```
Solver solver;
Sort s1 = solver.mkFloatingPointSort(5, 11);
Sort s2 = solver.mkFunctionSort(s1, s1);
Sort s4 = solver.getBooleanSort();
Term t1 = solver.mkConst(s1, "_x0");
Term t2 = solver.mkConst(s4, "_x1");
Term t4 = solver.mkConst(s2, "_x3");
Term t32 = solver.mkTerm(ITE, t2, t4, t4);
Term t47 = solver.mkTerm(APPLY_UF, t32, t1);
Term t51 = solver.mkTerm(FLOATINGPOINT_TO_REAL, t1);
Term t62 = solver.mkTerm(FLOATINGPOINT_LT, t47, t1);
solver.assertFormula(t62);
solver.simplify(t51);
```

**cvc5 version/commit**: 3f2e127061ee03db1ba8

**Comment by ajreynol** [comment]
The error message is wrong, but this is expected behavior.  `t47` is an APPLY_UF taking an ITE term as the operator, which is only supported when higher-order is enabled.  Also, t2 and t4 are higher-order.

We should update the error message to say that an `HO_` logic is necessary.

**Comment by aniemetz** [comment]
Interesting. Why is this only supported when higher-order is enabled?

**Comment by ajreynol** [comment]
The root cause is that `t4` is a function variable that is occurring in a term position (as a child of an ITE). This means that we have a term of function type that is not an operator, which means the problem is higher-order.
