### ISSUE TITLE
quantifier incompleteness compared to z3

### ISSUE THREAD

**Issue by barrettcw** [cvc5/cvc5#6999]
Another minimized example where z3 says unsat and cvc5 says unknown:

(set-logic ALL)
(declare-sort T 0)
(declare-fun S (T Int) Int)
(declare-fun S (T Int Int) T)
(assert (forall ((? T) (x Int)) (= x (S (S ? 0 0) 0))))
(check-sat)

**Comment by barrettcw** [comment]
Curiously, even --full-saturate-quant doesn't get this one.  But if you change a 0 to a 1, then full-saturate-quant gets it.

**Comment by barrettcw** [comment]
Maybe some limited instantiation with integer constants is warranted?

**Comment by HanielB** [comment]
The technique is limited to terms occurring in the formula. Indeed it seems it'd be interesting to explore having a few default constants per type in the enumeration. We apply a similar principle when building SyGuS grammars that may be good to apply in this scenario as well.

**Comment by ajreynol** [comment]
I think we should recognize this as a case where the quantifier should immediately rewrite to false via the instantiation `(+ 1 (S (S ? 0 0) 0))`.

On an unrelated note, (the even heavier hammer) `--sygus-inst` gets unsat.

**Comment by barrettcw** [comment]
Yes, but this heavy hammer leads to timeouts on non-trivial examples.
