### ISSUE TITLE
Issues related to installation

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#7001]
I cannot successfully install cvc5 at the commit [c8bc488](https://github.com/cvc5/cvc5/commit/c8bc4881d4f3bf54258b0f01280fbda23a1dd651). 
The ERROR returned by `cmake version 3.10.2` is `list does not recognize sub-command PREPEND`. 

The installation works smoothly at the commit [e04248](https://github.com/cvc5/cvc5/commit/e04248ec858c97b8d716796f87ed42078a953967).
I would be very grateful if you could help me.

**Comment by 4tXJ7f** [comment]
@merlinsun Thanks a lot for your report. PR #7003 should make our build system compatible with older CMake versions again.
