### ISSUE TITLE
How to disable copyright banner in REPL

### ISSUE THREAD

**Issue by ghost** [cvc5/cvc5#7013]
When no arguments are passed to CVC, it reads input from stdin, and in case the process is started directly from a command line, CVC prints copyright message. Is there a way to disable this behavior? There is `--copyright` option to enable it, but how to disable it? Thanks.

**Comment by 4tXJ7f** [comment]
What exactly is your use case? You could use `--no-interactive`, but then you won't get a copyright message _and_ cvc5 won't print `cvc5>`. Does that work for you?

**Comment by user93702699** [comment]
Sorry, but we need the `cvc5>` output, as we use it to as a delimiter to determine when the previous output is fully printed to the console.

I don't really see what is the hindrance to introduce `--no-copyright` flag (or even better do not print copyright at all unless `--copyright` is provided)? I somewhat understand the cvc5 developers' need for copyright adwares, but on the other hand, from a technical point of view, it really decreases user satisfaction. Being forced to see 20+ irrelevant lines of output every time I open cvc5 repl is irritating.

All modern open-source software, and even a lot of proprietary closed-source software, that support CLI also provide an option to hide copyright info, or even don't display the copyright by default. Please consider adding such option to cvc5. Thanks.

**Comment by 4tXJ7f** [comment]
I see, thanks. Does decreasing the verbosity work for you (`-q`)? With a lower verbosity level, we don't print the copyright message but I think that we print all the information that you need. Could you give that a try?
