### ISSUE TITLE
Build cvc4 1.7 with antlr from ubuntu 20.04

### ISSUE THREAD

**Issue by elopio** [cvc5/cvc5#7272]
Hello!

**Describe the bug**
I would like to build cvc4 1.7 using the [libantlr package from ubuntu 20.04](https://packages.ubuntu.com/focal/libantlr3c-3.4-0). I'm not sure what should I pass to ./configure so it can find it.

I'm getting:
`  Could NOT find ANTLR (missing: ANTLR_INCLUDE_DIR ANTLR_LIBRARIES)`

**cvc5 version/commit**: 1.7
**Operating system**: Ubuntu 20.04

**`configure.sh` options**  
That's the question. This is for building the [solidity snap](https://github.com/ethereum/solidity/blob/7a9f48155b6513d9a3a52f533b6cc88af10a3967/snap/snapcraft.yaml#L57), so I'm using:

`./configure.sh --prefix=$SNAPCRAFT_STAGE/usr`

**`configure.sh` output**  
`  Could NOT find ANTLR (missing: ANTLR_INCLUDE_DIR ANTLR_LIBRARIES)`

The thing is that `./contrib/get-antlr-3.4` is failing on architectures other than amd64. So I thought it would be better to use the package instead of building it. However my cmake knowledge is very limited, I'm not sure what the script that finds antlr is asking for.

I will appreciate any pointers.

pura vida

**Comment by nafur** [comment]
Please note, that the 1.7 release is almost two and a half year old and we strongly encourage everyone to use the latest release (which would be 1.8) or the current master. Is there a specific reason you want 1.7?

As for the actual problem: you can try building ANTLR with `MACHINE_TYPE=X ./contrib/get-antlr-3.4`. What machine type are you trying to build for?

**Comment by 4tXJ7f** [comment]
To add to what @nafur said, please also note that libantlr won't be enough, CVC4/cvc5 additionally require ANTLR 3 itself to generate the actual code for the parser. Your best bet is to use a newer version of CVC4/cvc5 that has support for other architectures such as ARM.
