### ISSUE TITLE
(get-option :regular-output-channel)

### ISSUE THREAD

**Issue by davidcok** [cvc5/cvc5#7361]
CVC5 --lang=smt2  
produces

cvc5> (get-option :regular-output-channel)
ManagedStream

and similarly for :diagnostic-output-channel

CVC4 produces ""

The standard says the results should be "stdout" and "stderr"

**Command line arguments**:  --lang=smt2   
**cvc5 version/commit**: 0.0.2
**Operating system**: MacOS

**Comment by nafur** [comment]
Thanks for the report, `ManagedStream` might indeed not be the most useful output here.
I'm preparing a PR to fix this.
