### ISSUE TITLE
:interactive-mode and :produce-assertions

### ISSUE THREAD

**Issue by davidcok** [cvc5/cvc5#7379]
V2.6 says that :interactive-mode is deprecated in favor of :produce-assertions, but that it is still accepted.

Accordingly, the following should work:
(set-option :interactive-mode true)
(set-logic QF_UF)
(declare-fun p () Bool)
(get-assertions)
(assert true)
(assert p)
(assert (or p p))
(assert false)
(get-assertions)

but instead CVC5 says

unsupported
success
success
(
error
"Cannot query the current assertion list when not in produce-assertions mode."
)
success
success
success
success
(
error
"Cannot query the current assertion list when not in produce-assertions mode."
)

**Command line arguments**: --lang=smt2 --quiet
**cvc5 version/commit**: 0.0.2
**Operating system**: MacOS

**Comment by ajreynol** [comment]
Yes, we should follow the standard, I guess this is easy to revert?

**Comment by nafur** [comment]
Yes, I'll send a PR.
