### ISSUE TITLE
CVC5 java language bindings

### ISSUE THREAD

**Issue by classicwuhao** [cvc5/cvc5#7579]
Hi, I am trying to integrate CVC5 into one of my tools, I built CVC5 with configure.sh --java-bindings, but I cannot find cvc5.jar. Is this something wrong with build files or I am building CVC5 with java bindings in a wrong way?

**Comment by mudathirmahgoub** [comment]
The following configuration would generate  `build/src/api/java/cvc5-0.0.4-dev.jar` and symbolic link 
`build/src/api/java/cvc5.jar`
```bash
$ ./configure.sh production --java-bindings --auto-download
$ cd build
$ make -j 8
```

**Comment by classicwuhao** [comment]
This is the configuration I used and I can find libcvc5jni.so but still missing .jar files.

**Comment by mudathirmahgoub** [comment]
I don't know which version you used, but the above commands worked with commit  71cab467df779fc1a52e8a5f981132f49d9d3182. 
Can you share the information requested when you opened this issue?

**Comment by classicwuhao** [comment]
I am attaching a detailed output from configure.sh and I am using Ubuntu 20.04 (cvc is cloned from master branch)
[config.log](https://github.com/cvc5/cvc5/files/7487911/config.log)

**Comment by mudathirmahgoub** [comment]
Tested the above commands on Ubuntu `20.04` CMAKE version `3.21` and the jar files are still generated.

**Comment by mudathirmahgoub** [comment]
Perhaps there is an issue with Cmake version. In our CI we use this configuration  below. Please can you try it?
```bash
./configure.sh production --auto-download --assertions --tracing --unit-testing --java-bindings
cd build
make build-tests
ctest -R unit/api/java/SolverTest
```

**Comment by classicwuhao** [comment]
Just tested with cmake version 3.22 and generates jar files. Looks like cmake caused the problems. Maybe this should be mentioned just in case other researchers would like to compile java bindings. Thanks.

**Comment by nafur** [comment]
I checked with cmake 3.16, and it seems to generate the jar file (https://github.com/nafur/cvc5/runs/4158557398#step:7:1092). Do you see this `Built target cvc5jar` in your build?

**Comment by mpreiner** [comment]
`Built target cvc5jar` is not enough, it should actually be:
```
[100%] Building Java objects for cvc5jar.jar
[100%] Generating CMakeFiles/cvc5jar.dir/java_class_filelist
[100%] Creating Java archive cvc5-0.0.4-dev.jar
[100%] Built target cvc5jar
```

I can reproduce the issue on Ubuntu 20.04.

**Comment by classicwuhao** [comment]
Thanks for fixing this issue.
