### ISSUE TITLE
CVC5 array declaration bug

### ISSUE THREAD

**Issue by GreenBeard** [cvc5/cvc5#7596]
**Describe the bug**
CVC5 does not handle negative numbers in array declarations (using `define-fun`). It however, will create them for models (produced by `get-model`) which means that it does not accept its own output model when testing against itself. This is causing me minor issues as I am attempting to store some proofs for later usage.

The output from the command (see below for command):
```
(error "Parse Error: ./counter.smt2:2.69: Illegal argument detected
cvc5::ArrayStoreAll::ArrayStoreAll(const cvc5::TypeNode&, const Node&)

  `value' is a bad argument; expected value.isConst() to hold
ArrayStoreAll requires a constant expression")
```

Example smtlib2 file
```counter.smt2
(set-logic ALL)
(define-fun foo () (Array Int Int) ((as const (Array Int Int)) (- 1)))
(assert (= (select foo 0) (- 1))
(check-sat)
```

**Command line arguments**: Command line arguments passed to cvc5 if applicable

I just used `cvc5 --lang=smt2 --output-lang=smt2 ./counter.smt2`
**cvc5 version/commit**:
```
This is cvc5 version 0.0.3 [git tag 0.0.3 branch HEAD]
compiled with GCC version 9.3.0
on Oct 29 2021 22:29:58
```
**Operating system**: Debian (Linux), but I believe this is irrelevant.

**`configure.sh` options**  
Whatever the build from the releases on github.com has.

**`configure.sh` output**  
Whatever the build from the releases on github.com has.

**Comment by ajreynol** [comment]
This is caused by a combination of two issues:
(1) we should ideally parse `(- 1)` as `CONST_RATIONAL{-1}` instead of `(UMINUS CONST_RATIONAL{1})`
(2) array constants should permit non-value arguments

It might be easier to address (1) in the short term.

**Comment by GreenBeard** [comment]
@ajreynol Thanks for the fix :)
