### ISSUE TITLE
non-clausal-simp progress/verbosity

### ISSUE THREAD

**Issue by chloesack92** [cvc5/cvc5#7778]
I have some NRA (actually QF_NRA) instances in about 100 variables. When I try to solve these, cvc5 quickly reports `non-clausal-simp...` and then seems to churn away in silence, for hours. Is there any way to determine if progress is being made, and if there's some prospect of completion of this pass?

**Comment by nafur** [comment]
Most likely, `non-clausal-simp` is simply the last preprocessing pass that is executed. While I have some guesses on where cvc5 is stuck, we'd need some debug output to confirm. Generally, 100 variables is an awful lot for nonlinear real problems, at least if we can't eliminate the majority in preprocessing. Can you share your input?

**Comment by chloesack92** [comment]
I see.

I have had to scramble it but the input is attached. :smiling_face_with_tear:  
[7778.smt2.gz](https://github.com/cvc5/cvc5/files/7689909/7778.smt2.gz)

**Comment by nafur** [comment]
So I had a look at that, and we get stuck in the cad-based solver at some point. I'm working right now at improving this part of cvc5 on benchmarks very similar to yours... and while it helps at bit, it is apparently not sufficient. While cvc5 might become much better at this in the future (dependent upon how much time I find for this), there are a few things you might be able to improve on your end, i.e. in the encoding:
Firstly, eliminate variables (when its easy). Look out for stuff like `(= x <some term without x>)` and simply replace x everywhere. 
Unfortunately, this will result in huge polynomials in a few places of your input... my guess is that this can be mitigated by computing their modulus with other equalities. Of course the optimum would be to compute a Gröbner basis here...

**Comment by chloesack92** [comment]
I see - I can certainly try eliminating variables in that way. It's good to hear cvc5 might become much better at these problems :smiley: 

You said "Firstly" - are there other suggestions you have for making these problems easier to solve?

**Comment by nafur** [comment]
> I see - I can certainly try eliminating variables in that way. It's good to hear cvc5 might become much better at these problems smiley
> 
> You said "Firstly" - are there other suggestions you have for making these problems easier to solve?

The things I'd try after that would be what I mentioned last: using the equalities to make the inequalities smaller (by computing the modulus of the polynomials). (if you have `(= p 0)` and `(> q 0)` you can replace the inequality by `(> r 0)` with `r = q % p`.
As for the equalities, it may also be worth using a Gröbner basis to make them smaller. However, this is a significant hurdle when computing small infeasible subsets, and thus not trivial to integrate.

**Comment by chloesack92** [comment]
Ah, now I understand. Thanks.

**Comment by nafur** [comment]
I think this can be closed, but feel free to reopen it if you have further questions.
