### ISSUE TITLE
UNTERMINATED_QUOTED_SYMBOL rule breaks incremental input (Bugzilla #572)

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5#791]
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *{Internals} Parser infrastructure*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

On 2014-06-22 02:58:15 -0700, Morgan Deters wrote:
> The presence of the UNTERMINATED\_QUOTED\_SYMBOL rule in the Smt2 parser breaks application\-track smtcomp input, e.g. a multiline :source
> 
> (set\-info :source |
> 
> foo
> 
> |)
> 
> will result in "error finding next token."
> 
> Investigate.

On 2014-06-22 04:13:32 -0700, Morgan Deters wrote:
> I hate this bug.  CC'ing you in, Kshitij\-\-\-maybe you've got a good idea on this one.
> 
> For the application track, we were having problems with line\-buffered input and multi\-line commands, e.g.
> 
> (set\-info :source | One line
> another line.
> A third. |)
> 
> Without the UNTERMINATED\_QUOTED\_STRING lexer token, everything is fine (so I disabled it for the SMT\-COMP application track binary submission).  But we like this rule, because it gives nice error messages (so it's re\-enabled in master currently).
> 
> How to fix this?  Maybe the UNTERMINATED\_QUOTED\_STRING token must end with EOF or something, to prevent it misfiring?

On 2014-06-22 04:15:10 -0700, Morgan Deters wrote:
> I should add:  the application track is somewhat special because it is required to run in interactive session with another process.  So no extra buffering is possible, since you won't get the next command until you respond "success" or whatever to the previous one.  Something about this line\-buffering confuses the lexer into firing the UNTERMINATED version of the rule.

On 2014-06-22 11:55:27 -0700, Kshitij wrote:
> Just tried with this input file:
> 
> (set\-info :source "Hello
> World")
> 
> When given as file, no errors.
> 
> When using redirecting with \-\-interactive get:
>   (error "Parse Error: <shell>:1.23: Error finding next token.")
> and then:
>   (error "Parse Error: <shell>:1.4: Unexpected token: 'World'.")
> 
> When using redirecting with \-\-no\-interactive, get a different error!
>   (error "Parse Error: <stdin>:2.6: Extended characters are not part of SMT\-LIB, and they must be encoded as esacped sequences
> 
>   xtended characters are not part of SMT\-LIB, and they must be encoded a...
>   ^
> ")
> 
> OK now, change the file to:
> (set\-info :source |Hello
> World|)
> 
> When using redirecting with \-\-interactive, it works successfully!
> 
> BUT, same file with \-\-no\-interactive I get:
>   (error "Parse Error: <stdin>:1.18: Error finding next token.")
> 
> What is going on? There seem to be two different issues it looks like, one with how strings are quoted, and another with line/buffering.
> 
> Perhaps using "\-\-interactive" AND "\-\-no\-interactive\-prompt" (which just hides the "CVC4>" bit we added for a user) will solve it for now?
> 
> Overall, looks like more ANTLR mess.

On 2014-06-22 12:14:31 -0700, Morgan Deters wrote:
> Try removing the UNTERMINATED rules and try also.
> 
> I think all of these cases were working previously, but then maybe broke
> when we added some rules.  :\-/

On 2014-06-22 18:06:45 -0700, Kshitij wrote:
> I tried after reverting the commit (when using "|" as quoting symbol), and it is working with \-\-no\-interactive but with \-\-interactive getting the same parsing error.
> 
> When you find some time, try running with \-d parser (with file redirection and \-\-smt \-\-no\-interactive), I am getting binary data printed out. It might just be some flawed debugging statement, or some memory corruption going on.
> 
> nextCommand() \=> (set\-info :<binarydata>(set\-info :source \_Hello
> World|)
> 
> (also note the \_ instead of |) This is with the commit 2b87a75 reverted on top of cc362cf.
> 
> \-\-Kshitij

**Comment by 4tXJ7f** [comment]
A similar issue came up again recently with the following input:

```
(set-logic ALL)
(set-info :source |

|)
```

Split tokens across lines is tricky :/
