### ISSUE TITLE
SYGUS incompatibility with record types

### ISSUE THREAD

**Issue by chasenorman** [cvc5/cvc5#7925]
Incorrect synthesis results are produced with constraints involving record types.

```
import pycvc5

# solver setup
solver = pycvc5.Solver()
solver.setOption('incremental', 'false')
solver.setOption("lang", "sygus2")
solver.setLogic("ALL")

# record setup
wrapped_integer = solver.mkRecordSort([('value', solver.getIntegerSort())])
value_selector = wrapped_integer.getDatatype()[0].getSelectorTerm('value')
zero = solver.mkInteger(0)

# nonterminal declaration
input = solver.mkVar(wrapped_integer, 'input')
value = solver.mkTerm(pycvc5.kinds.ApplySelector, value_selector, input)
value_eq_zero = solver.mkTerm(pycvc5.kinds.Equal, value, zero)  # represents (= (value input) 0)

# grammar creation
output = solver.mkVar(solver.getBooleanSort(), 'output')
grammar = solver.mkSygusGrammar([input], [output])
grammar.addRule(output, value_eq_zero)
f = solver.synthFun('f', [input], solver.getBooleanSort(), grammar)  # can only be (= (value input) 0)

# constrain f(x) to always hold.
x = solver.mkSygusVar(wrapped_integer, 'x')
constraint = solver.mkTerm(pycvc5.kinds.ApplyUf, f, x)
solver.addSygusConstraint(constraint)
```

This unexpectedly synthesizes `(= (value input) 0)`, despite this expression not holding for some values of `input`. 

**Command line arguments**: N/A
**cvc5 version/commit**: `4d8e954c952db015e28d218b4c23f038155797ad`
**Operating system**: macOS Monterey

**`configure.sh` options**  
N/A

**`configure.sh` output**  
N/A

I am not using the most recent version of cvc5 because I am having trouble generating python bindings on the latest release. Using the latest version of cmake, the configuration `./configure.sh production --auto-download --assertions --tracing --unit-testing --python-bindings --static` does not produce python bindings when invoking `make`.

**Comment by chasenorman** [comment]
```
(set-logic ALL)
(declare-datatypes ((wrapped_integer 0)) (((constructor (value Int)))))
(synth-fun f ((input wrapped_integer)) Bool ((bool Bool)) ((bool Bool ( (= (value input) 0)))))
(declare-var x wrapped_integer)
(constraint (f x))
(check-synth)
```
Produces
```
(
(define-fun f ((input wrapped_integer)) Bool (= (value input) 0))
)
```
On the latest release. What am I missing?

**Comment by ajreynol** [comment]
Thanks a lot for reporting this.

This bug is caused by a mismatch in the semantics of datatype selectors in the SyGuS solver and the underlying verification subsolver.

At the moment, using the option `--dt-share-sel` makes this example give the correct behavior (it should return `fail`), I will submit a PR to fix the issue.
