### ISSUE TITLE
Reference counting problem

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#8079]
`make check` fails In debug mode on `regress2/strings/replace_re.smt2` with a reference counting error.
This happens on my Mac (not on Linux) and it's related to field `d_visited` in `smt/witness_form.h`.
My guess is that `d_visited` should be reset between successive calls to checkProof because it may contain
dead nodes.

Here's the trace:
```
./build.debug/bin/cvc5 test/regress/regress2/strings/replace_re.smt2 '--strings-exp' '--check-proofs' '--proof-granularity=theory-rewrite'
sat
sat
sat
unsat
sat
unsat
Fatal failure within void cvc5::NodeTemplate<false>::assertTNodeNotExpired() const [ref_count = false] at /Users/dutebrun/Repos/cvc5/src/./expr/node.h:219
Check failure

 d_nv->d_rc > 0
TNode pointing to an expired NodeValue
Abort
```

**Command line arguments**:
```
test/regress/regress2/strings/replace_re.smt2 --strings-exp --check-proofs --proof-granularity=theory-rewrite
```

**cvc5 version/commit**: 8ac648bebbbb0621d83689f66f7180ca33cf6534

**Operating system**:  MacOS/Big Sur 11.6.3

**`configure.sh` options** 
```
debug --name=build.debug --auto-download
```

**Comment by ajreynol** [comment]
Thanks for the report, I'm not sure what the justification for TNode was here, and this is not performance critical, so I've made the code safer to use Node now. This should fix the issue.

**Comment by BrunoDutertre** [comment]
OK. Thanks, that seems to work now.
