### ISSUE TITLE
Failure in algebraic number construction

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#8126]
``make check`` fails on test 772.

More details:
```
bin/cvc5 ../test/regress/regress0/nl/proj-issue-451-ran-combination-1.smt2
Assertion failed: (lp_upolynomial_is_primitive(f)), function lp_algebraic_number_construct, file algebraic_number.c, line 45.
Abort
```

I'm using CVC5 commit 3dd30794611fa1e4344b0f7f3068211533b48f4f and the latest version of `libpoly` (https://github.com/SRI-CSL/libpoly/commit/1383809f2aa5005ef20110fec84b66959518f697).

This seems to happen in `RealAlgebraicNumber::RealAlgebraicNumber(const Rational& r)`
The debugger shows that the polynomial in question (derived from r) has a negative lead coefficient.

**Comment by nafur** [comment]
It took me a while to realize that you obviously need a debug build of libpoly to trigger this assertion...
