### ISSUE TITLE
Parser/LineBuffer bug

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#8374]
When reading from stdin, cvc5 will sometimes throw weird errors caused by memory corruption.

Here's a small example:
```
(set-info :smt-lib-version 2.6)
(set-logic ALL)
(set-info :source |
Generated by: Andrew Reynolds
Generated on: 2018-04-25
Generator: PyEx, converted to v2.6 by CVC4
Application: Symbolic Execution of Python Programs
Target solver: CVC4, Z3, Z3str2
Publications: "Scaling Up DPLL(T) String Solvers Using Context-Dependent Simplification" by A. Reynolds, M. Woo, C. Barrett, D. Brumley, T. Liang, and C. Tinelli, CAV 2017.
|)
```

And here's what happens:
```
./bin/cvc5 < test.smt2
(error "Parse Error: <stdin>:9.1: std::bad_alloc")
```
This is easier to reproduce with CVC5 built in debug mode (or to see with valgrind).

The bug appears to be a combination of `antlr_input.h`  and `antlr_line_buffered_input` and `line_buffer`.
The line_buffer maintains several segments, one per line of input.  Function `AntlrInput::tokenText` assumes 
that `token->start` and `token->stop` are pointers in a contiguous block of memory. This is not true
if the input stream is managed via a line_buffer and if the token spans several lines.

**Comment by nafur** [comment]
This sounds an awful lot like #791, although the error looks slightly different.

**Comment by BrunoDutertre** [comment]
Well, hope you see this as an encouragement to fix this old bug.
