### ISSUE TITLE
String solving escape sequence in Java

### ISSUE THREAD

**Issue by baierd** [cvc5/cvc5#8394]
Hello CVC5 team,

CVC5 seems to recognize Unicode escape sequences not correctly in Java. For example "\\u{1234}" should be recognized as a single char. CVC5 however recognizes this as "\u{5c}u{1234}" with "\u{5c}" as the first char (as \) and the rest being single chars (the second character is "u" for example). Expected behavior would be that is recognizes the sequence as 1 char.

Example in CVC5 Java:
```
Solver s = ...;
s.setOption("produce-models", "true");
s.setOption("finite-model-find", "true");
s.setOption("sets-ext", "true");
s.setOption("output-language", "smtlib2");
s.setOption("strings-exp", "true");

Term var = s.mkConst(s.getStringSort(), "variable");
Term charAt = s.mkTerm(Kind.STRING_CHARAT, s.mkString("\\u{1234}"), var);
// Check SAT
// s.getValue(var) returns "\u{5c}" which is "\"
```

Thank you for your help.

**Comment by mudathirmahgoub** [comment]
Did you try to set [useEscSequence](https://cvc5.github.io/docs/cvc5-0.0.7/api/java/io/github/cvc5/api/Solver.html#mkString(java.lang.String,boolean)) argument as true?
```java
Solver s = new Solver();
s.setOption("produce-models", "true");
Term var = s.mkConst(s.getStringSort(), "variable");
Term constraint = s.mkTerm(Kind.EQUAL, new Term[]{s.mkString("\\u{1234}", true), var});
s.checkSatAssuming(constraint);
System.out.println("variable: " + s.getValue(var)); 
```
output
```bash
variable: "\u{1234}"
```

**Comment by baierd** [comment]
That actually solves my problem completely. Sorry for the bother and thank you!
