### ISSUE TITLE
Parser error for quoted symbol.

### ISSUE THREAD

**Issue by NlightNFotis** [cvc5/cvc5#8489]
**Describe the bug**
Hello.

I have an SMTLIB2.6 file that I'm passing to `cvc5`.

When the file is passed to `cvc5`, I do get some issues around parsing errors related to unexpected tokens.

The file is this:

```lisp
(set-logic ALL)
(define-fun |B0| () Bool true)
(declare-fun |goto_symex::&92;guard#1| () Bool)
(define-fun |B1| () Bool |goto_symex::&92;guard#1|)
(define-fun |B2| () Bool (|not| |goto_symex::&92;guard#1|))
(declare-fun |main::1::result_signed!0@1#2| () (_ BitVec 32))
(declare-fun |main::1::first!0@1#1| () (_ BitVec 32))
(declare-fun |main::1::place!0@1#1| () (_ BitVec 32))
(assert (|=| |main::1::result_signed!0@1#2| (|bvashr| |main::1::first!0@1#1| |main::1::place!0@1#1|)))
(declare-fun |main::1::result_unsigned!0@1#2| () (_ BitVec 8))
(declare-fun |main::1::second!0@1#1| () (_ BitVec 8))
(assert (|=| |main::1::result_unsigned!0@1#2| ((_ |extract| 7 0) (|bvashr| ((_ |zero_extend| 24) |main::1::second!0@1#1|) |main::1::place!0@1#1|))))
(check-sat)
```

The exact error I'm seeing is:

```
(error "Parse Error: /tmp/shift_right.smt:12.59: Unexpected token: '|extract|'.

  ...main::1::result_unsigned!0@1#2| ((_ |extract| 7 0) (|bvashr| ((_ |zero...
                                          ^
")
```

I believe the issue is that `cvc5` doesn't like some symbols being quoted. Indeed, as soon as I remove the quotes around `extract` and `zero_extend` in the last assert, `cvc5` does process the file and comes back with a result of `sat`.

I find this weird because according to my reading of the [SMTLIB2.6 specification](https://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf), a `symbol` is either a *quoted symbol* or a *simple symbol*. It looks to me like `cvc5` shouldn't have an issue with these two symbols being quoted - in this case both the *simple symbol* and the *quoted symbol* definitions should be equivalent.

Is this an actual issue, or is perhaps a reason this happens (and my understanding of the spec is faulty)?

---

**Command line arguments**: `$ cvc5 --lang=smtlib2.6 /tmp/shift_right.smt` (with `/tmp/shift_right.smt` being the file quoted above. 

**cvc5 version/commit**:
```
$ cvc5 --version
This is cvc5 version 0.0.9-dev.10.81bcd1aef [git 81bcd1aef on branch main]
compiled with GCC version Apple LLVM 13.1.6 (clang-1316.0.21.2)
on Mar 31 2022 10:02:02
``` 

**Operating system**:
```sh
$ sw-vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

**`configure.sh` options**: `$ ./configure.sh --auto-download`

**Comment by ajreynol** [comment]
Thanks for pointing this out, indeed this should not give a parse error.  This is fixed in my latest PR.

**Comment by NlightNFotis** [comment]
@ajreynol Thanks for sorting this out so fast.

I can confirm the fix works.
