### ISSUE TITLE
cvc5 Refutation Soundness issue on QF_NRA

### ISSUE THREAD

**Issue by KJongUk** [cvc5/cvc5#8638]
Hi,
For this formula z3 returns sat, but cvc5 v1.0.0 returns unsat.

<pre>
<code>
$ z3 small.smt2 
sat
$ cvc5 small.smt2 
unsat
$ cat small.smt2
(set-logic QF_NRA)
(declare-fun y () Real)
(declare-fun pi () Real)
(declare-fun x () Real)
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(assert (< 13 c))
(assert (< c 19))
(assert (< (- 11) a))
(assert (< a (/ (+ y pi (- b)) c)))
(assert (< 16 b))
(assert (< b 48))
(assert (and (> (* y y y y b) 0) 
             (> (* y (+ 1 (* pi (/ (- 1) 2)) (* y y pi (/ 1 6)))) 0) 
             (> pi (/ 15707963 5000000)) 
             (> (/ 31415927 10000000) pi) 
             (> (* pi (/ 1 2)) y) 
             (> x 0) 
             (> y x)
        )
)
(check-sat)
</code>
</pre>

**Comment by ajreynol** [comment]
I can confirm z3 gives this model which we accept:
```
  (define-fun c () Real
    14.0)
  (define-fun a () Real
    (- 10.0))
  (define-fun b () Real
    17.0)
  (define-fun y () Real
    (/ 3.0 2.0))
  (define-fun pi () Real
    (/ 26353589.0 8388608.0))
  (define-fun x () Real
    1.0)

**Comment by nafur** [comment]
Once again, the issue is in the variable elimination that wraps the coverings solver... the issue is already avoided with `--no-nl-cov-var-elim`. I'll have a look.
