### ISSUE TITLE
Incorrect result for separation logic

### ISSUE THREAD

**Issue by TDacik** [cvc5/cvc5#8659]
For the following input:
```smt
(set-logic ALL)

(declare-sort Loc 0)
(declare-heap (Loc Loc))

(declare-const x Loc)
(declare-const y Loc)

(assert (distinct x y))

(assert
  (sep
    (not (wand
      (pto x x)
      (not (pto x x))
    ))
    (pto x y)
  )
)

(check-sat)
```
cvc5 (#8652, and also CVC4 version 1.5) returns `unsat`, but the formula should be satisfiable by a single pointer from *x* to *y*. This should be more clear when the negated magic wand is rewritten using septraction to the following equivalent formula:

```smt
(assert (distinct x y))
(assert 
  (sep 
    (septraction (pto x x) (pto x x)) 
    (pto x y)
  )
)
````
The septraction can be satisfied by an empty heap and the separating conjunction by a pointer from *x* to *y.* When the assertion  `distinct x y` is removed, cvc5 returns the correct result.

**Comment by ajreynol** [comment]
Thanks, I can reproduce and I've tracked down the issue.  We are using a lemma scheme that is unsound when used on problems with magic wand.

I'm working on a fix.
