### ISSUE TITLE
invalid model issue

### ISSUE THREAD

**Issue by KJongUk** [cvc5/cvc5#8755]
Hi,
For the following formula, cvc5(version 1.0.1-dev.49.6a9a932b5) gives an invalid model:
<pre>
<code>
$ cvc5 --check-models -q bug.smt2 
Fatal failure within void cvc5::internal::smt::CheckModels::checkModel(cvc5::internal::theory::TheoryModel*, const cvc5::context::CDList<cvc5::internal::NodeTemplate<true> >&, bool) at /cvc5/src/smt/check_models.cpp:134
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (= (- x y) (int.pow2 x))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
$ cat bug.smt2
(set-logic QF_LIA)
(declare-fun x () Int)
(declare-fun y () Int)
(assert (= (- x y) (int.pow2 x)))
(check-sat)
</code>
</pre>

**Comment by ajreynol** [comment]
This is caused by the logic setting, which is disabling the POW2 solver altogether.  We need to throw a logic exception for this.
