### ISSUE TITLE
Issue with resource limit

### ISSUE THREAD

**Issue by kanigsson** [cvc5/cvc5#8776]
[slow.smt2.txt](https://github.com/cvc5/cvc5/files/8697862/slow.smt2.txt)

Hello,

On the attached file, cvc5 1.0 stops immediately with a limit set to 7833, and runs indefinitely with a limit set to 7834:
```
$ time cvc5 --rlimit=7833 slow.smt2
unknown

real	0m0.025s
user	0m0.025s
sys	0m0.000s
$ time cvc5 --rlimit=7834 slow.smt2 
^Ccvc5 interrupted by user.


real	1m28.398s
user	1m28.361s
sys	0m0.024s
```
When running with `--stats-internal`, it seems most time is spent in `theory::bv::BVSolverBitblast::cadical::solve_time`. Could you take a look?

**Comment by mpreiner** [comment]
CaDiCaL currently only  supports time limits, but no resource limits. I'll take a look and add resource limits support.

**Comment by kanigsson** [comment]
I can confirm that this fixed the issue. Thanks!
