### ISSUE TITLE
unexpected bad performance

### ISSUE THREAD

**Issue by kanigsson** [cvc5/cvc5#8786]
[bench.tgz.txt](https://github.com/cvc5/cvc5/files/8706781/bench.tgz.txt)

Hello cvc5 team,

We usually have cvc5 and z3 about on par in terms of performance, but on new input code we have cvc5 perform significantly worse (CVC4 behaves the same here), to the point where I begin to suspect we are doing something wrong. From that code base, I selected at random 10 benchmarks where z3 proves the goal immediately, and cvc5 doesn't prove it in 2 minutes (attached). Can you spot something obvious in the files that blocks cvc5? Is there anything else we could do to investigate this? Thank you in advance.

**Command line arguments**: None needed to reproduce, though we usually use `--prenex-quant=none` as suggested on #8631 .
**cvc5 version/commit**: cvc5 1.0.0
**Operating system**: openSUSE Leap 15.3

The configuration is identical with the one submitted on #8631.

**Comment by ajreynol** [comment]
It seems that the use of `bv2nat` may be to blame.

Just to clarify, you are saying that both cvc5 and versions of CVC4 are bad on this set?  (This is in line with what I am seeing).

I believe the solution here may be for us to handle bv2nat more lazily.

**Comment by ajreynol** [comment]
Also, there is an experimental option `--solve-bv-as-int=iand` that solves several of the benchmarks in the attached set quickly.  This option attempts to convert bitvector operators to integer ones during preprocessing.

FYI @yoni206

**Comment by yoni206** [comment]
I will check if more benchmarks from this set can be solved using this option.

**Comment by kanigsson** [comment]
Yes, I meant to say CVC4 and cvc5 both perform equally badly, so this is not a regression wrt CVC4. I will try this option, but it sounds very radical at first glance, so I fear it will have a strong impact on all our other benchmarks. I will let you know.

**Comment by kanigsson** [comment]
A more general question, is submitting benchmarks to you a good way to communicate with you? I kind of feel bad dropping hundreds or thousands of files on you (that's why I only selected 10). If it helps you, I can submit many more files which exhibit the issue here.

**Comment by barrettcw** [comment]
Yes!  We really appreciate getting benchmarks that exhibit problems, performance or otherwise.  Submitting them in small batches as you are doing is also useful, as often a fix for a small batch will fix many others.  Thanks!

**Comment by kanigsson** [comment]
[bench.tgz.txt](https://github.com/cvc5/cvc5/files/8735107/bench.tgz.txt)
Summarizing the situation, the `--solve-bv-as-int=iand` does degrade overall performance for us a little bit, especially on code that actually uses bitwise reasoning (that's why we use bitvectors in the first place). Also, it *does* improve on the new codebase I mentioned, but not a lot. I am attaching a new set of files that are cvc5 doesn't prove regardless of the presence of that option (timeout is one minute), and z3 proves very quickly. I hope this is useful for you. Do you have any other suggestions what to improve there?
Another general remark is that we are pretty open to doing changes in the way we generate VCs as we have a lot of control over this. So any suggestions in this direction are welcome as well. Concerning bv2nat, it might be a bit difficult to avoid, but not impossible if that's what we need to do.

**Comment by ajreynol** [comment]
Hello @kanigsson , cvc5 should now have improved support for bv2nat and int2bv internally.

I've noticed that the latest version is now better on the benchmarks attached to this issue.

Perhaps you can run a larger test to confirm?

**Comment by kanigsson** [comment]
That's great news! I will check this out as soon as I have some time.

**Comment by kanigsson** [comment]
Hello @ajreynol,

I ran some tests on the original set of 10351 benchmarks from which I extracted the reproducers of this ticket, all supposed to be provable. Z3 proves 10173. The older cvc5 1.0 proves just 8313, while the newer one proves 9658 (all runs are with 60s timeout). A huge improvement.

On our more general benchmarks, performance is almost the same, which is good, that is, the changes don't degrade performance in the general case.

I suggest we close the issue and we will possibly create new benchmarks if other issues come up. Thanks!

**Comment by ajreynol** [comment]
That's great to hear.

FYI, I have one more improvement in the works that should give another boost on these benchmarks. I will ping you when it is merged.

Let's go ahead and close this issue, I've added the benchmarks from this issue to my test setup.  Do keep me posted if you have further benchmarks you'd like me to look at.
