### ISSUE TITLE
Incorrect result for simple entailment in separation logic

### ISSUE THREAD

**Issue by TDacik** [cvc5/cvc5#8841]
For the following input:
```smt
(set-logic QF_ALL)
(declare-sort Loc 0)
(declare-heap (Loc Loc))

(declare-const x1 Loc)
(declare-const x2 Loc)

(assert (pto x1 x2))
(assert (not (pto x2 x2)))

(check-sat)
```
cvc5 (#8768) returns `unsat` while the formula is clearly satisfiable by a heap {x1 -> x2} such that interpretations of x1 and x2 are distinct. Since #8652 returns the correct result, this seems to be a bug introduced probably in #8768.

**Comment by ajreynol** [comment]
Thanks a lot for the report.  This is fixed in my latest PR.
