### ISSUE TITLE
No more models when resource limit is hit

### ISSUE THREAD

**Issue by yannickmoy** [cvc5/cvc5#8854]
As part of our migration from CVC4 to cvc5 in both Why3 and SPARK, we've hit a problem that seems to come from a change in how cvc5 handles models when resource limit (time or steps) is hit. CVC4 used to display a model, which we could compare with other models (calling the prover with more or less context), as well as filter valid models by executing them with different semantics (as described in the article "Explaining Counterexamples with Giant-Step Assertion Checking" at F-IDE 2021).

Instead, cvc5 displays the following message instead of a model when a resource limit is hit:

```
Cannot get model since model is not available. Perhaps the most recent call to check-sat was interrupted?
```

Is there a switch to restore the previous behavior?
Otherwise, could such a functionality be provided?
Otherwise, we won't be able to use cvc5 for getting models ("counterexamples" in our case) when proof fails.

Ideally of course, we'd prefer cvc5 to validate as much as possible the partial model obtained when a resource limit is hit, against ground facts, before displaying it, so that we don't have to filter bad models out. But discarding all partial models is not a suitable solution in our case.

**Comment by 4tXJ7f** [comment]
@yannickmoy Thank you for the report. This looks like an unintentional change due to some refactoring and I am taking a look at restoring the old behavior.

**Comment by 4tXJ7f** [comment]
@yannickmoy Which version of CVC4 were you using previously with what kind of options? I can't seem to get the desired behavior from CVC4 1.8 nor CVC4 1.7 using `--rlimit` (I get the error message above with CVC4 1.8 and an assertion failure with CVC4 1.7).

**Comment by yannickmoy** [comment]
@4tXJ7f we're still using CVC4 1.8 for counterexample generation in SPARK. Why3 team is using currently CVC4 1.7. And we're both relying on ``--rlimit``. We're using ``(get-model)`` to get the complete model. Do you want an example VC?

**Comment by 4tXJ7f** [comment]
Yes, a VC together with the command line arguments would be very helpful.

**Comment by solene-moreau** [comment]
@4tXJ7f , please find attached an example file reproducing the behavior described by @yannickmoy , which is extracted from our bench of tests in the Why3 team.
With `cvc4-1.8 --rlimit=150000 threshold.smt2` we get a model, but with `cvc5-1.0.0 --rlimit=150000 threshold.smt2` we get the error `(error "Cannot get model since model is not available. Perhaps the most recent call to check-sat was interrupted?")`.

[threshold.zip](https://github.com/cvc5/cvc5/files/8890604/threshold.zip)

**Comment by 4tXJ7f** [comment]
@solene-moreau Thank you for the example. On my machine, it seems like CVC4 1.8 actually seems to solve the problem within the allotted resource limit:

```
$ ./cvc4-1.8-x86_64-linux-opt threshold.smt2 --rlimit=150000
sat
(model
(define-fun n () (_ BitVec 32) #b11111111111111111111111111111111)
(define-fun min () (_ BitVec 32) #b10000000000000000000000000000000)
(define-fun max () (_ BitVec 32) #b01111111111111111111111111111111)
(define-fun usx () (_ BitVec 32) #b11111111111111111111111111111111)
(define-fun result () (_ BitVec 32) #b00000000000000000000000000000000)
)
```

Are you seeing the same behavior? If I further limit the resources to 1500, I am getting:

```
$ ./cvc4-1.8-x86_64-linux-opt ../threshold.smt2 --rlimit=1500
unknown
(error "Cannot get model since model is not available. Perhaps the most recent call to check-sat was interupted?")
```

It looks to me like CVC4 and cvc5 behave the same on this problem, but cvc5 does not solve the problem within those resource limits, which leads to the error message. Do you see the same behavior on your machine? Do you have another example where CVC4 answers `unknown` followed by a model?

Relatedly, I have done a git bisect and found a commit that changed our policy with respect to how we handle conversions between integers and bit-vectors (commit 5fb5d6030). Is `bv2nat` a common operator for you?

**Comment by solene-moreau** [comment]
@4tXJ7f indeed I agree with your analysis, even if we lose a model when switching from CVC4 to cvc5 with this file it is not related to the issue described above.
As soon as I have another better example file, I will submit it here for further investigation.

> Relatedly, I have done a git bisect and found a commit that changed our policy with respect to how we handle conversions between integers and bit-vectors (commit [5fb5d60](https://github.com/cvc5/cvc5/commit/5fb5d6030aa031d5f63676ec29ffa8e158fa5c6a)). Is `bv2nat` a common operator for you?
Yes indeed, it is.

**Comment by solene-moreau** [comment]
@4tXJ7f  please find here a new example.
When calling CVC4 with a time limit or with a resource limit we get the answer `unknown` but with a model.
```
cvc4-1.8 --tlimit-per=100 steplimit.smt2
unknown
(:reason-unknown timeout)
(model
(define-fun x () Int 2)
(define-fun y () Int 3)
(define-fun z () Int 4)
)
```
```
cvc4-1.8 --rlimit=15000 steplimit.smt2
unknown
(:reason-unknown resourceout)
(model
(define-fun x () Int 2)
(define-fun y () Int 3)
(define-fun z () Int 3)
)
```
When using cvc5 on the same example with a time limit or a resource limit, we do not get a model.
```
cvc5-1.0.0 --tlimit-per=100 steplimit.smt2
unknown
(:reason-unknown timeout)
(error "Cannot get model since model is not available. Perhaps the most recent call to check-sat was interrupted?")
```
```
cvc5-1.0.0 --rlimit=15000 steplimit.smt2
unknown
(:reason-unknown resourceout)
(error "Cannot get model since model is not available. Perhaps the most recent call to check-sat was interrupted?")
``
[steplimit.zip](https://github.com/cvc5/cvc5/files/8939723/steplimit.zip)
`

**Comment by 4tXJ7f** [comment]
@solene-moreau Thank you for that example. I am looking into this.
@claudemarche Thank you for elaborating. The change was not intentional. We are currently looking into what caused the change in behavior and we are planning to improve support for producing models after answering `unknown`. This includes documenting the circumstances under which we expect to be able to produce a model.
