### ISSUE TITLE
Build failure related to option.h

### ISSUE THREAD

**Issue by kanigsson** [cvc5/cvc5#8861]
Hello,

We sporadically see build failures that terminate the build with this message:
```
.../cvc5/src/src/parser/tptp/tptp.cpp:24:10: fatal error: options/options.h: No such file or directory
   24 | #include "options/options.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This happens in maybe 1 out of 10 builds, and only on a system with a large number of cores (256 cores). We use `make -j 256` on that machine.

The configuration is as described in #8631.

This has low priority for us as we simply avoid building cvc5 on that machine.

**Comment by mpreiner** [comment]
Turns out that these headers are not required anymore in the TPTP parser. Removed them in #8864.
