### ISSUE TITLE
Another incorrect result for separation logic

### ISSUE THREAD

**Issue by TDacik** [cvc5/cvc5#8863]
For the input
```smt
(set-logic ALL) 
 
(declare-sort Loc 0) 
(declare-heap (Loc Loc)) 
 
(declare-const z Loc) 
(declare-const y Loc) 
(declare-const x Loc) 
 
(assert 
  (sep 
    (not (wand 
      sep.emp 
      (not (pto x z)) 
    ))  
    (distinct y z) 
    (distinct y x) 
    (distinct z x) 
  ) 
) 
 
(assert 
  (pto x y) 
) 
 
(check-sat) 
(get-model) 
```

cvc5 (#8860) returns *sat* while the formula should be unsatisfiable. This can be demonstrated on an equivalent formula where the negated magic wand is replaced by the septraction operator:
```smt
(set-logic ALL) 
 
(declare-sort Loc 0) 
(declare-heap (Loc Loc)) 
 
(declare-const z Loc) 
(declare-const y Loc) 
(declare-const x Loc) 
 
(assert 
  (sep 
    (septraction 
      sep.emp 
      (pto x z) 
    )
    (distinct y z) 
    (distinct y x) 
    (distinct z x) 
  ) 
) 
 
(assert 
  (pto x y) 
) 
 
(check-sat) 
(get-model) 
```

The septraction can be satisfied only by a heap *h* = {x -> z} since this is the only heap that can be extended by an empty heap to obtain a pointer from *x* to *z*. Because *y* and *z* are required to be distinct, *h* is not a model of (pto x y).

The result was correct in #8652, but not in #8768.

**Comment by ajreynol** [comment]
Thanks a lot for debugging this. My fix for `wand` was not sufficient unfortunately, so cvc5 is currently model-unsound in general when `wand` is present (some unsat problems may return "sat").

I will get back to you about a fix.
