### ISSUE TITLE
Removing JNI dependencies from CVC5 JNI binaries

### ISSUE THREAD

**Issue by baierd** [cvc5/cvc5#8869]
CVC5 compiles JNI into its `libcvc5jni.so` in such a way that the JNI binaries are always needed as explicit dependencies.
This behavior is bad for a multitude of reasons, i.e. shipping precompiled binaries gets harder.
CVC4 and most other solvers with Java bindings don't need this (and you even wondered why you need this in a comment regarding the Java binding tests).

A solution is simply replacing the following 2 lines in cvc5/src/api/java/CMakeLists.txt:

```
target_link_libraries(cvc5jni PRIVATE ${JNI_LIBRARIES})
target_include_directories(cvc5jni PUBLIC ${JNI_INCLUDE_DIRS})
```

with:

```
include_directories(${JNI_INCLUDE_DIRS})
link_libraries(${JNI_LIBRARIES})
```

Note: i don't know much about CMake, i just looked up how other solvers compile JNI into the binaries.

**Comment by 4tXJ7f** [comment]
@baierd Thank you for bringing this up. I have submitted a PR that avoids unnecessarily linking the `libjvm` and `libjawt` libraries.
