### ISSUE TITLE
diagnostic output channel setting

### ISSUE THREAD

**Issue by LeventErkok** [cvc5/cvc5#8900]
Looks like #7478 is back

Given:

```
(set-option :diagnostic-output-channel "stdout")
(set-option :produce-models true)
(set-logic QF_BV)
(declare-fun s0 () Bool)
(assert s0)
(check-sat)
```

Putting the above in `a.smt` and running

```
$ cvc5 a.smt
```

Produces the file `"stdout"` in the current directory. Version info: (Downloaded directly from your GitHub release):

```
$ cvc5 --version
This is cvc5 version 1.0.0
compiled with GCC version Apple LLVM 13.0.0 (clang-1300.0.29.30)
on Jun 18 2022 17:52:41
```

**Comment by LeventErkok** [comment]
@ajreynol Is there any chance this fix can be merged? It'd really help out with our use case. In particular, this is causing serious problems on Windows. (On Mac/Linux, it's annoying to have the stray file, on Windows apparently it flat out crashes since Windows doesn't allow filenames with quotes in them.) Thanks!

**Comment by ajreynol** [comment]
Yes, sorry for the delay.  The fix has been merged now.  Let me know if you have any issues.

**Comment by LeventErkok** [comment]
@ajreynol 

I gave this a try and unfortunately the pipe based communication seems to be broken. Perhaps related to https://github.com/cvc5/cvc5/issues/9257?

I'm wondering if your merge made the code that "flushed" the buffer after each line of output disappear. Can you check please?

**Comment by LeventErkok** [comment]
I did another test and `--stdin-input-per-line` parameter indeed fixes the issue.

Is this the recommended setting for pipe-based communication?

**Comment by LeventErkok** [comment]
@ajreynol 

To summarize; before this merge, communication was fine, but we were getting the `"stdout"` file created on Mac/Linux and on Windows this was choking due to being unable to create a file with a quotes in it.

After the merge, the pipeline communication completely hangs. So, I'm at a loss as to where to look for the culprit. As it stands CVC5 is no longer usable from a piped input after the merge.

**Comment by barrettcw** [comment]
We decided to enable --stdin-input-per-line by default.  Disabling this flag will cause problems for piped input.  If you're not seeing that this flag is on by default, maybe do a clean build and see if that fixes it.

**Comment by LeventErkok** [comment]
I downloaded the binary and didn't do a build. (March 2nd download from https://github.com/cvc5/cvc5/releases). I didn't change anything else.. Do I have to explicitly pass this parameter?

**Comment by barrettcw** [comment]
Ah - I see - it was not yet fixed in that release.  The latest nightly build has the fix and should work correctly.  We are also planning a new release on Monday that will have the fix.

**Comment by LeventErkok** [comment]
Cool; I'll wait till Monday to test it out!

**Comment by barrettcw** [comment]
For now, I suggest you go ahead and remove --no-interactive.  I believe this is the correct way to use cvc5 now.  Andy is out of town this week, but hopefully he can confirm when he returns.

**Comment by LeventErkok** [comment]
Thanks Andrew.. Looks like we have a working solution now. Indeed that warning would've made debugging easier for us; though kudos to @RyanGlScott who somehow figured it out that was the culprit.
