### ISSUE TITLE
str.replace_re function result different from SMT document.

### ISSUE THREAD

**Issue by KJongUk** [cvc5/cvc5#8931]
Hi,
For this formula, CVC5 returns unsat.
<pre>
$cvc5 bug.smt2
unsat
$cat bug.smt2
(set-logic QF_SLIA)
(assert (= "-" (str.replace_re "-" (str.to_re "-") "")))
(check-sat)
</pre>

According to SMT-LIB document,
<pre>
; (str.replace_re s r t) is the string obtained by replacing the
; shortest leftmost non-empty match of r in s, if any, by t.
; Note that if t is empty, the result is to prepend t to s.
</pre>
I consider that <code>(str.replace_re "-" (str.to_re "-") "")</code> equals "-". 
But CVC5 reports that this formula is empty string "".

**Comment by 4tXJ7f** [comment]
That looks like a mistake in the SMT-LIB specification. It should say that if `r` matches the empty string, `t` is prepended to `s` (to mirror the semantics of `str.replace`).

The definition of the semantics:

```
  * (str.replace_re String String String String)

    - ⟦str.replace_re⟧(w, L, w₂) = w        if no substring of w is in L

    - ⟦str.replace_re⟧(w, L, w₂) = u₁w₂u₂ 
      where u₁, w₁ are the shortest words such that 
            - w = u₁w₁u₂
            - w₁ ∈ L
                                            if some substring of w is in L
```

seems to confirm my suspicion.

**Comment by KJongUk** [comment]
Thank you for answering @4tXJ7f.
After reading your suspicion, that looks like a mistake in the SMT-LIB spec, like your comment.
I will close this issue.
