### ISSUE TITLE
Unexpected Array theory write-chains CVC5 error when using --finite-model-find

### ISSUE THREAD

**Issue by robby-phd** [cvc5/cvc5#8933]
**Describe the bug**
The attached SMT2 query causes CVC5 to give the following unexpected error when using `--finite-model-find`:
```
(error "Array theory solver does not yet support write-chains connecting two different constant arrays")
```

**Command line arguments**: `--lang=smt2.6 --finite-model-find`
**cvc5 version/commit**: 1.0,latest (2022-06-30-9480126)
**Operating system**: macOS Monterey (12.4)

[test.smt2.gz](https://github.com/cvc5/cvc5/files/9046948/test.smt2.gz)

**Comment by robby-phd** [comment]
Thanks for the response. Would it be possible to return `unknown` in situation like this (if the logic is set to `ALL`)? It's not a high priority as I'm already special casing this in my tool for cvc5 and treat it as unknown, but I thought it'd be nice to not have to do that for similar kinds of errors.

**Comment by ajreynol** [comment]
This no longer reproduces on current master. The benchmark in question now times out.
