### ISSUE TITLE
Array Theory Write Chain Error With Single Const Array

### ISSUE THREAD

**Issue by d-xo** [cvc5/cvc5#9038]
**Describe the bug**

The following query produces an error ("Array theory solver does not yet support write-chains connecting two different constant arrays") when I run it with cvc5. I'm not sure I understand why, since afaict there is only a single constant array (`emptyBuf`). 

Is this a cvc5 bug or am I misunderstanding the error message?

**Command line arguments**: None 
**cvc5 version/commit**: 1.0.1
**Operating system**: Linux (NixOS)
**Query:**

```smt2
(set-logic ALL)
(define-sort Byte () (_ BitVec 8))
(define-sort Word () (_ BitVec 256))
(define-sort Buf () (Array Word Byte))
(declare-fun k (Buf) Word)
(define-const emptyBuf Buf ((as const Buf) (_ bv0 8)))
(define-const buf0 Buf emptyBuf)
(define-const buf1 Buf buf0)
(define-const buf2 Buf buf1)
(define-const buf3 Buf buf2)
(define-const buf4 Buf (store buf3 (_ bv0 256) (_ bv1 8)))
(define-const buf5 Buf buf4)
(define-const buf6 Buf buf4)
(define-const buf7 Buf buf6)
(define-const buf14 Buf (store buf7 (_ bv0 256) (select (store buf6 (_ bv0 256) ((_ extract 7 0) (k buf5))) (_ bv0 256))))
(assert (= (_ bv0 256) (ite (= (_ bv0 256) (ite (= (_ bv0 256) (ite (= (k buf14) (_ bv0 256)) (_ bv1 256) (_ bv0 256))) (_ bv1 256) (_ bv0 256))) (_ bv1 256) (_ bv0 256))))
(check-sat)
```

**Comment by mpreiner** [comment]
Thanks for the bug report! It looks like the constant array check is overly restrictive in this case. I'll have a look.

**Comment by barrettcw** [comment]
Actually, both emptyBuf and buf4 are considered different constant arrays by cvc5 as they are arrays, all of whose entries are known and consist of constant values.  The error message is the result of a "write chain" between these two arrays, which cvc5 does not currently support.  Adding better support for constant arrays is on the wish list...

**Comment by d-xo** [comment]
Ah understood. This is unfortunate. Thanks for investigating.

I would be curious to understand the reason for this limitation, and whether there are alternative encoding strategies that could be used as a work around?

**Comment by msooseth** [comment]
Just adding one more case where we encounter this issue, as a reference to self, but also perhaps could be helpful for the CVC5 engineers. Hopefully this is not too much noise: 
[write-chains-error.smt2.gz](https://github.com/user-attachments/files/16310766/write-chains-error.smt2.gz)
