### ISSUE TITLE
recommended "re-configure with '-DENABLE_GPL -DENABLE_BEST'" not working with cmake-3.22.2

### ISSUE THREAD

**Issue by jwaldmann** [cvc5/cvc5#9044]
I am building from source on GNU/Linux (Fedora 36)

```
$ ./configure.sh --prefix=/opt/cvc5/cc8071138e5b9647483400af303eab9497c9913e --auto-download
...
cvc5 1.0.2-dev
...
GPL                       : off
Best configuration        : off
...
libraries which can improve cvc5's performance on arithmetic and bitvector
logics, re-configure with '-DENABLE_GPL -DENABLE_BEST'.
```
I am doing as suggested, but get this error
```
$ ./configure.sh --prefix=/opt/cvc5/cc8071138e5b9647483400af303eab9497c9913e --auto-download -DENABLE_GPL -DENABLE_BEST
CMake Error: Parse error in command line argument: ENABLE_GPL
 Should be: VAR:type=value

$ cmake --version
cmake version 3.22.2
```
With some guess-work I arrive at
```
$ ./configure.sh --prefix=/opt/cvc5/cc8071138e5b9647483400af303eab9497c9913e --auto-download -DENABLE_GPL:BOOL=on -DENABLE_BEST:BOOL=on
```
now `configure.sh` works, but the output is inconsistent:

```
...
cvc5 1.0.2-dev
...
GPL                       : on
Best configuration        : on
...
cvc5 license: modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
...
```
Still, the executable does seem to be linked against gmp:
```
$ cd build/
$ make -j
...
$ ldd bin/cvc5
...
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007f4edd4f6000)
```
Indeed the executable corrrectly prints
```
$ cvc5 
...
This version of cvc5 is linked against the following third party
libraries covered by the LGPLv3 license.
See licenses/lgpl-3.0.txt for more information.

  GMP - Gnu Multi Precision Arithmetic Library
  See http://gmplib.org for copyright information.

  LibPoly polynomial library
  See https://github.com/SRI-CSL/libpoly for copyright and
  licensing information.
```

```

**Comment by 4tXJ7f** [comment]
@jwaldmann Thanks for the report. The message is a bit confusing/wrong, because it describes options to be used when invoking CMake directly to configure the project. However, the recommended way of configure cvc5 is to use the `configure.sh` script (as you do) and the options there are called `--best --gpl`: `./configure.sh --best --gpl  --auto-download` should do the trick. Further, `-DENABLE_BEST` does not actually work anymore. The "best" configuration is instead purely handled at the level of the `configure.sh` script.

**Comment by 4tXJ7f** [comment]
Currently, cvc5 can't download GLPK automatically. Before configuring cvc5 with the `--best --gpl` options, please install GLPK using the [contrib/get-glpk-cut-log](https://github.com/cvc5/cvc5/blob/main/contrib/get-glpk-cut-log) script.

**Comment by 4tXJ7f** [comment]
I am closing this issue for now. Please feel free to reopen it or open a new one if you have any other questions.
