### ISSUE TITLE
Debug option to print out AST of SyGuS result?

### ISSUE THREAD

**Issue by wonhyukchoi** [cvc5/cvc5#9079]
Is there a debug option to print out the AST of a SyGuS result?
There is `-o sygus` to print out the enumerations `CVC5` did to reach its solution, but the exact Abstract Syntax Tree that it used is unclear.

For instance, if we want to synthesize a nullary function
```
(set-logic LIA)

(synth-fun f () Int
    ((a Int) (b Int))
    ((a Int (b 0 1
              (+ a a) ))
     (b Int (1 2)))
)

(constraint (= 5 f))
(check-synth)
```

We get
```
(
(define-fun f () Int (+ 1 (+ 1 (+ 1 2))))
)
```
But it is unclear how this solution was obtained; there are multiple valid AST's from the given grammar that could have resulted in this solution.

Is this something that can be easily added to `SygusEnumerator`?

**Comment by ajreynol** [comment]
Yes, this could be added as another debug option. I can look into this soon.
