### ISSUE TITLE
Installing the Pythonic API on Mac with apple silicon 

### ISSUE THREAD

**Issue by ruchou** [cvc5/cvc5#9146]
I was trying to install cvc5 python package on Macbook with m1 chip

[The documentation](https://cvc5.github.io/docs/latest/api/python/python.html) states `pip install cvc5` but that's giving

```
ERROR: Could not find a version that satisfies the requirement cvc5 (from versions: none)
ERROR: No matching distribution found for cvc5

```

It seems that there is no way I could install cvc5 for the MacBook with m1 chip

What's the best way to install cvc5?

**Comment by yoni206** [comment]
The build instructions are now updated in the documentation for both architectures:
https://cvc5.github.io/docs-ci/docs-main/api/python/python.html
