### ISSUE TITLE
Install.rst refers to CVC4

### ISSUE THREAD

**Issue by sjunges** [cvc5/cvc5#9165]
**Describe the bug**
The install.rst describes here https://github.com/cvc5/cvc5/blob/main/INSTALL.rst#compilation-on-macos a homebrew tap that refers to CVC4.

**Comment by vrcamillo** [comment]
I submitted a PR https://github.com/cvc5/homebrew-cvc5/pull/1 with a new homebrew formula proposal for cvc5 1.0.5.

**Comment by ajreynol** [comment]
@mpreiner can this be closed now?
