### ISSUE TITLE
Error occurred, when the parsed grammar contains division

### ISSUE THREAD

**Issue by BugBugSurvival** [cvc5/cvc5#9219]
**Describe the bug**
When the parsed grammar contains division, cvc5 throws an error below:
**(error "Parse Error: test-grammar.sl:24.1: A non-linear fact was asserted to arithmetic in a linear logic.
The fact in question: (div BOUND_VARIABLE_362 BOUND_VARIABLE_363)
")**

The line where the error showed up is: (div y_term y_cons), where y_term and y_cons are both Int.  And y_term is a non-terminal, y_cons are constant numbers. y_cons is defined as (y_cons Int (0 1)). And it also throws the same error at (mod y_term y_cons). 

The grammar is based on page 18th of _The SyGuS Language Standard Version 2.0_. ![Screenshot from 2022-10-12 16-02-44](https://user-images.githubusercontent.com/47865775/195384818-3f2f0093-7be7-48e5-9367-876f85acbb7d.png)

**Command line arguments**: cvc5 test-grammar.sl  
**cvc5 version/commit**: 1.0.2  
**Operating system**: Ubuntu 22.04.1 LTS 64-bit

**Comment by ajreynol** [comment]
The SyGuS language document should be amended to not include `div` / `mod` in the grammar for linear arithmetic.  See: https://smtlib.cs.uiowa.edu/logics-all.shtml#QF_LIA.
Strictly speaking, div/mod are not allowed in the LIA logic.  In practice, cvc5 can handle these operators in linear arithmetic for constant coefficients *other than 0*.   Regardless, for grammars with div/mod, the logic should be set to include NIA.

**Comment by BugBugSurvival** [comment]
Thank you! You helped me a lot.
