### ISSUE TITLE
Returning Arrays from Functions

### ISSUE THREAD

**Issue by avery-laird** [cvc5/cvc5#9223]
Hello,

It appears that CVC5 doesn't allow functions to return arrays. For example, creating a function that takes a floating point number and integer as input, then returns an array of floating point numbers, gives this error:

```
Invalid argument '(-> (_ FloatingPoint 11 53) Int (Array Int (_ FloatingPoint 11 53)))' for 'sort', expected function sort as codomain sort
```

I was wondering whether my assumption is correct, that CVC5 doesn't support this kind of function? Thanks for any help.

**Comment by 4tXJ7f** [comment]
@avery-laird Could you post the complete example? To have that context would be really useful.

**Comment by avery-laird** [comment]
Hi @4tXJ7f thanks for the quick reply, here's a minimal standalone example:

```cpp
#include <cvc5/cvc5.h>

using namespace cvc5;

int main() {
    Solver slv;
    auto FPSort = slv.mkFloatingPointSort(11, 53);
    auto Array = slv.mkVar(slv.mkArraySort(slv.getIntegerSort(), FPSort), "x");
    auto Idx = slv.mkVar(slv.getIntegerSort(), "idx");
    auto Val = slv.mkVar(FPSort, "val");
    auto Body = slv.mkTerm(STORE, {Array, Idx, Val});

    auto FunSort = slv.mkFunctionSort({Idx.getSort(), Val.getSort()}, Array.getSort());
    auto FunDef = slv.defineFun("Test", {Array, Idx, Val}, FunSort, Body);
}
```

Hopefully this helps, please let me know if there's any other info I can provide that might help. Thanks!

**Comment by ajreynol** [comment]
The issue is that a function is being used as the return sort of a `defineFun`.  The error message should have read: `...expected *non-*function sort as codomain sort`.

We do not accept function types as the return sort for defineFun. The reason is that such sorts are equivalent to sorts where the arguments of the returned function sort are moved to the arguments of overall defineFun.

An alternative way of writing the above example, which cvc5 should accept, is:
```
#include <cvc5/cvc5.h>

using namespace cvc5;

int main() {
    Solver slv;
    auto FPSort = slv.mkFloatingPointSort(11, 53);
    auto Array = slv.mkVar(slv.mkArraySort(slv.getIntegerSort(), FPSort), "x");
    auto Idx = slv.mkVar(slv.getIntegerSort(), "idx");
    auto Val = slv.mkVar(FPSort, "val");
    auto Body = slv.mkTerm(STORE, {Array, Idx, Val});

    auto FunDef = slv.defineFun("Test", {Array, Idx, Val, Idx.getSort(), Val.getSort()}, Array.getSort(), Body);
}

**Comment by avery-laird** [comment]
That works, thanks @ajreynol for clarifying!
