### ISSUE TITLE
cvc5 reports unknown for a simple sygus problem

### ISSUE THREAD

**Issue by ebmoon** [cvc5/cvc5#9230]
**Describe the bug**
cvc5 reports `unknown` for this simple sygus problem. (`(= x1 x3)` is a solution)
I have checked that the same issue occurs both in the macOS binary and the base python API.

```
(set-logic LIA)

(synth-fun f ((x1 Int) (x2 Int) (x3 Int)) Bool
    
    ((AP Bool) (I1 Int) (I2 Int))

    ((AP Bool ((= I1 I2) (distinct I1 I2)))
     (I1 Int (x1 x2))
     (I2 Int (x3)))
)

(constraint (not (f 1 0 0)))

(check-synth)
```

**Command line arguments**: no option
**cvc5 version/commit**: cvc5 version 1.0.2
**Operating system**: macOS 12.4 (Apple M1 silicon)

**Comment by ajreynol** [comment]
Thanks for the benchmark. Somewhat coincidentally, this issue was fixed a few days ago: https://github.com/cvc5/cvc5/commit/b500e9d1e6add1edbaf6866da6bc7a1bbd6a623f
The latest cvc5 should now give:
```
(
(define-fun f ((x1 Int) (x2 Int) (x3 Int)) Bool (distinct x2 x3))
)

**Comment by ebmoon** [comment]
The latest cvc5 works! Thank you for the answer.
