### ISSUE TITLE
Quantifiers in CVC5 vs Z3

### ISSUE THREAD

**Issue by avery-laird** [cvc5/cvc5#9234]
Hello, I've run into some cases where CVC5 returns unknown and Z3 returns sat/unsat. Below is a short example with three main assertions:

1. `n>0`
2. `m>0`
3. for all `s` between `0` and `n`, `array[s] >= array[s+1]` and `array[s]` is non-negative:

```smt2
(set-logic ALL)
(declare-fun n () Int)
(assert (> n 0))
(declare-fun m () Int)
(assert (> m 0))
(declare-fun array () (Array Int Int))
(assert (forall ((s Int))
  (let ((a!1 (and (<= (select array s) (select array (+ s 1)))
                  (>= (select array s) 0))))
    (=> (and (>= s 0) (<= s n)) a!1))))
(check-sat)
```

CVC5 returns `unknown` for this example (or will run indefinitely if using certain options, e.g. cegqi-all). Z3 returns `sat` with an example fairly quickly (in about 0.01sec). 

I was wondering whether there are some options I can try in CVC5 to get comparable behaviour with Z3? Or in general some suggestions for how to solve these kinds of problems in CVC5/whether it's currently possible? Thanks for any help or insights.

**Comment by ajreynol** [comment]
cvc5 can solve this example using specialized techniques for bounded integer quantification.  Additionally this benchmark requires disabling E-matching to avoid a matching loop.  So, this set of command line options solves the problem:

`--fmf-bound --no-e-matching`.

Although in general, I would not recommend using `--no-e-matching` by default, unless *all* quantified formulas in the problem have bounded ranges.

**Comment by avery-laird** [comment]
Thanks very much @ajreynol for the quick and helpful answer. This works great for my purposes.
