### ISSUE TITLE
feature request: windows python package

### ISSUE THREAD

**Issue by florianschanda** [cvc5/cvc5#9235]
Hi,

First off all, the PyPI CVC5 package is working like a charm. Thank you so much for providing it. I may have a chance to develop and roll out a tool based on this; but the environment in question is a mixed windows / linux environment. Is there any chance you can provide a windows version of the python cvc5 package?

I fully understand how nasty it would likely be, and I am sorry for asking for it. :/

**Comment by barrettcw** [comment]
Hi Florian - nice to hear from you.  As you have guessed, getting a windows version of the python is indeed quite a painful task.  It is on our roadmap, but not for the near future.  The task is currently slated to be accomplished near the end of a 2-year project we hope to receive funding for sometime next year.

There are two ways you could possibly help speed this up.  First, you are welcome to do it yourself and submit a PR.  :)

Second, we have a new center (the Center for Automated Reasoning, or Centaur - check it out here: https://centaur.stanford.edu/affiliates_and_sponsors.html).  The purpose of the center is to facilitate collaborations with industry.  If your employer were to join the center, we could earmark the corresponding funding for *your* high-priority tasks.

**Comment by daniel-larraz** [comment]
With the latest release (1.2.0), we are now providing official PyPI packages for Windows. Closing this as resolved.
