### ISSUE TITLE
Shared libraries are unversioned

### ISSUE THREAD

**Issue by swt2c** [cvc5/cvc5#9273]
When building shared libraries, the resulting shared libraries are unversioned, e.g. `libcvc5.so`.  Is this intentional?

In CVC4, the shared libraries were versioned, e.g.:
```
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man3/libcvc4.3
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man3/libcvc4parser.3
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/lib/x86_64-linux-gnu/libcvc4.so.7
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/lib/x86_64-linux-gnu/libcvc4.so
```

**Comment by mpreiner** [comment]
@swt2c Thanks for the bug report. That's definitely not intentional, we'll have a look.
