### ISSUE TITLE
[Question]: How to parse a code in file using Base Python API?

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#9316]
Hello, I am a novice in Base Python API of cvc5. Recently, I tried to parse a code written in smtlibv2 through base python. However, I've never found any method to do even though I went over documentation(https://cvc5.github.io/docs/cvc5-1.0.2/api/python/base/python.html)
Is there any method to do this? For example, there are some functions(e.g. parse_smt2_string or parse_smt2_file) in z3 to do.

Thanks for your time!

**Comment by ajreynol** [comment]
We are in the process of reimplementing our parser.  When this is complete, we will export it to Python and Java.  The parser's API is planned to have methods for parsing terms, commands and files.

**Comment by ajreynol** [comment]
This is now available in our API, for example see https://cvc5.github.io/docs/cvc5-1.1.0/examples/parser.html.
