### ISSUE TITLE
Arithmetic result of get-qe is not strictly typed

### ISSUE THREAD

**Issue by daniel-larraz** [cvc5/cvc5#9375]
This is related to issue #7870. Consider this script: [ccp11.lus.qe.txt](https://github.com/cvc5/cvc5/files/10303877/ccp11.lus.qe.txt)

The term returned by `get-qe` contains the following subterms: `(not (>= (* (- 1) top.impl.usr.zz5@0) (- 100)))`, `(not (>= top.impl.usr.zz5@0 0))` where `top.impl.usr.zz5@0` is a real constant.

I was expecting cvc5 to generate subterms `(not (>= (* (- 1.0) top.impl.usr.zz5@0) (- 100.0)))`, `(not (>= top.impl.usr.zz5@0 0.0))` instead.

**Command line arguments**: `--lang=smt2`
**cvc5 version/commit**:  cvc5 1.0.3 (e7a16c6)
**Operating system**: Ubuntu 20.04

**Comment by ajreynol** [comment]
Actually it seems the term returned by `get-qe` is strictly typed:
```
(or top.res.init_flag@0 top.impl.usr.zz162@0 (not top.impl.usr.zz155@0) (not top.impl.usr.SP3c@0) (not top.impl.usr.zz1@0) (not top.impl.usr.zz4@0) (not (= top.impl.usr.mode@0 1)) (= top.impl.usr.zz3@0 (not (= top.impl.usr.mode@0 5))) (= top.impl.usr.zz0@0 (not (= top.impl.usr.mode@0 6))) (= top.usr.OK@0 (and (not (>= top.impl.usr.desiredSpeed@0 15.0)) (or (= top.impl.usr.mode@0 3) (= top.impl.usr.mode@0 4) (= top.impl.usr.mode@0 5) (= top.impl.usr.mode@0 6)))) (not (= top.impl.usr.zz161@0 1)) (ite top.impl.usr.zz3@0 (not (= top.impl.usr.zz5@0 (/ (- 1) 20))) (not (= top.impl.usr.zz5@0 0.0))) (ite top.impl.usr.zz0@0 (not (= top.impl.usr.zz2@0 (/ 1 20))) (not (= top.impl.usr.zz2@0 0.0))) (ite (ite (= top.impl.usr.mode@0 6) (not (>= top.impl.usr.zz2@0 0.0)) (and (= top.impl.usr.mode@0 5) (not (>= top.impl.usr.zz5@0 0.0)))) (not (= top.impl.usr.desiredSpeed@0 0.0)) (ite (ite (= top.impl.usr.mode@0 6) (not (>= (* (- 1.0) top.impl.usr.zz2@0) (- 100.0))) (and (= top.impl.usr.mode@0 5) (not (>= (* (- 1.0) top.impl.usr.zz5@0) (- 100.0))))) (not (= top.impl.usr.desiredSpeed@0 100.0)) (ite (= top.impl.usr.mode@0 6) (not (= top.impl.usr.desiredSpeed@0 top.impl.usr.zz2@0)) (ite (= top.impl.usr.mode@0 5) (not (= top.impl.usr.desiredSpeed@0 top.impl.usr.zz5@0)) (not (= top.impl.usr.desiredSpeed@0 0.0)))))) (and (or (not top.impl.usr.zz183@0) (not (= top.impl.usr.zz176@0 1))) (or top.impl.usr.zz183@0 (not (= top.impl.usr.zz176@0 0)))) (and (or top.impl.usr.zz178@0 (not (= top.impl.usr.zz170@0 0))) (or (not top.impl.usr.zz178@0) (not (= top.impl.usr.zz170@0 1)))))
```

The subsequently call to `simplify` on line 3211 returns a result that not strictly typed.  At the moment, this is expected behavior, since simplify is intended to rewrite a term to its internal representation in cvc5 (which is not strictly typed).  

It is worth considering making the result of `simplify` have the same policy as `get-qe`, that is, we eliminate subtyping from both for consistency.

**Comment by daniel-larraz** [comment]
You are right. I overlooked the call to `simplify`.
