### ISSUE TITLE
Last version isn't on PyPI, no source tarball on PyPI

### ISSUE THREAD

**Issue by yurivict** [cvc5/cvc5#9377]
No last version [here](https://pypi.org/project/cvc5/).

No source tarball [here](https://pypi.org/project/cvc5/#files).

**Comment by mpreiner** [comment]
Seems like there are some CI issues we have to fix to get this working again. Thanks for reporting!

**Comment by vrcamillo** [comment]
We fixed a pypi packaging issue and now cvc5 1.0.5 is available [here](https://pypi.org/project/cvc5/#history).

Thank you for your report!
