### ISSUE TITLE
How to start with C++ API?

### ISSUE THREAD

**Issue by jatingupta2000** [cvc5/cvc5#9385]
I am facing problem with the C++ API. I have installed the CVC5 as instructed in INSTALL.rst but at the end it is giving error as 

/usr/bin/ld: /tmp/cccpRDPj.o: in function `main':

first.cpp:(.text+0x27): undefined reference to `cvc5::Solver::Solver()'

/usr/bin/ld: first.cpp:(.text+0x53): undefined reference to `cvc5::Solver::getBooleanSort() const'

/usr/bin/ld: first.cpp:(.text+0x71): undefined reference to `cvc5::Solver::mkConst(cvc5::Sort const&, 

std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) const'

/usr/bin/ld: first.cpp:(.text+0x80): undefined reference to `cvc5::Sort::~Sort()'

/usr/bin/ld: first.cpp:(.text+0xa5): undefined reference to `cvc5::operator<<(std::ostream&, cvc5::Term const&)'

/usr/bin/ld: first.cpp:(.text+0xda): undefined reference to `cvc5::Solver::checkSatAssuming(cvc5::Term const&) const'

/usr/bin/ld: first.cpp:(.text+0xec): undefined reference to `cvc5::operator<<(std::ostream&, cvc5::Result const&)'

/usr/bin/ld: first.cpp:(.text+0x121): undefined reference to `cvc5::Term::~Term()'

/usr/bin/ld: first.cpp:(.text+0x12d): undefined reference to `cvc5::Solver::~Solver()'

/usr/bin/ld: first.cpp:(.text+0x15a): undefined reference to `cvc5::Sort::~Sort()'

/usr/bin/ld: first.cpp:(.text+0x19f): undefined reference to `cvc5::Term::~Term()'

/usr/bin/ld: first.cpp:(.text+0x1b4): undefined reference to `cvc5::Solver::~Solver()'

collect2: error: ld returned 1 exit status

Can anyony guide me to successfully execute this?

**Comment by martin-cs** [comment]
That looks like a link error.   Can you send the command line you used to link?  Also platform and configuration information would be useful.  It looks like you are running Linux and using GCC but I could be wrong.

**Comment by jatingupta2000** [comment]
Yes, Problem is resolved. Actually I am not using **-lcvc5** after C++ command before.

**Comment by martin-cs** [comment]
Glad to hear you got it sorted.
