### ISSUE TITLE
use of bv2nat leads to unprovable VCs

### ISSUE THREAD

**Issue by yannickmoy** [cvc5/cvc5#9415]
**Describe the bug**

bv2nat leads to unprovable VCs with cvc5.
For example, it does not prove that the result of bv2nat is greater or equal to zero.
What can we expect from the support of bv2nat in cvc5, now and in the future?

Unfortunately, we have to use conversions between int and bv theories sometimes in SPARK, for example when specifying numerical algorithms that can't be specified with the largest existing machine integers.

You can see that on the following SMT file, on which cvc5 does not return:

```
(set-logic AUFBVFPDTNIRA)
(set-info :smt-lib-version 2.6)

(declare-const bv (_ BitVec 32))
(assert (not (<= 0 (bv2nat bv))))

(check-sat)
```

**Command line arguments**: none
**cvc5 version/commit**: 1.0.3
**Operating system**: Linux

**Comment by ajreynol** [comment]
Thanks for the benchmark. Coincidentally, I sent a PR a few days ago that solves this quickly: https://github.com/cvc5/cvc5/pull/9409.  It should be merged soon.

Currently, our support for bv2nat is work-in-progress. When we updated CVC4 -> cvc5, we refactored our support for bv2nat significantly, as well as rewriting the BV solver from scratch. Thus there is still low hanging fruit to address performance-wise.

Moving forward, we plan to continue to improve our support for bv2nat/int2bv. Issues like this are helpful in driving this.

**Comment by rod-chapman** [comment]
Nice to see this becoming a popular topic ... BV problems seem to be like buses... you wait for ages, and then...

**Comment by yannickmoy** [comment]
Great news! thanks @ajreynol 
I'll keep creating issues then for other problems we have on nonlinear or mixed arithmetic VCs.

**Comment by yannickmoy** [comment]
@ajreynol will your PR also solve similar properties like monotonicity of bv2nat? e.g. the following VC:

```smt
(set-logic AUFBVFPDTNIRA)
(set-info :smt-lib-version 2.6)

(declare-const x (_ BitVec 32))
(declare-const y (_ BitVec 32))
(assert (bvule x y))
(assert (not (<= (bv2nat x) (bv2nat y))))

(check-sat)
```

**Comment by ajreynol** [comment]
Unfortunately no, not yet.  This can be added, it will likely require a lemma schema in the bv2nat subsolver.

**Comment by yannickmoy** [comment]
Is there something that I could read to know better how bv2nat is handled currently?
We are definitely interested in getting better support from cvc5 on bv2nat.
