### ISSUE TITLE
Function in C++ API

### ISSUE THREAD

**Issue by jatingupta2000** [cvc5/cvc5#9421]
Can anyone give an example to write function of Terms in C++ API to reuse the equation of terms?

I am trying to write below example
Term findOutput(Solver* slv, Term *k, Term *a, Term *b){
	Term Add = slv->mkTerm(ADD, {*a, *b});		// Add => (a + b)
	Term Minus = slv->mkTerm(SUB, {*a, *b});		// Minus => (a - b)
	Term cond = slv->mkTerm(EQUAL, {*k, slv->mkInteger(0)});		// cond => (k == 0)
	return slv->mkTerm(ITE, {cond.notTerm(), Add, Minus});
}

And giving this error
terminate called after throwing an instance of 'cvc5::CVC5ApiException'
  what():  expecting an arithmetic subterm
Aborted (core dumped)

**Comment by ajreynol** [comment]
Can you show what terms are being passed for k, a, b?

**Comment by jatingupta2000** [comment]
Solver slv;
Term a = slv.mkVar(Integer, "a");
Term b = slv.mkVar(Integer, "b");
Term k = slv.mkVar(Integer, "k");

Term f = findOutput(&slv, &k, &a, &b);

**Comment by ajreynol** [comment]
Were you able to resolve this issue?  I would need further context to see the entire code you are running.
