### ISSUE TITLE
Segmentation Fault when Synthesizing Multiple Functions Given One Large Constraint

### ISSUE THREAD

**Issue by ruchou** [cvc5/cvc5#9442]
Hi CVC5 team, We are working on synthesizing multiple functions with CVC5 given only one heavy constraint. If the constraint is relatively small, CVC5 synthesis succeeds. However, we found that if the constraint is large and complex beyond a certain point, CVC5 crashes when trying to synthesize exactly the same function signature. From what we can see, most crashes have to do with memory corruption.

After trying several queries for CVC5, we found most error messages for this issue to be as follows:

```shell
cvc5 suffered a segfault.
Offending address is 0x0
Looks like a NULL pointer was dereferenced.
zsh: segmentation fault
```

So we investigated these errors with the `-o sygus' option and found that CVC5 crashes when enumerating all terms and solution candidates. Our current suspicion is that there is a memory management issue in CVC5 that is causing this problem. We have attached an example of a relatively small SyGuS file that causes CVC5 to crash. This SyGuS file was generated by a higher-level synthesis tool we have developed. It is the smallest such file that we were able to construct that exhibited the crash.

**SyGuS File With Minimum Constraint Causing the Crash**

[axiom.sy](https://gist.github.com/ruchou/d938408c57f292d3b8321632dc903f77)

**cvc5 version**: 1.0.3 compiled with GCC version Apple LLVM 14.0.0 (clang-1400.0.29.202)

**Operating system**: macOS 13.1 (22C65)

We are currently encountering this crash on a significant number of the SyGuS files that are generated by our higher-level tool, so it is having a sizeable impact on our ability to use CVC5 for synthesis. Can you please take a look? If you need us to provide further information, don't hesitate to let us know. Thank you!

**Comment by ajreynol** [comment]
Thanks a lot for the report, indeed the issue was related to memory (reference counting).  

This is fixed in my latest PR.  The attached benchmark now solves in ~26 seconds on my machine.
