### ISSUE TITLE
Fails to link with libkissat.so

### ISSUE THREAD

**Issue by yurivict** [cvc5/cvc5#9483]
**Describe the bug**
I have the /usr/local/lib/libkissat.so installed, and no /usr/local/lib/libkissat.a
With ```USE_KISSAT=ON``` configure finds Kissat:
```
Kissat                    : true (system)
```
But binaries aren't linked with ```libkissat.so```.

**cvc5 version/commit**: 1.0.4
**Operating system**: FreeBSD 13.1

**Comment by vrcamillo** [comment]
Thank you for the report!

I installed a FreeBSD virtual machine to try to reproduce this issue. 

When the static library `libkissat.a` is not found, the executable is not linked against. but with `libcvc5.so`, which itself is linked against `libkissat.so`. You can list the dependencies of `libcvc5.so` by running the command `readelf -d <your build directory>/src/libcvc5.so | grep "NEEDED"`. On my machine it is the first dependency listed:

```NEEDED Shared library: [/usr/local/lib/libkissat.so]```

Would you please confirm if that dependency is correctly linked to libcvc5.so on your machine, @yurivict?

**Comment by vrcamillo** [comment]
I assume this is no longer a problem. Please let us know if you encounter any problems.
