### ISSUE TITLE
Fails to compile with cocoalib

### ISSUE THREAD

**Issue by yurivict** [cvc5/cvc5#9484]
**Describe the bug**
cocoalib-0.99800 is installed (see https://cocoa.dima.unige.it/cocoa/cocoalib/). cvc5-1.0.4 fails to build with ```USE_COCOA=ON```:
```
In file included from /usr/ports/math/cvc5/work/cvc5-cvc5-1.0.4/src/theory/ff/roots.cpp:24:
In file included from /usr/ports/math/cvc5/work/cvc5-cvc5-1.0.4/src/./theory/ff/roots.h:24:
In file included from /usr/local/include/CoCoA/RingFp.H:22:
In file included from /usr/local/include/CoCoA/GlobalManager.H:23:
In file included from /usr/local/include/CoCoA/random.H:22:
In file included from /usr/local/include/CoCoA/MachineInt.H:33:
/usr/local/include/CoCoA/ULong2Long.H:31:3: error: expected unqualified-id
  "ERROR: -DCoCoA_ULONG2LONG=n setting missing";
  ^
In file included from /usr/ports/math/cvc5/work/cvc5-cvc5-1.0.4/src/theory/ff/roots.cpp:24:
In file included from /usr/ports/math/cvc5/work/cvc5-cvc5-1.0.4/src/./theory/ff/roots.h:24:
In file included from /usr/local/include/CoCoA/RingFp.H:22:
In file included from /usr/local/include/CoCoA/GlobalManager.H:23:
In file included from /usr/local/include/CoCoA/random.H:22:
In file included from /usr/local/include/CoCoA/MachineInt.H:34:
/usr/local/include/CoCoA/ULongLong2LongLong.H:31:3: error: expected unqualified-id
  "ERROR: -DCoCoA_ULONGLONG2LONGLONG=n setting missing";
  ^
2 errors generated.
```

**cvc5 version/commit**: 1.0.4
**Operating system**: FreeBSD 13.1

clang-14

**Comment by vrcamillo** [comment]
I could not reproduce it in Ubuntu 22.04 with cvc5 1.0.4 and clang-14. Going to build a FreeBSD virtual machine to test it. 

@yurivict Would you please provide the ./configure command you used?

**Comment by yurivict** [comment]
It uses cmake:

cmake -DANTLR_BINARY=/usr/ports/math/cvc5/work/antlr3  -DFREEBSD_DISTDIR=/usr/ports/distfiles  -DPython_EXECUTABLE:STRING=/usr/local/bin/python3.9 -DUSE_CLN:BOOL=false -DUSE_COCOA:BOOL=true -DUSE_CRYPTOMINISAT:BOOL=true -DUSE_EDITLINE:BOOL=true -DBUILD_BINDINGS_JAVA:BOOL=true -DJAVA_INCLUDE_PATH:PATH=/usr/local/openjdk8/include  -DJAVA_AWT_LIBRARY:PATH=/usr/local/openjdk8/jre/lib/amd64/libjawt.so  -DJAVA_JVM_LIBRARY:PATH=/usr/local/openjdk8/jre/lib//libjava.so -DUSE_KISSAT:BOOL=false -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Production"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_BINDINGS_PYTHON:BOOL=OFF -DUSE_PYTHON3:BOOL=OFF -GNinja -DPython_ADDITIONAL_VERSIONS=3.9 -DBOOST_PYTHON_SUFFIX:STRING=39

**Comment by vrcamillo** [comment]
I assume this is no longer a problem. Please let us know if you encounter any further issues.

**Comment by yurivict** [comment]
@vrcamillo 
Sorry for missing your messages. The problem still exists.

We have cocoalib-0.99800 installed. It installs the file /usr/local/include/CoCoA/PREPROCESSOR_DEFNS.H but it doesn't contain the string CoCoA_ULONG2LONG:
```
#undef COCOA_WITH_BOOST
#undef COCOA_WITH_FROBBY
#undef COCOA_WITH_GFAN
#undef COCOA_WITH_GSL
#undef COCOA_WITH_NORMALIZ
```
