### ISSUE TITLE
CVC5 1.0.4 (macOS) crash in Cadical

### ISSUE THREAD

**Issue by rod-chapman** [cvc5/cvc5#9492]
CVC5 1.0.4 crashes on the attached input, somewhere in Cadical. Discovered and reproducible on macOS/ARM64.
```
rodchap@f4d4889dcf6d gnatprove % cvc5 --version
This is cvc5 version 1.0.4 [git tag 1.0.4 branch HEAD]
compiled with GCC version Apple LLVM 14.0.0 (clang-1400.0.29.202)
on Feb  3 2023 11:59:35

rodchap@f4d4889dcf6d gnatprove % cvc5 --decision=internal --rlimit=8000000 --debug sparknacl-secretbox.adb_198_34_precondition2_1.smt2
Fatal failure within virtual cvc5::internal::prop::SatValue cvc5::internal::prop::CadicalSolver::modelValue(cvc5::internal::prop::SatLiteral) at /Users/rodchap/Desktop/rod/tools/src/cvc5/src/prop/cadical.cpp:196
Check failure

 d_inSatMode

zsh: abort      cvc5 --decision=internal --rlimit=800000 --debug 
```
[sparknacl-secretbox.adb_198_34_precondition2_1.smt2.gz](https://github.com/cvc5/cvc5/files/10687115/sparknacl-secretbox.adb_198_34_precondition2_1.smt2.gz)

**Comment by rod-chapman** [comment]
A clue... if I remove "--decision=internal" from the command-line, then it terminates normally with "unknown" and no crash...

**Comment by mpreiner** [comment]
Thanks @rod-chapman for the report, we'll try to reproduce.

**Comment by rod-chapman** [comment]
For what it's worth, I have another SMT file that generates this crash... attached.
This is CVC5 1.0.4 on macOS - note that --rlimit=1000000 AND --decision=internal are required to reproduce the crash:
```
rodchap@f4d4889dcf6d gnatprove % cvc5 --rlimit=800000 sparknacl.adb_616_21_overflow_check_1.smt2
unknown
rodchap@f4d4889dcf6d gnatprove % cvc5 --rlimit=1000000 sparknacl.adb_616_21_overflow_check_1.smt2
unknown
rodchap@f4d4889dcf6d gnatprove % cvc5 --rlimit=1000000 --decision=internal sparknacl.adb_616_21_overflow_check_1.smt2
Fatal failure within virtual cvc5::internal::prop::SatValue cvc5::internal::prop::CadicalSolver::modelValue(cvc5::internal::prop::SatLiteral) at /Users/rodchap/Desktop/rod/tools/src/cvc5/src/prop/cadical.cpp:196
Check failure

 d_inSatMode

zsh: abort      cvc5 --rlimit=1000000 --decision=internal 
```
I have also been able to reproduce this on Amazon Linux 2, also using CVC5 1.0.4. This generates a slightly different error message:
```
dev-dsk-rodchap-1c-27e71892 % cvc5 --rlimit=800000 sparknacl.adb_616_21_overflow_check_1.smt2 
unknown

(23-02-14 9:47:42) <0> [~]  
dev-dsk-rodchap-1c-27e71892 % cvc5 --rlimit=1000000 sparknacl.adb_616_21_overflow_check_1.smt2
unknown

(23-02-14 9:47:52) <0> [~]  
dev-dsk-rodchap-1c-27e71892 % cvc5 --rlimit=1000000 --decision=internal sparknacl.adb_616_21_overflow_check_1.smt2
cadical: fatal error: invalid API usage of 'int CaDiCaL::Solver::val(int)' in '../src/solver.cpp': can only get value in satisfied state
zsh: abort      cvc5 --rlimit=1000000 --decision=internal 

(23-02-14 9:48:06) <134> [~]  
```
[sparknacl.adb_616_21_overflow_check_1.smt2.gz](https://github.com/cvc5/cvc5/files/10731065/sparknacl.adb_616_21_overflow_check_1.smt2.gz)

**Comment by rod-chapman** [comment]
Here's another example that crashes, even without the use of --decision=internal.  CVC4 says "unknown", while z3 says "unsat" in very little time...
```
rodchap@f4d4889dcf6d gnatprove % cvc4 --rlimit=45000 sparknacl.adb_264_22_assert_1.smt2 
unknown
rodchap@f4d4889dcf6d gnatprove % cvc5 --rlimit=45000 sparknacl.adb_264_22_assert_1.smt2
Fatal failure within virtual cvc5::internal::prop::SatValue cvc5::internal::prop::CadicalSolver::modelValue(cvc5::internal::prop::SatLiteral) at /Users/rodchap/Desktop/rod/tools/src/cvc5/src/prop/cadical.cpp:196
Check failure

 d_inSatMode

zsh: abort      cvc5 --rlimit=45000 sparknacl.adb_264_22_assert_1.smt2
rodchap@f4d4889dcf6d gnatprove % z3 sparknacl.adb_264_22_assert_1.smt2
unsat
```
[sparknacl.adb_264_22_assert_1.smt2.gz](https://github.com/cvc5/cvc5/files/10734394/sparknacl.adb_264_22_assert_1.smt2.gz)

**Comment by mpreiner** [comment]
Thanks @rod-chapman! I can now reproduce the bug on a mac.

**Comment by rod-chapman** [comment]
I re-build from commit e048e6be8, but I still see the crash on one of those examples:
```
rodchap@f4d4889dcf6d t % cvc5 --version
This is cvc5 version 1.0.5-dev.28.e048e6be8 [git e048e6be8 on branch main]

```
then
```
rodchap@f4d4889dcf6d t % cvc5 --rlimit=1000000 --decision=internal sparknacl.adb_616_21_overflow_check_1.smt2
Fatal failure within virtual cvc5::internal::prop::SatValue cvc5::internal::prop::CadicalSolver::modelValue(cvc5::internal::prop::SatLiteral) at /Users/rodchap/Desktop/rod/tools/src/cvc5/src/prop/cadical.cpp:196
Check failure

 d_inSatMode

zsh: abort      cvc5 --rlimit=1000000 --decision=internal 
```

**Comment by rod-chapman** [comment]
...and the other one...
```
rodchap@f4d4889dcf6d t % cvc5 --rlimit=50000 sparknacl.adb_264_22_assert_1.smt2
Fatal failure within virtual cvc5::internal::prop::SatValue cvc5::internal::prop::CadicalSolver::modelValue(cvc5::internal::prop::SatLiteral) at /Users/rodchap/Desktop/rod/tools/src/cvc5/src/prop/cadical.cpp:196
Check failure

 d_inSatMode

zsh: abort      cvc5 --rlimit=50000 sparknacl.adb_264_22_assert_1.smt2
```

**Comment by mpreiner** [comment]
@rod-chapman There are more resource checks missing. I've opened another PR to fix the remaining issues you reported. Can you maybe apply this patch (https://patch-diff.githubusercontent.com/raw/cvc5/cvc5/pull/9513.diff) on top of the main branch and check if this indeed fixes all the issues? I was now able to reproduce all the issues on Linux with different resource limits and this issue doesn't get triggered anymore on my machine.

**Comment by rod-chapman** [comment]
I patched, rebuilt and tested... all seems well now on those test cases. I hope you might add those test cases to your regression test set to guard against reoccurrence of this.

**Comment by mpreiner** [comment]
I can try adding them, although it will be hard to find a rlimit for each benchmark that'd trigger the behavior on all the different platforms/os we use.

**Comment by rod-chapman** [comment]
I thought the whole point of --rlimit=N --tlimit=0 was to get predictable behaviour on all platforms?

**Comment by martin-cs** [comment]
/pedant on/

The purpose of the reproducible resource limit in the SMT-LIB standard (which `--rlimit` is an implementation of) was to give a deterministic resource limit for a particular solver/input pair.  There is no requirement for this to be stable, cross-platform, etc.  The only requirement is that it should be monotonic in terms of what is solved.

Now, the sane and good ways of implementing it are pretty stable w.r.t. solver and problem change, cross platform, well correlated with elapsed time, etc.  but this is not required behaviour.

/pedant off/

**Comment by mpreiner** [comment]
You can get different solver behavior on different platforms, which is mostly due  to different system library versions that e.g. may impact the order of elements in unordered containers. E.g. for the issues you reported here, I was able to reproduce them on a Apple Silicon mac with the same resource limits. However, on a Linux machine I had to find out which resource limit triggers this behavior for each file since the given resource limit did not trigger it.
 The resource limit provides a deterministic way to terminate the solver when a given resource limit is hit. This will always be the same termination point for a solver/input pair on a given machine for consecutive executions. In contrast, the time limit will terminate the solver whenever the time limit is reached independent from the state the solver is currently in.

**Comment by rod-chapman** [comment]
Yuk... it's very common indeed for industrial users to have different platforms on desktop and server.  e.g. Windows on Desktop, Linux on CI Server etc.  In that environment, I simply have to have reproducible behaviour.

**Comment by mpreiner** [comment]
The solver will terminate in a deterministic way after the resource limit is hit, no matter what platform. However, it is not guaranteed that the solver will always terminate in the same state. The question is what is expected of a predictable resource limit? To have the solver terminate always in the same state on all platforms?

**Comment by barrettcw** [comment]
Just a quick follow-up on this.  Indeed, it would be fantastic to have a tool that is deterministic across platforms, but this is *extremely* difficult to ensure in practice.  Even if we are highly disciplined about our own code, we have dependencies on standard libraries, multiple precision arithmetic packages, and several other things.  It is great as an aspirational long-term goal, but for now, determinism on a single platform is the goal of the resource limit.

**Comment by rod-chapman** [comment]
Noted, but I think this will be an FAQ for ever more... "multi platform" is the normal setup for industrial users like SPARK customers - it's typically Windows on the engineers' desktops and "something else" on the CI server. It really hurts when a developers spends their hard-earned time and effort to get a bunch of proofs to work on desktop, then they commit the code, only to get a rude email from the CI server saying their code is broken...

**Comment by barrettcw** [comment]
Yes, understood.  Fortunately, platform-dependent behavior is rare and we work to eliminate it as much as possible, but guaranteeing platform independence is almost impossible.  The fine-grained nature of the resource limit unfortunately makes it one of these rare cases.
