### ISSUE TITLE
Seg fault in AletheProofPrinter

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9515]
**Describe the bug**

On the following  file, cvc5 suffers a segfault when trying to produce a proof  in the Alethe format:
```
(set-logic QF_UF)
(declare-sort u 0)
(declare-fun $2 () Bool)
(declare-fun y () u)
(declare-fun $ () u)
(assert (= y (ite $2 y $)))
(assert (not $2))
(assert (not (= $ y)))
(check-sat)
```

This happens with a recent build: commit 6a0abb70032db7bd747724477ca63372e7c801eb.

To reproduce:
```
cvc5 --dump-proofs --proof-format-mode=alethe --dag-thresh=0 --simplification=none test.smt2
```
This should produce:
```
cvc5 suffered a segfault.
Offending address is 0x2f
Looks like a NULL pointer was dereferenced.
Segmentation fault
```

**Comment by HanielB** [comment]
Both this and #9516 have been fixed in proof-new, as they are due to the same issue of dealing with fresh symbols. I'll do a PR into main that should fix them. Keeping this open until then.
