### ISSUE TITLE
Alethe proof contains undefined symbols

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9516]
**Describe the bug**

On this example. cvc5 generates an invalid alethe proof. The proof contains an undeclared identifier `termITE_1`
```
(set-logic QF_UF)
(declare-sort u 0)
(declare-fun $2 () Bool)
(declare-fun $ () u)
(declare-fun s () u)
(assert (not (= s (ite $2 s $))))
(assert (not (= $ (ite $2 s $))))
(check-sat)
```

This is with cvc5 commit 6a0abb70032db7bd747724477ca63372e7c801eb. 

To reproduce:
```
> cvc5 --dump-proofs --proof-format-mode=alethe --dag-thresh=0 --proof-granularity=theory-rewrite test.smt2
```
Then running carcara on the proof gives an error:
```
> carcara check test.prf test.smt2
[ERROR] parser error: identifier 'termITE_1' is not defined (on line 3, column 33)
invalid
```
Playing with carcara command-line options makes no difference,

**Comment by HanielB** [comment]
Closed via #9530
