### ISSUE TITLE
At-most k / At-least k in cvc5

### ISSUE THREAD

**Issue by Dinple** [cvc5/cvc5#9527]
Hi,

Coming from Z3 solver, is there any similar syntax to `(_ at-most k)` or `(_ at-least k)` in cvc5?

I could not find any and cvc5 seems not supporting this function. If not, what would be the best practice in cvc5 to get around this?

Thanks in advance!

**Comment by ajreynol** [comment]
I assume this means `((_ at-most k) C1 ... Cn)` is true if at most `k` of formulas `C1 ... Cn` are true?

If so, I think the easiest way would be to use a linear arithmetic inequality:
`(<= (+ (ite C1 1 0) ... (ite Cn 1 0)) k)`

Let me know if my understanding is correct and if this works.

**Comment by Dinple** [comment]
this is really helpful! thanks
