### ISSUE TITLE
Pythonic API: Cannot print: Kind.CONST_INTEGER

### ISSUE THREAD

**Issue by ov7a** [cvc5/cvc5#9549]
**Describe the bug**
I'm using pythonic API. When I try to print any `ArithRef` object, I get an error:
```
...
  File "/usr/local/lib/python3.10/dist-packages/cvc5/pythonic/cvc5_pythonic_printer.py", line 899, in pp_prefix
    return seq1(self.pp_name(a), r)
  File "/usr/local/lib/python3.10/dist-packages/cvc5/pythonic/cvc5_pythonic_printer.py", line 690, in pp_name
    return to_format(_op_name(a))
  File "/usr/local/lib/python3.10/dist-packages/cvc5/pythonic/cvc5_pythonic_printer.py", line 372, in _op_name
    raise Exception("Cannot print: " + str(k))
Exception: Cannot print: Kind.CONST_INTEGER
```
This happens even in the simplest situations:
```python3
from cvc5.pythonic import *
a = Int('a')
solve(a == 1)
```
The issue and workaround for it was described before [here](https://hackmd.io/@s-fish/H1nqUvx6j) (I'm not the OP).
The author also mentions another problem with printing the model:

> This may display the integer 1 like 1() instead. If you figure out how to fix this I would be delighted to hear about it.

**cvc5 version/commit**: 1.0.4 [git tag 1.0.4 branch HEAD] - binary distribution from downloads [page](https://cvc5.github.io/downloads.html)
**Operating system**: Ubuntu 22.04.2 LTS Linux 5.15.0-60-generic
**Python version**: 3.10.6
**Python-cvc5 version**: 1.0.1

**Comment by yoni206** [comment]
Hi and thanks for raising this issue.
The pythonic API's repo has an [identical issue](https://github.com/cvc5/cvc5_pythonic_api/issues/81) which will be solved once [this PR](https://github.com/cvc5/cvc5_pythonic_api/pull/82/files) is merged.

**Comment by yoni206** [comment]
solved by this PR:
https://github.com/cvc5/cvc5_pythonic_api/pull/82/files
