### ISSUE TITLE
Script fix-install-header.sh does not work properly on MacOS

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9553]
**Describe the bug**

The script `fix-install-header.sh` uses the 'sed' options `-i'' `, which do not work on Mac OS.
On Linux, this modifies `*.h` files in place. 

On MacOS, the syntax is `-i <extension>`  so this command creates a backup with suffix 'h-e' for every '.h' file.
Because the `find` applies sed to every file in the install `include` directory, the whole thing results in this:
```
> ls /usr/local/include/cvc5
cvc5.h                  cvc5_export.h           cvc5_kind.h             cvc5_sort_kind.h        cvc5_types.h
cvc5.h-e                cvc5_export.h-e         cvc5_kind.h-e           cvc5_sort_kind.h-e      cvc5_types.h-e
cvc5.h-e-e              cvc5_export.h-e-e       cvc5_kind.h-e-e         cvc5_sort_kind.h-e-e    cvc5_types.h-e-e
```

Things get worse if you install a new version as the sed command will create `.h-e-e-e-e-e` files and more every time.

**Comment by mpreiner** [comment]
Thanks for reporting @BrunoDutertre! We are in the process of restructuring the public headers, which will make this script obsolete.
