### ISSUE TITLE
Potential performance issue on a small QF_NRA formula

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#9565]
Hi,
cvc5 will hang on this formula without `--force-logic="QF_NRA"`. 
I'm unsure if this behavior is expected.

```
$ cat small.smt2
(set-logic ALL)
(declare-fun e () Real)
(assert (= (* e e) (+ 1.0 1.0)))
(check-sat)
$ time ./cvc5-2023-03-12-x86_64-Linux-production --force-logic="QF_NRA" small.smt2
sat

real	0m0.016s
user	0m0.011s
sys	0m0.006s
$ timeout 10s ./cvc5-2023-03-12-x86_64-Linux-production small.smt2
cvc5 interrupted by SIGTERM.
```

**Comment by mpreiner** [comment]
This is expected behavior since cvc5 will configure and optimize options based on the specified logic. In general, for cvc5 it is recommended to narrow the logic as much as possible.

**Comment by merlinsun** [comment]
Hello there,
I was wondering if you could spare a moment to review the following issue. It appears to be a regression issue, as previous versions (e.g., [cvc5-0.0.2](https://github.com/cvc5/cvc5/commit/5ca9c2b5ec7e8d503f4ff122ccb2a4a76410c02c)) were able to solve the instance quickly.
Thank you kindly for your attention and time.
Best regards,
```
$ timeout 120s cvc5-2023-04-09-x86_64-Linux-production small.smt2
cvc5 interrupted by SIGTERM.
$ time ./cvc5-Linux-0.0.2 small.smt2
sat

real	0m0.018s
user	0m0.009s
sys	0m0.009s
$ cat small.smt2
(set-logic ALL)
(declare-fun e () Real)
(assert (= (* e e) (+ 1.0 1.0)))
(check-sat)
```

**Comment by barrettcw** [comment]
Please see our previous response.
