### ISSUE TITLE
Weird INTERFACE_LINK_LIBRARY in cvc5Targets.cmake

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9570]
**Describe the bug**

When building cvc5 statically, the install process will create a `cvc5Targets.cmake`  that looks buggy.

When I try to build another package that uses `cmake` and `find_package(cvc5 ..)`, I get this link-time error:
```
ld: library not found for -lGMP
```
This is caused by the `INTERFACE_LINK_LIBRARIES`  in  `cvc5Targets.cmake`:
```
set_target_properties(cvc5::cvc5 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GMP;\$<LINK_ONLY:CaDiCaL>;Polyxx;\$<LINK_ONLY:SymFPU>"
)
```
This happens on both Linux and MacOS and with two different versions of cmake.

Here's more detail:

1) Build & install cvc5:
```
cd cvc5
./configure --auto-download --static --no-static-binary
cd build
make
sudo make install
```

2) Try to build `murxla` and  link with `cvc5`
```
cd murxla
mkdir build
cmake ..
cd build
make
```
The `cmake` command finds `cvc5` but the last step fails.  `make VERBOSE=1` shows that the link command is wrong.

**Comment by vrcamillo** [comment]
I believe this might be because cmake is not differentiating between the name of the library and the name of the package in `target_link_libraries`. `GMP` should be lowercase. I am going to look into this.
