### ISSUE TITLE
Question about separation logic

### ISSUE THREAD

**Issue by FrogOfJuly** [cvc5/cvc5#9571]
I apologize in advance if I am asking this question in the wrong place. In this case, feel encouraged to point out where this question should be asked.

I am new to CVC5 and separation logic, but I am slowly learning both of them. I did some simple queries and their results are very confusing to me. I asked the same [question](https://cs.stackexchange.com/questions/157764/what-is-the-difference-in-heap-configurations-separation-logic-with-cvc5-smt-so) on cs.stackexchange, but had no answer.

I will repeat my question here:

## First query

```
(set-logic QF_ALL)
(set-info :smt-lib-version 2.6)

(set-option :produce-models true)

; Heap declaration

(declare-heap (Int Int))

(declare-const v Int)

(assert (sep 
    (pto 1 v)
    (pto 2 v)
))

(check-sat)
(get-model)
```
### Result

```
sat
(
(define-fun v () Int 0)
)
(heap
(sep (pto 2 v) (pto 1 v))
(= (as sep.nil Int) 0)
)
```

## Second query

```
(set-logic QF_ALL)
(set-info :smt-lib-version 2.6)

(set-option :produce-models true)

; Heap declaration

(declare-heap (Int Int))

(declare-const v Int)

(assert (not (sep 
    (pto 1 v)
    (pto 2 v)
)))

(check-sat)
(get-model)
```

### Result

```
sat
(
(define-fun v () Int 0)
)
(heap
(sep (pto 2 0) (pto 1 0))
(= (as sep.nil Int) 0)
)
```

Why do both of these queries give SAT results? 

What is the difference between `pto 1 v` and `pto 1 0` while `v` equals zero?

What should I read to be able to understand these things myself?

**Comment by ajreynol** [comment]
Thanks a lot for pointing this out.  The models for the heap were not being generated correctly, both in that `v` was not specified in the first query, and that `0` was the incorrect value to point-to in the second query.  After my latest PR, cvc5 now gives the correct models for the heap:

Query 1:
```
sat
(
(define-fun v () Int 0)
)
(heap
(sep (pto 2 0) (pto 1 0))
(= (as sep.nil Int) 0)
)
```
Query 2:
```
sat
(
(define-fun v () Int 0)
)
(heap
(sep (pto 2 1) (pto 1 1))
(= (as sep.nil Int) 0)
)
```

**Comment by FrogOfJuly** [comment]
Thank you very much for the fix! Should I close the issue or wait for the merge of #9574 first?

**Comment by ajreynol** [comment]
No problem.  Let's wait until the merge to close.
Cheers,
Andy

**Comment by FrogOfJuly** [comment]
There is another question I wanted to ask. Why `(sep (pto 2 1) (pto 1 1 )` is a valid heap, despite `2` and `1` pointing to the same value? One can't separate the heap in two heaplets, because the `1` is the same for both pointers.
