### ISSUE TITLE
Meaning of get-abduct

### ISSUE THREAD

**Issue by LeventErkok** [cvc5/cvc5#9598]
I'm playing around with `get-abduct`. My understanding is that it's supposed to produce a predicate that is consistent with the assertions present, but contradicts when the given conjecture is added as well. So, I tried:

```
(set-logic QF_LIA)
(set-option :produce-abducts true)
(declare-fun x () Int)
(declare-fun y () Int)

(assert (>= x 0))
(get-abduct A (>= (+ x y) 2))
```

This prints:

```
(define-fun A () Bool (= y 2))
```

i.e., `y == 2` is claimed to be an abduct. Indeed, `x >= 0` and `y == 2` is consistent, but if I further conjunct with `x + y >= 2` (i.e., the conjecture), what we have is still satisfiable. That tells me `y == 2` isn't really an abduct. Am I reading this incorrectly?

**Comment by ajreynol** [comment]
Conceptually, `get-abduct` here is asking "what do I need to add to my assertions that would imply `(>= (+ x y) 2)`?"

Thus, the goal is implicitly negated in a satisfiability query, which is unsatisfiable.

**Comment by LeventErkok** [comment]
Ah thanks.. So, what's UNSAT is the conjunction of the existing assertions, the generated abduct, and the NEGATION of the conjecture. I missed that last part. Thanks!
