### ISSUE TITLE
SIGSEGV on array term simplification over a nested recursive datatype

### ISSUE THREAD

**Issue by meng-xu-cs** [cvc5/cvc5#9658]
**Describe the bug**
Received a SIGSEGV when trying to simplify a term of an array sort
with both index and value being the same nested recursive datatype.

Conceptual reproduction
- Define a nested recursive data type
  ```rust
  datatype A {
    v1,
    v2,
    v3 (array [A -> A]
  }
  ```
- Create two new terms:
  ```rust
  term_v1 = A::v1();
  term_v2 = A::v2();
  ```
- Create a constant array:
  ```rust
  term_array = const array [A -> A] with default term_v1
  ```
- Update this array with a `Store` operation
   ```rust
   term_updated = store(term_array, term_v2, term_v2);
   ```
- Simplify the new term `term_updated` --> **This will trigger a `SIGSEGV`**

Here is a test case in C++ for the problem

```cpp
#include <cvc5/cvc5.h>

int main() {
  cvc5::Solver solver;

  // allow recursive datatype
  solver.setOption("dt-cyclic", "true");
  solver.setOption("dt-nested-rec", "true");

  // the recursive datatype declaration:
  // datatype A {
  //   v1,
  //   v2,
  //   v3 { value: array[A -> A] },
  // }
  auto sort_placeholder = solver.mkUnresolvedDatatypeSort("A", 0);
  auto decl = solver.mkDatatypeDecl("A");
  auto v1 = solver.mkDatatypeConstructorDecl("v1");
  decl.addConstructor(v1);
  auto v2 = solver.mkDatatypeConstructorDecl("v2");
  decl.addConstructor(v2);
#ifndef IGNORE_NESTED
  auto v3 = solver.mkDatatypeConstructorDecl("v3");
  v3.addSelector("value",
                 solver.mkArraySort(sort_placeholder, sort_placeholder));
  decl.addConstructor(v3);
#endif
  auto sort_a = solver.mkDatatypeSort(decl);

  // create two dummy terms, both of sort A, with v1 and v2 variants
  auto v1_ctor = sort_a.getDatatype().getConstructor("v1").getTerm();
  auto term_v1 = solver.mkTerm(cvc5::APPLY_CONSTRUCTOR, {v1_ctor});
  auto v2_ctor = sort_a.getDatatype().getConstructor("v2").getTerm();
  auto term_v2 = solver.mkTerm(cvc5::APPLY_CONSTRUCTOR, {v2_ctor});

  // create the array term: (constant array)
  auto sort_array_of_a_to_a = solver.mkArraySort(sort_a, sort_a);
  auto term_array = solver.mkConstArray(sort_array_of_a_to_a, term_v1);

  // update the array with a store
  auto term_a_array_updated =
      solver.mkTerm(cvc5::STORE, {term_array, term_v2, term_v2});

  // SIMPLIFICATION TRIGGERS A PANIC HERE!
  solver.simplify(term_a_array_updated);
}
```

**Command line arguments**: N/A, program constructed via C++ API  
**cvc5 version/commit**: d87874506a956c1d9f97233fff38ee25945e32d2 (`main` when this issue is filed)
**Operating system**: Ubuntu 22.04.2 LTS, MacOS 13.2

**`configure.sh` options**  
```
./configure.sh debug --ninja --auto-download
```

**`configure.sh` output**  
Paste the output of `configure.sh` here.

**Comment by meng-xu-cs** [comment]
@ajreynol @yoni206 I know this issue might not be on the critical path but just in case you have taken a look, any updates and estimation on how complex it is to fix it?

**Comment by yoni206** [comment]
Hi @meng-xu-cs , thanks for the issue and the question. We are now looking into this, and hopefully will have updates toon.

**Comment by yoni206** [comment]
Hi @meng-xu-cs ,

Looking more closely at this benchmark, we see a problem with having these datatypes inside a (possibly infinite) array. Is it possible for you to use `sequences` of `A` instead of an array of `A`s? 

Roughly speaking, the issue is that the type `A` contains all arrays from `A` to `A`, which means that $|A|\geq |A\rightarrow A|\geq 2^{|A|}$, which is impossible.
If you use finite containers, like sequences, then this problem does not occur, because then `A` includes all finite sequences of `A`-elements, which is possible whenever `A` is infinite.

Meanwhile, I am also including here an SMT-LIB version of your benchmark, to help us identify such problems better:

```
(set-logic ALL)
(set-option :dt-nested-rec true)
(declare-datatypes ((A 0)) (((v1) (v2) (v3 (value (Array A A)) ) ) ))
(define-fun term_array () (Array A A) ((as const (Array A A)) v1))
(define-fun term_a_array_updated () (Array A A) (store term_array v2 v2))
(define-fun assertion () Bool (= term_a_array_updated term_array))
(assert assertion)
(check-sat)
```

@barrettcw @ajreynol FYI
