### ISSUE TITLE
CVC5 Pythonic API SIGSEGV on declaring datatype

### ISSUE THREAD

**Issue by Eladkay** [cvc5/cvc5#9671]
**Describe the bug**
I performed the following steps:
```Python
from cvc5.pythonic import *
datatype = Datatype("empty")
datatype.declare("mk_A")
created = datatype.create()
```
After this, Python crashed with SIGSEGV. Crash report: https://pastebin.com/FZx2N7t9

*Note*: If the bug is triggered with an SMT2 input file please minimize it with [ddsmt](https://github.com/ddsmt/ddSMT).

**Command line arguments**: N/A
**cvc5 version/commit**: d284ecaaee41e38467874c7a9cf5bdf764869f94 (latest main at time of submission)
**Operating system**: macOS Ventura 13.1 on M2 MacBook Pro

**`configure.sh` options**  
N/A?

**`configure.sh` output**  
N/A?

I built and installed the Pythonic CVC5 API by using the instructions here: https://cvc5.github.io/docs-ci/docs-main/api/python/python.html#installation-arm64-variants-of-linux-and-macos

Thank you!

**Comment by yoni206** [comment]
Thanks for opening this issue -- we are looking into it.

**Comment by yoni206** [comment]
Hi @Eladkay ,
Sorry for the late reply.

I am unable to reproduce the problem, neither on linux nor on macOS (I tried on an M1 machine). I have tried both current `main` and your mentioned commit, but in both cases it works.

Can you please try to reproduce it yourself, using current `main`? If you get the same problem, can you respond with the exact output that you are getting (I don't see this in the crash report).

**Comment by alexandernutz** [comment]
Hi all,

@mpreiner pointed me to this thread, since I'm also seeing segfaults on CVC5 on an M2 Pro machine.

I'm attaching an smt file (only quite partially delta-debugged so far, sorry.. -- I'm new to ddsmt; if I can find / make a better file I'll post it).

The current arm64 release (https://github.com/cvc5/cvc5/releases/download/cvc5-1.0.5/cvc5-macOS-arm64) gives this output on my machine:

```                                                                                                              
cvc5 suffered a segfault.
Offending address is 0x600020000000
[1]    37298 segmentation fault  ~/Downloads/cvc5-macOS-arm64 dd.smt2
```

Note that
 - when I've asked colleagues at Certora with an M1-generation processor to reproduce this problem, they didn't observe the crash but cvc5 ran normally; so I suspect it's M2 (Pro)-specific
 - I haven't had problems when running the other MacOs binaries (via rosetta)

[dd.smt2.zip](https://github.com/cvc5/cvc5/files/11917319/dd.smt2.zip)

**Comment by yoni206** [comment]
Thanks, @alexandernutz ! This helps.
Unfortunately I don't have M2, but we will nevertheless try to reproduce it on our end.

**Comment by daniel-larraz** [comment]
@alexandernutz We recently discovered the M2 architecture is not properly supported by GMP 6.2.1 (the version of the GMP library we were using to generate the cvc5 binaries). Upgrading to GMP 6.3.0 solves the issue. If you download the current version of cvc5 1.1.0 macOS arm64 from the release page (https://github.com/cvc5/cvc5/releases/download/cvc5-1.1.0/cvc5-macOS-arm64, md5=8fd450a71acd123ba03e7535d758dac4) or you build cvc5 using GMP 6.3.0, the problem should be gone.

**Comment by daniel-larraz** [comment]
Hi @Eladkay. Please see my [reply](https://github.com/cvc5/cvc5/issues/9671#issuecomment-1881728573) to alexandernutz. Can you please try to reproduce the original issue using current `main` compiled with GMP 6.3.0? Thanks.

**Comment by Eladkay** [comment]
Sure.
I reran the instructions from [here](https://cvc5.github.io/docs-ci/docs-main/api/python/python.html#installation-arm64-variants-of-linux-and-macos) after pulling from main and making sure that GMP 6.3.0 is installed.
After rebuilding, I can confirm that the issue appears to be fixed.

Thank you very much for your help!
