### ISSUE TITLE
cvc5 license issue

### ISSUE THREAD

**Issue by baoluomeng** [cvc5/cvc5#9698]
Hi,

Just noticed that the the link to the symFPU license in the cvc5 license (https://github.com/cvc5/cvc5/blob/main/COPYING#L72) does not exist.

**Comment by martin-cs** [comment]
Hi @baoluomeng 

There are two different branches of SymFPU, one is GPL V3, the other is BSD.  cvc5 uses the BSD licensed one.

Cheers,
 - Martin

**Comment by martin-cs** [comment]
The "master" branch of SymFPU is GPLv3:
https://github.com/martin-cs/symfpu/blob/master/LICENSE
https://github.com/martin-cs/symfpu/commit/cc302e7f13787a2004d0c800425e464d6e1c8bf9

The special branch for the cvc team is"CVC4":
https://github.com/martin-cs/symfpu/blob/CVC4/LICENSE
https://github.com/martin-cs/symfpu/commit/bdc0ad4cc49b5d590b4d8492199249e392c3368d

**Comment by baoluomeng** [comment]
> The "master" branch of SymFPU is GPLv3: https://github.com/martin-cs/symfpu/blob/master/LICENSE [martin-cs/symfpu@cc302e7](https://github.com/martin-cs/symfpu/commit/cc302e7f13787a2004d0c800425e464d6e1c8bf9)
> 
> The special branch for the cvc team is"CVC4": https://github.com/martin-cs/symfpu/blob/CVC4/LICENSE [martin-cs/symfpu@bdc0ad4](https://github.com/martin-cs/symfpu/commit/bdc0ad4cc49b5d590b4d8492199249e392c3368d)

Thank you, Martin for the quick response.
I was saying that the url to the SymFPU license (https://raw.githubusercontent.com/martin-cs/symfpu/cvc5/LICENSE) in the cvc5 [license](https://github.com/cvc5/cvc5/blob/main/COPYING#L72) is broken, which is confusing. If I click on the url (https://raw.githubusercontent.com/martin-cs/symfpu/cvc5/LICENSE), it gives me a 404: Not Found error. 

And in your SymFPU repo, the license banner shows GNU GPL v3 for all the branches. 

So I think you may want to either fix the url in the cvc5 license or create a new branch for cvc5 on the SymFPU GitHub repo to match the url in cvc5's license.

**Comment by aniemetz** [comment]
Note that we currently use a patched version of branch `CVC4`, which is also BSD: https://github.com/martin-cs/symfpu/tree/symfpu-0.0.7-CVC4-patched

**Comment by aniemetz** [comment]
And good catch about the broken link! I'll submit a fix.
