### ISSUE TITLE
Invalid Alethe proof produced

### ISSUE THREAD

**Issue by rodrigo7491** [cvc5/cvc5#9760]
**Describe the bug**

When trying to check the Alethe proof produced by cvc5 for the instance in [ex.zip](https://github.com/cvc5/cvc5/files/11531814/ex.zip), carcara states that the proof is invalid (see https://github.com/ufmg-smite/carcara/issues/9 for details). The instance is quite large, but since no error is present in cvc5's output, I can't see how ddsmt can be used to minimise it.

The LFSC proof produced for this instance is valid according to the LFSC checker.

**Command line arguments**: `--produce-proofs --proof-format=alethe --proof-granularity=theory-rewrite --flatten-ho-chains ex.smt2`
**cvc5 version/commit**: v1.0.5
**Operating system**: Linux Mint 20.2 and Ubuntu 20.04.1

**Comment by HanielB** [comment]
This issue has been fixed in main with the recent update of the Alethe backend.
