### ISSUE TITLE
Include more files into release versions: Not only executables, but also libraries

### ISSUE THREAD

**Issue by barrettcw** [cvc5/cvc5#9767]
### Discussed in https://github.com/cvc5/cvc5/discussions/9678

<div type='discussions-op-text'>

<sup>Originally posted by **kfriedberger** April 16, 2023</sup>
As a developer of another tool, I would like to download complete prepared/compiled release versions for CVC5 (executables and libraries, including all dependencies, bindings, and license information).
Currently, only the executables are [available there](https://github.com/cvc5/cvc5/releases),
which requires us to build the whole CVC5 aplication on our own, using our own flags and handling potential errors coming from the build-process.

An optimal solution can be seen at the [Z3 release page](https://github.com/Z3Prover/z3/releases), where there is a ZIP-file per operating systems, each including all bindings and libraries for further development.
I would assume that such files already come out from the default build process for CVC5, and only the packaging ignores them.
Would it be possible to provide such files also at the CVC5 release page?</div>

**Comment by leonardoalt** [comment]
We're currently updating cvc4 to cvc5 in our code base so this would be great to have (currently need to compile from source).

Related links from our repo:

https://github.com/ethereum/solidity/issues/13843
https://github.com/ethereum/solidity/pull/14279
