### ISSUE TITLE
get-model does not work

### ISSUE THREAD

**Issue by thaddywu** [cvc5/cvc5#9790]
Hi, I'm using cvc5 1.0.6-dev.133.f8c6f02c1.
It seems that `get-model` does not produce anything.
```
(set-logic QF_ALL)
(set-option :produce-models true)
;(set-option :strings-exp true)

(declare-const z Int)
;(assert (= "5" (str.from_int z)))
(assert (= 5 z))
(check-sat)
(get-model)
```

The output is
```
sat

```

Am I missing any options? BTW, cvc4 works properly.

**Comment by thaddywu** [comment]
hi @ajreynol , I just tried cvc5 1.0.1. It works correctly. It seems like an issue caused by a version upgrade.

**Comment by barrettcw** [comment]
This simple example works on all configurations we have tested.  Could you try either downloading a new binary or rebuilding the binary from scratch.  It could be some strange misconfiguration in your setup.
