### ISSUE TITLE
Tests fail to compile in debug mode

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9840]
**Describe the bug**

When building in debug mode `make check` may fail with a compilation error:
```
.../cvc5/test/unit/./test.h:19:10: fatal error: 'gtest/gtest.h' file not found
#include "gtest/gtest.h"
```
This happens when `gtest` is installed in a non-standard location.

I'm on a recent commit (3114b147124b2ac7ae5bc07b8baf9a338b5f7f7b) and I configured with this command:
```
./configure.sh debug --auto-download  --static
```

The configure script correctly finds the `gtest` installed by brew.
```
Found GTest : /opt/homebrew/lib/libgtest.a
```
But file `test/unit/CMakeLists.txt`  does not take `${GTest_INCLUDE_DIR}` into account.

**Comment by vrcamillo** [comment]
Thanks for the report, @BrunoDutertre. I will look into this. Could you please confirm which operating system you are using?

**Comment by BrunoDutertre** [comment]
I'm using MacOS and I've installed googletest with brew.

I've added a line to `test/unit/CMakeList.txt` and that fixed the problem for me. I haven't tested it
on anything other than my Mac.
```
     target_compile_definitions(${name} PRIVATE ${CVC5_UNIT_TEST_FLAGS_BLACK})
+    target_include_directories(${name} PRIVATE ${GTest_INCLUDE_DIR})
     target_link_libraries(${name} PUBLIC main-test GMP)
```
