### ISSUE TITLE
[Question] Why getValue cannot evaluate a term that does not consist of variable.

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#9860]
Hi, I am using cvc5 in Python. Recently, I found that `solver` in cvc5 Python cannot evaluate a term that does not use a variable. for example, 
```
>>> solver = Solver()
>>> solver.setOption("produce-models","true")
>>> solver.setOption("check-models","true")
>>> p = solver.mkTerm(Kind.EQUAL, solver.mkConst(solver.getIntegerSort(), 'a'), solver.mkInteger(1))
>>> solver.assertFormula(p)
>>> solver.checkSat()
sat
>>> q = solver.mkTerm(Kind.EQUAL, solver.mkRegexpNone(), solver.mkTerm(Kind.REGEXP_STAR, solver.mkRegexpAllchar()))
>>> q
(= re.none (re.* re.allchar))
>>> solver.getValue(q)
Could not evaluate (= re.none (re.* re.allchar)) in getValue.
```
it's hard for me to understand. Why solver cannot evaluate `q`? `q` does not have any variable.
I hope why it happens and how to evaluate terms like what I mentioned with a model.

Thanks for reading.

**Comment by ajreynol** [comment]
Typically, cvc5 will be able evaluate any term that does not have a variable in it.

However, equality between regular expressions is an exception. In general, it is non-trivial to compute whether two regular expressions are equivalent, which is not done by the rewriter.

To test the equivalence of two regular expressions, you can check the satisfiability of:
`(not (= (str.in_re x R1) (str.in_re x R2)))`
for some string x.

**Comment by hagozaebii** [comment]
@ajreynol Thanks for your answer. Except regex, I think there might be some functions which cannot be evaluated by model(e.g. sin, cos..). Could I know which functions cannot be evaludated by model.

Thank you again!

**Comment by ajreynol** [comment]
Unfortunately there isn't central documentation for the list of all functions that don't have evaluation, although here is a list I compiled via a grep of the code base:
```
theory/uf/theory_uf.cpp:  d_valuation.setUnevaluatedKind(kind::COMBINED_CARDINALITY_CONSTRAINT);
theory/bags/theory_bags.cpp:  d_valuation.setUnevaluatedKind(WITNESS);
theory/sets/theory_sets.cpp:  d_valuation.setUnevaluatedKind(SET_COMPREHENSION);
theory/sets/theory_sets.cpp:  d_valuation.setUnevaluatedKind(WITNESS);
theory/sets/theory_sets.cpp:  d_valuation.setUnevaluatedKind(SET_UNIVERSE);
theory/strings/theory_strings.cpp:  d_valuation.setUnevaluatedKind(SEQ_NTH);
theory/arith/theory_arith.cpp:    d_valuation.setUnevaluatedKind(kind::EXPONENTIAL);
theory/arith/theory_arith.cpp:    d_valuation.setUnevaluatedKind(kind::SINE);
theory/arith/theory_arith.cpp:    d_valuation.setUnevaluatedKind(kind::PI);
theory/quantifiers/theory_quantifiers.cpp:  d_valuation.setUnevaluatedKind(EXISTS);
theory/quantifiers/theory_quantifiers.cpp:  d_valuation.setUnevaluatedKind(FORALL);
theory/datatypes/theory_datatypes.cpp:  d_valuation.setUnevaluatedKind(APPLY_SELECTOR);
```
Note that others, e.g. `COSINE` reduce to the above list.

We should consider adding further documentation on this.

**Comment by hagozaebii** [comment]
@ajreynol  Thanks for your answer. I got it right.
