### ISSUE TITLE
Regression test fails because on an incorrect Assert

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9861]
This test fails on MacOS when building in debug mode:
```
> ./build/bin/cvc5 --seq-array=lazy --strings-code-elim test/regress/cli/regress1/strings/to_upper_12.smt regress1/regress1/strings/to_upper_12.smt2
Fatal failure within bool cvc5::internal::theory::strings::SortSeqIndex::operator()(const std::pair<Node, Node> &, const std::pair<Node, Node> &) at  .../cvc5/src/theory/strings/theory_strings.cpp:291
Check failure

 i.first != j.first

Abort
```

I haven't been able to reproduce this on Linux. Here's my set up:
- OS: MacOS X 12.6
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)

I configured with
```
./configure.sh debug --static --auto-download
```

I believe the Assert at line 291 is wrong. 

**More details**

Here's the relevant code:
```
struct SortSeqIndex
{
  ..
  bool operator()(const std::pair<Node, Node>& i,  const std::pair<Node, Node>& j)
  {
    ...
    Assert(i.first != j.first);      // bad assert here
    return ...
  }
}
```
It's used at line 564 for sorting a vector:
```
SortSeqIndex ssi;
std::sort(writes.begin(), writes.end(), ssi);
```
The `Assert` at line 291 will fail if the `std::sort` method calls the comparison operator with two equal arguments. I don't think we can assume that `std::sort` will never do that, and that's exactly what happens on this test. 
Here's what the debugger shows:
```
frame #5: 0x0000000101003fb4 cvc5`cvc5::internal::theory::strings::SortSeqIndex::operator(this=0x000000016fdfd9f8, i=0x0000600002c0d5b0, j=0x0000600002c0d5b0)
```
The arguments `i` and `j` are equal in this call.

**Comment by ajreynol** [comment]
I'm surprised that `std::sort` compares elements to themselves, note `writes` does ensure that the first argument of each of its element is distinct.
Regardless, I can remove the assertion.
