### ISSUE TITLE
Reference counting bugs

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9862]
On MacOs, with a debug build, two regression tests fail:

        2172 - regress1/lemmas/pursuit-safety-8.smtv1.smt2 (Failed)
        3073 - regress1/sygus/node-discrete.sy (Failed)

Both failures have the same symptom:
```
Fatal failure within void cvc5::internal::NodeTemplate<false>::assertTNodeNotExpired() const [ref_count = false] at .../cvc5/src/./expr/node.h:220
Check failure

 d_nv->d_rc > 0
TNode pointing to an expired NodeValue
Abort
```
These are reference counting bugs in `StaticRewrite::rewriteAssertion` and `FunDefEvaluator::evaluateDefinitions`,
caused by use of `std::unordered_map<TNode, Node>` instead of `std::unordered_map<Node, Node>`.

**To reproduce**

I'm on MacOS X 12.6, using Apple clang version 14.0.0 (clang-1400.0.29.202). I'm using commit 0da85f100e126fb89eb8727fa276d2744f0f39c4.

To reproduce the second failure (on `node-discrete.sy`):
```
> ./configure.sh debug --static --auto-download
> cd build
> make
> bin/cvc5 --sygus-out=status --lang=sygus2 --no-check-synth-sol node-discrete.sy
Fatal failure within void cvc5::internal::NodeTemplate<false>::assertTNodeNotExpired() const [ref_count = false] at .../cvc5/src/./expr/node.h:220
Check failure

 d_nv->d_rc > 0
TNode pointing to an expired NodeValue
Abort
```

**Details**

This  bug is in method `evaluateDefinitions` of `FunDefEvaluator` in `src/theory/quantifiers/fun_def_evaluator.cpp`.

This method uses a hashmap:
```
  std::unordered_map<TNode, Node> visited;
```
and it does things roughly like this:
```
  it = visited.find(cur);
  if (it != visited.end() {
    curEval = it->second;  // visited[cur] and curEval point to the same node value obj
    ...
    if (curEval.isNull()) {
     ...
    } else {
     it = visited.find(curEval);
     if (it == visited.end()) {
       ...
     } else {
       // here we know that there's a key k == curEval in the visited map
       // so k points to 'obj'
       ...
       visited[cur] = it->second;  // This decrements the refCount of obj
    }
  }
 }
```
In this code,  the assignment replaces `visited[cur]` which points to the same node_value `obj` as `curEval` with a new node. As a side effect, the refCount on `obj` will be decremented. This refCount may go down to 0 and `obj` could be deleted.  But a pointer to`obj` is still  present as a key in the `visited` table. Because keys in `visited` are `TNode`  instead of `Node` they're not included in the reference count.

**Debugging on linux**

I couldn't reproduce this crash on Linux. But modifying the code slightly shows the problem:
```
  {
     ...
     visited[cur] = it->second;
     Assert(curEval.getRefCount() > 0);
  }
```
With this change, you get an assertion failure::
```
> ./bin/cvc5 --sygus-out=status --lang=sygus2 --no-check-synth-sol node-discrete.sy
Fatal failure within cvc5::internal::Node cvc5::internal::theory::quantifiers::FunDefEvaluator::evaluateDefinitions(cvc5::internal::Node) const at ..../cvc5/src/theory/quantifiers/fun_def_evaluator.cpp:245
Check failure

 curEval.getRefCount() > 0

Abort
```

The crash on `pursuit-safety-8.smtv1.smt2` is similar, but the bug is in a different part of the code.
It's in method `StaticRewriter::rewriteAssertion` in `src/preprocessing/passes/static_rewriter.cpp`.

**Comment by BrunoDutertre** [comment]
I'm still seeing an error on MacOS
```
> cvc5 --check-unsat-cores pursuit-safety-8.smtv1.smt2
Fatal failure within void cvc5::internal::NodeTemplate<false>::assertTNodeNotExpired() const [ref_count = false] at /Users/dutebrun/Repos/cvc5/src/./expr/node.h:220
Check failure

 d_nv->d_rc > 0
TNode pointing to an expired NodeValue
Abort
```
Still in `StaticRewriter::rewriteAssertion`.

**Comment by BrunoDutertre** [comment]
The code in `StaticRewriter::rewriteAssertion` does something like this:
```
if (childChanged)
{
    ret = nm->mkNode(cur.getKind(), children);
}
if (...)
{
  // here retr & ret are known to point to different node_values
  wasRewritten = true;
  keep.insert(retr);
  rewrittenTo[cur] = retr;
  rewrittenTo[ret] = retr;  // the ref count of ret.d_nv  may go down to 0 once the ret variable goes out of scope
}
if (!wasRewritten)
{
   ...
   keep.insert(ret);
} 
```

The `keep.insert(ret)` should be done independently of `wasRewritten`.

**Comment by ajreynol** [comment]
I've opened #9907, does this look right to you?

**Comment by BrunoDutertre** [comment]
Yes. That works.
