### ISSUE TITLE
unable to decode real value from api

### ISSUE THREAD

**Issue by florianschanda** [cvc5/cvc5#9870]
**Describe the bug**
I am getting a SAT result with the below script, but for the life of me I cannot figure out what to do with the value:
```python
import cvc5

solver = cvc5.Solver()
solver.setLogic("QF_NRA")
solver.setOption("produce-models", "true")

x = solver.mkConst(solver.getRealSort(), "x")

solver.assertFormula(
    solver.mkTerm(cvc5.Kind.EQUAL,
                  solver.mkTerm(cvc5.Kind.MULT, x, x),
                  solver.mkReal(30)))

result = solver.checkSat()
value = solver.getValue(x)

print(result)
print(value.getKind())
print(value)
```

This produces:
```plain
sat
Kind.INTERNAL_KIND
(_ real_algebraic_number <1*x^2 + (-30), (21/4, 11/2)>)
```

I have tried both `getRealValue()` and `toPythonObj()`. What do I do?

Even just getting an approximate value would be of immense help.

**Command line arguments**: N/A
**cvc5 version/commit**: 1.0.5 (as downloaded from PyPI)
**Operating system**: Debian 11.7

**Comment by barrettcw** [comment]
The answer is in the output.  The first part of the pair tells you that the exact answer is the square root of 30.  The second tells you that it lies in an interval between 5.25 and 5.5.  What kind of information were you hoping for?

**Comment by florianschanda** [comment]
I was hoping for a programmatic way of getting this info. There is no function on `value` that doesn't die with an exception being thrown. For example using `getRealValue()`

```
Traceback (most recent call last):
  File "/home/florian/projects/trlc/tests/lint-vcg-power/example.py", line 20, in <module>
    print(value.getRealValue())
  File "cvc5.pxi", line 4149, in cvc5_python_base.Term.getRealValue
```

And `toPythonObj()` just returns `None`.

The only thing that works is `str(value)`, but am I really supposed to then parse this internal representation?

But even if I convert to a string and then write a parser for it, I do not understand how `1*x^2 + (-30)` means sqrt. Is there documentation somewhere on those?

**Comment by barrettcw** [comment]
The way to interpret that first part is that the current value is a solution to this polynomial equation (the one you get by setting the term x^2 - 30 equal to 0).  I agree though, it would be good to have a way to obtain that info without parsing a string.  I'll defer to Andy who may know a way to do that (or we could probably easily implement something).

**Comment by florianschanda** [comment]
Ah, now I understand the meaning of the first bit, thanks!

So even a minimal solution would be:
* a predicate, i.e. isSomething() to check which get... function to use
* provide a getRealInterval() -> (Fraction, Fraction) function perhaps, that would already be a big help

I should maybe also say that I am really impressed with the ease of use of the Python API. Very nice work :)

**Comment by ajreynol** [comment]
We should add support for getting information regarding real algebraic numbers from the API, I will look into this.

**Comment by florianschanda** [comment]
Great, thanks. I had a look at the PR and the API seems reasonable.

You don't build the API in the latest / pre-release builds, right?
