### ISSUE TITLE
python3.11 support

### ISSUE THREAD

**Issue by Mingyu821** [cvc5/cvc5#9878]
Do cvc5 support running on python3.11?
Desperately wanna see cvc5 have a version running on python3.11.
I cannot pip install cvc5 on python3.11 now.

**Comment by vrcamillo** [comment]
Python support has already been reenabled in our development branch. In the next cvc5 release, you will be able to install it via pip. Right now, you can use python 3.11 if you build the project from source. I'll discuss with the team about having a new release soon.

**Comment by florianschanda** [comment]
I second this, it would be very nice to have this :)

**Comment by florianschanda** [comment]
So, for python 3.8 at least this is well and truly broken now.
```python3
import cvc5
```
```
Traceback (most recent call last):
  File "potato.py", line 1, in <module>
    import cvc5
  File "/home/q541028/.local/lib/python3.8/site-packages/cvc5/__init__.py", line 2, in <module>
    from .cvc5_python_base import *
  File "cvc5kinds.pxi", line 7, in init cvc5_python_base
  File "/usr/lib/python3.8/enum.py", line 243, in __new__
    enum_member = __new__(enum_class, *args)
TypeError: 'staticmethod' object is not callable
```

**Comment by florianschanda** [comment]
I'd like to say that Python 3.8 support is *extremely important* as that is what is available on Ubuntu 20 LTS, i.e. something found in a lot of corporate setups.
