### ISSUE TITLE
When using getRealValue(), the program terminal reports an error

### ISSUE THREAD

**Issue by busyxu** [cvc5/cvc5#9889]
The real theory of CVC5 is used to solve the constraint _cos(x)==0_, and the solution returns SAT. The value string of the variable is obtained by _getValue_ interface and the result is _"(* (/ 1 2) real.pi)"_, and then the _getRealValue_ interface directly collapses. How do I get the real value of the variable?

The following is an error program fragment picture, the constraint to solve is also cos(x)==0, want to get the real value of x, how to operate?

![cvc5-fig1](https://github.com/cvc5/cvc5/assets/48397805/b8541d40-0b33-4213-a9f6-c73a9afbb0c2)

The following figure shows the specific error information.

![cvc5-fig2](https://github.com/cvc5/cvc5/assets/48397805/dcec17d5-6a6b-426e-8911-cac2e94cb29b)

**Comment by ajreynol** [comment]
`getRealValue` is only valid for terms for which `isRealValue` returns true, see the note here: https://github.com/cvc5/cvc5/blob/main/include/cvc5/cvc5.h#L1533.

A related discussion is here: https://github.com/cvc5/cvc5/issues/9860.

**Comment by ajreynol** [comment]
Note that it is possible to use cvc5 to approximate the value of `real.pi` via successive calls to `check-sat` + bounds on `real.pi`, although there are more efficient ways to do this approximation externally.

**Comment by busyxu** [comment]
`getRealValue` does not support getting terms in the form described above. So there is no interface to get this form Term directly? Need to parse to get Real value?

Thank you very much.

**Comment by ajreynol** [comment]
`getRealValue` should only be used on terms for which `isRealValue` returns true. Other terms can be inspected in the standard way (e.g. via `getKind`, accessing their children via `[]`, etc.).

**Comment by busyxu** [comment]
Thank you for your answer
