### ISSUE TITLE
[Question]: How to use the latest commit version cvc5 in python? 

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#9904]
Hello,

I am currently using cvc5 as a python library(so-called cvc5.base). What if I want to use cvc5 in python with the latest commit version? Because I installed cvc5 with `pip3 install cvc5`, I do not know how to install the latest cvc5 in python which uses latest commit.
Thanks for reading.

**Comment by vrcamillo** [comment]
Thanks for the question!

The latest released version of cvc5 is 1.0.5. It is also released as a python package that can be installed via `pip`, but only if you are using versions of python <= 3.10. Support for python 3.11 has been added and will be available from cvc5 1.0.6, which has not been released yet. 

If you want to use python bindings of in our development branch (main), it is possible to do so by building the project from source, and changing the environment variable `PYTHONPATH`. You can find instructions [HERE](https://cvc5.github.io/docs-ci/docs-main/api/python/python.html).

**Comment by hagozaebii** [comment]
@vrcamillo Thanks a lot, i appreciate your help :)
