### ISSUE TITLE
Fatal failure in Alethe proof generation

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/cvc5#9927]
**Describe the bug**

cvc5 crashes when trying to produce an alethe proof. This is related to Skolem constants.

Here's an example:
```
(set-logic QF_LRA)
(declare-fun b () Bool)
(assert (= 0.0 (ite b 2.0 1.0)))
(check-sat)
```
Then
```
> cvc5 --dump-proof --proof-format-mode=alethe test.smt2 
unsat
Fatal failure within virtual cvc5::internal::Node cvc5::internal::proof::AletheNodeConverter::postConvert(cvc5::internal::Node) at /Users/dutebrun/Repos/cvc5/src/proof/alethe/alethe_node_converter.cpp:34
Unreachable code reached Fresh Skolems are not allowed

Abort
```

This happens with a recent build: 4a2074c2095895dbc6f5589734691777bda111ae

**Comment by ajreynol** [comment]
Note: we are planning to remove support for `--proof-format-mode=alethe` in the future, which will be subsumed by the new format `--proof-format-mode=alf`.

**Comment by HanielB** [comment]
This issue has been fixed in main with the recent update of the Alethe backend. A regression will be added in a subsequent PR.
