### ISSUE TITLE
Include Java bindings in release

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5#9934]
### Discussed in https://github.com/cvc5/cvc5/discussions/9916

<div type='discussions-op-text'>

<sup>Originally posted by **Selebrator** July 25, 2023</sup>
Hi, I'm [depending](https://github.com/Selebrator/ColorUnfolder) on the Java Bindings for cvc5.
I want to automate my dependency resolution and set up automated builds/tests (CI).
As far as I can tell, there is no distribution of cvc5 with Java Bindings; did I miss something?
I would appreciate the distribution found at the Github releases to include the Java bindings, because then I and others, e.g. [package maintainers](https://aur.archlinux.org/packages/cvc5-bin), would be able to easily obtain them. Building from source takes roughly 10 minutes on 8 cores for me. I don't care about the Python bindings, but they would be nice to have as well I assume.

Greetings from the University of Oldenburg, Germany</div>

**Comment by Selebrator** [comment]
Thank you for implementing this. I already switched to this for my build https://github.com/Selebrator/ColorUnfolder/commit/a054522233e90238d41ef5f62d1394ff496b821e, so I can confirm that it is working just as I hoped it would :)
