### ISSUE TITLE
[Question]: How to use `defineFun` function having no argument in python API?

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#9961]
Hello. Recently, I saw a smt file as below:
```
(declare-fun pow2 (Int) Int)
(define-fun pow2_base_cases () Bool (and (= (pow2 0) 1) (= (pow2 1) 2) (= (pow2 2) 4) (= (pow2 3) 8) ) )
```
In the code above, there is a function having no argument. I know functions defined by `define-fun` can be defined by `defineFun` in Python.
However, I do not know how to generate terms with functions having no argument in cvc5 API in Python.
for example,
```
z = solver.defineFun('add', [], int_sort, solver.mkTerm(Kind.NEG, solver.mkInteger(1)))
>>> solver.mkTerm(Kind.APPLY_UF, z, [])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cvc5.pxi", line 1182, in cvc5_python_base.Solver.mkTerm
TypeError: Cannot convert list to cvc5_python_base.Term
```
`APPLY_UF` does not work for the function. 
Could I know how to generate terms with functions having no argument (and defined by `define-fun`)?

Thanks for your time!

**Comment by ajreynol** [comment]
`APPLY_UF` is only necessary if the function has arity>0. In other words, I believe `z` itself is the term you want here.

**Comment by hagozaebii** [comment]
@ajreynol Thanks for your answer. Function having no arguemt can be used as itself! Thanks for your kindness again!
