### ISSUE TITLE
1.0.7 PyPi package TypeError: 'staticmethod' object is not callable

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5#9975]
For Python 3.8 the following fails with the 1.0.7 PyPi package:

Python 3.11 does not have this issues.

```python3
import cvc5
```
```
Traceback (most recent call last):
  File "potato.py", line 1, in <module>
    import cvc5
  File "/home/q541028/.local/lib/python3.8/site-packages/cvc5/__init__.py", line 2, in <module>
    from .cvc5_python_base import *
  File "cvc5kinds.pxi", line 7, in init cvc5_python_base
  File "/usr/lib/python3.8/enum.py", line 243, in __new__
    enum_member = __new__(enum_class, *args)
TypeError: 'staticmethod' object is not callable
```

_Originally posted by @florianschanda in https://github.com/cvc5/cvc5/issues/9878#issuecomment-1689904978_

**Comment by florianschanda** [comment]
I'd like to say that Python 3.8 support is *extremely important* as that is what is available on Ubuntu 20 LTS, i.e. something found in a lot of corporate setups.

**Comment by florianschanda** [comment]
I assume you'll need to do a new PyPI release for this?

**Comment by mpreiner** [comment]
Yes, we'll prepare a new release soon.

**Comment by mpreiner** [comment]
@florianschanda We made a new release 1.0.8. The upload to pypi is in progress. Please let us know if 1.0.8 now works for you.

**Comment by florianschanda** [comment]
I can confirm it now works! Thank you!
