### ISSUE TITLE
crash of model printing on Mac (Bugzilla #785)

### ISSUE THREAD

**Issue by mpreiner** [cvc5/cvc5#998]
**Imported from Bugzilla**
Reporter: *Sylvain Dailler*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Models and counterexamples*
Milestone: *1.6*
Version: *master*
Platform: *Macintosh*
OS: *Mac OS*

Original attachment names and IDs:
- _[crash.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/411_crash.smt2)_ (File causing the crash, ID 411)

On 2017-03-16 03:56:09 -0700, Sylvain Dailler wrote:
> Created attachment 411
> File causing the crash
> 
> Hello,
> 
> On Mac, cvc4 seems to crash on a lot of files we are using to generate counterexamples. We get the following crash during model production: "Abort trap:6"
> 
> On the attached file we get the following:
> 
> \=\=\=\=\=\=\=\=\=\=\=\=\=\=\= Output of cvc4 on the example \=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=
> 
> $ cvc4 crash.smt2
> sat
> (model
> (declare\-datatypes () ((tuple0 (Tuple0))
> ))
> (declare\-sort us\_private 0)
> (define\-fun private\_\_bool\_eq ((BOUND\_VARIABLE\_610 us\_private) (BOUND\_VARIABLE\_611 us\_private)) Bool false)
> (define\-fun us\_null\_ext\_\_ () us\_private _@uc\_us\_private\_0)
> (declare\-sort us\_type\_of\_heap 0)
> (declare\-datatypes () ((us\_type\_of\_heap\_\_ref (mk\_\_\_type\_of\_heap\_\_ref\_\_\_ (us\_type\_of\_heap\_\_content us\_type\_of\_heap)))
> ))
> (declare\-sort us\_image 0)
> (declare\-datatypes () ((int\_\_ref (mk\_int\_\_ref\_\_\_ (int\_\_content Int)))
> ))
> (declare\-datatypes () ((bool\_\_ref (mk\_bool\_\_ref\_\_\_ (bool\_\_content\_\_\_ (\_ BitVec 1))))
> ))
> (declare\-datatypes () ((real\_\_ref (mk\_real\_\_ref\_\_\_ (real\_\_content Real)))
> ))
> (declare\-datatypes () ((us\_private\_\_ref (mk\_\_\_private\_\_ref\_\_\_ (us\_private\_\_content us\_private)))
> ))
> (declare\-sort int20 0)
> (define\-fun attr\_\_ATTRIBUTE\_IMAGE ((BOUND\_VARIABLE\_616 Int)) us\_image _@uc\_us\_image\_0)
> (define\-fun attr\_\_ATTRIBUTE\_VALUE\_\_pre\_check ((BOUND\_VARIABLE\_620 us\_image)) Bool false)
> (define\-fun attr\_\_ATTRIBUTE\_VALUE ((BOUND\_VARIABLE\_623 us\_image)) Int 0)
> (define\-fun user\_eq ((BOUND\_VARIABLE\_626 int20) (BOUND\_VARIABLE\_627 int20)) Bool false)
> (define\-fun dummy () int20 _@uc\_int20\_0)
> (declare\-datatypes () ((int20\_\_ref (mk\_int20\_\_ref\_\_\_ (int20\_\_content int20)))
> ))
> (declare\-sort int10 0)
> (define\-fun attr\_\_ATTRIBUTE\_IMAGE1 ((BOUND\_VARIABLE\_631 Int)) us\_image _@uc\_us\_image\_0)
> (define\-fun attr\_\_ATTRIBUTE\_VALUE\_\_pre\_check1 ((BOUND\_VARIABLE\_634 us\_image)) Bool false)
> (define\-fun attr\_\_ATTRIBUTE\_VALUE1 ((BOUND\_VARIABLE\_637 us\_image)) Int 0)
> (define\-fun user\_eq1 ((BOUND\_VARIABLE\_640 int10) (BOUND\_VARIABLE\_641 int10)) Bool false)
> (define\-fun dummy1 () int10 _@uc\_int10\_0)
> (declare\-datatypes () ((int10\_\_ref (mk\_int10\_\_ref\_\_\_ (int10\_\_content int10)))
> ))
> (define\-fun attr\_\_ATTRIBUTE\_ADDRESS () Int 0)
> (define\-fun attr\_\_ATTRIBUTE\_ADDRESS1 () Int 0)
> (define\-fun x () Int 0)
> (define\-fun y () Int 0)
> (define\-fun inrange\_\_do\_it\_\_result () Int 0)
> (define\-fun o () Int 10)
> (define\-fun inrange\_\_add\_out\_\_i () Int 10)
> (define\-fun o1 () Int 0)
> (define\-fun result () Int 0)
> (define\-fun x1 () Int 10)
> (define\-fun result1 () Int 0)
> (define\-fun y1 () Int 10)
> (define\-fun inrange\_\_add\_out\_\_i1 () Int 20)
> (define\-fun result2 () Int 0)
> (define\-fun x2 () Int 0)
> (define\-fun result3 () Int 0)
> (define\-fun inrange\_\_do\_it\_\_result1 () Int 0)
> (define\-fun inrange\_\_do\_it\_\_result2 () Int 0)
> (define\-fun inrange\_\_do\_it\_\_result3 () Int 0)
> Abort trap:6

On 2017-03-16 09:45:35 -0700, Andrew Reynolds wrote:
> Hi Sylvain,
> 
> 
> What command line options are you using?  Also, can you show the result of running "cvc4 \-\-show\-config"?
> 
> 
> 
> I can't reproduce this on Linux (assuming no command line options).  On first glance, the one thing that is a bit out of the ordinary is the line:
> 
> (get\-info :reason\-unknown) 
> 
> Where my version of CVC4 outputs:
> 
> (error "Can't get\-info :reason\-unknown when the last result wasn't unknown!")
> 
> Does the benchmark still crash when this line is removed?
> 
> 
> 
> 
> Cheers,
> Andy

On 2017-03-16 11:05:56 -0700, Andrew Reynolds wrote:
> Received an email from Yannick Moy on the issue (see below).  The crash is indeed caused by the line:
> 
> (get\-info :reason\-unknown) 
> 
> We should still investigate why this is crashing, but I'll move this to 1.6 milestone/enhancement.
> 
> 
> 
> 
> Hi Andrew,
> 
> This is to answer your comment on the bug that my colleague Sylvain reported earlier today.
> http://cvc4.cs.stanford.edu/bugzilla3/show_bug.cgi?id=785
> 
> \-\-\- Comment \# 1 from Andrew Reynolds <andrew.j.reynolds_@gmail.com> 2017\-03\-16 09:45:35 PDT \-\-\-
> Hi Sylvain,
> 
> 
> What command line options are you using?  
> This is the command used when no steps are used:
> cvc4 \-\-lang\=smt2 \-\-stats \-\-no\-cbqi \-\-no\-cond\-rewrite\-quant \-\-boolean\-term\-conversion\-mode\=native \-\-bitblast\-step\=5 \-\-cnf\-step\=5 \-\-lemma\-step\=10 \-\-parse\-step\=0 \-\-preprocess\-step\=0 \-\-restart\-step\=10 \-\-rewrite\-step\=0 \-\-macros\-quant  \-\-quiet  %f
> 
> and the command used when steps are used:
> cvc4 \-\-lang\=smt2 \-\-stats \-\-no\-cbqi \-\-no\-cond\-rewrite\-quant \-\-boolean\-term\-conversion\-mode\=native \-\-bitblast\-step\=5 \-\-cnf\-step\=5 \-\-lemma\-step\=10 \-\-parse\-step\=0 \-\-preprocess\-step\=0 \-\-restart\-step\=10 \-\-rewrite\-step\=0 \-\-macros\-quant  \-\-quiet  \-\-rlimit\=%S %f
> 
> with obvious wildcards.
> Also, can you show the result of
> running "cvc4 \-\-show\-config"?
> I'm attaching the result.
> I can't reproduce this on Linux (assuming no command line options).  On first
> glance, the one thing that is a bit out of the ordinary is the line:
> 
> (get\-info :reason\-unknown) 
> 
> Where my version of CVC4 outputs:
> 
> (error "Can't get\-info :reason\-unknown when the last result wasn't unknown!")
> 
> Does the benchmark still crash when this line is removed?
> No, CVC4 does not crash anymore when we remove this line, which is not important anyway when trying to get a counterexample (only relevant when proving a VC, to get the reason for lack of proof). Thanks, that provides us with a solution for this issue on our side.
> 
> Best regards
> \-\-
> Yannick Moy, Senior Software Engineer, AdaCore

**Comment by yoni206** [comment]
Cannot reproduce on macOS with current master.
