### ISSUE TITLE
[Question] How to get a model for uninterpreted function in cvc5 Python API?

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#9983]
hello. Currently, I want to get a model for an uninterpreted function through the cvc5 Python API. Specifically, I want to get a model (mapping from input to output) of an uninterpreted function. For example, if you get a model for an uninterpreted function through the z3 Python API, it would look like this:
```
>>> f = Function('f', IntSort(), IntSort())
>>> p = f(1) == 2
>>> solver = Solver()
>>> solver.add(p)
>>> solver.check()
sat
>>> model = solver.model()
>>> model
[f = [else -> 2]]
>>> f = model[0]
>>> model[f]
[else -> 2]
>>> model[f].else_value()
2
```
From this code, I was able to get the model for f(`else -> 2`). How can I do this in the cvc5 python API?

**Comment by hagozaebii** [comment]
Is there something that I did not mention? If there was little info to answer, plz tell me. I will articulate my question more specifically.

**Comment by alex-ozdemir** [comment]
Hi,

You can access the interpretation of function *applications* like this:

```python
from cvc5.pythonic import *

f = Function('f', IntSort(), IntSort())
solver = Solver()
solver.add(f(1) == 2)
print(solver.check()) # prints sat
model = solver.model()
# f = model[0]   # this triggers a bug that will be fixed by: https://github.com/cvc5/cvc5_pythonic_api/pull/90
print(model[f(1)]) # prints 2
```

You can also see [our documentation](https://cvc5.github.io/docs/cvc5-1.0.7/examples/combination.html) for an example of this.

There is no builtin notion of an "else" value for function interpretations.
But, if you're curious about the structure of `f`, you can inspect its AST.

Thank you for this question and this example. As the comment above states, your example revealed a bug that we are patching right now.

Cheers,
Alex

**Comment by hagozaebii** [comment]
@alex-ozdemir  Thanks for your kind reply. However, I want to get a model (mapping from input to output) of an uninterpreted function in `cvc5.base` api. Because as far as I know, cvc5.pythonic does not support some cvc5-specific functions yet.

I went over documentation of cvc5 to know how to get a model about uninterpreted function however, I did not find it yet. 

Hope to know how to get a model in `cvc5.base`

Thanks.

**Comment by alex-ozdemir** [comment]
Ah, I see. Then I think [this example](https://cvc5.github.io/docs/cvc5-1.0.7/examples/combination.html) is what you want.

**Comment by hagozaebii** [comment]
@alex-ozdemir Thanks for your answer. However, I do not know whether my question is handled in the example. I wanna know how to get `else_value` about uninterpreted function. The result of line 78-83 is as below.
```
Call slv.getValue(...) on terms of interest
slv.getValue((f x)): 0
slv.getValue((f y)): 1
slv.getValue((+ (f x) (f y))): 1
slv.getValue((p 0)): false
slv.getValue((p (f y))): true
```
I think those are evaluation result after function application. However, I wanna know something like `[f = [else -> 2]]`.

**Comment by hagozaebii** [comment]
I tried using `getValue` about uninterpreted function itself. And, I got a result as below.
```
>>> solver = Solver()
>>> solver.setOption('produce-models', 'true')
>>> integer = solver.getIntegerSort()
>>> f = solver.declareFun('f', [integer], integer)
>>> a = solver.mkTerm(Kind.APPLY_UF, f, solver.mkInteger(1))
>>> b = solver.mkTerm(Kind.APPLY_UF, f, solver.mkInteger(2))
>>> c = solver.mkTerm(Kind.APPLY_UF, f, solver.mkInteger(3))
>>> p = solver.mkTerm(Kind.EQUAL, a, solver.mkInteger(2))
>>> q = solver.mkTerm(Kind.EQUAL, b, solver.mkInteger(3))
>>> r = solver.mkTerm(Kind.EQUAL, c, solver.mkInteger(4))
>>> solver.assertFormula(p)
>>> solver.assertFormula(q)
>>> solver.assertFormula(r)
>>> solver.checkSat()
sat
>>> solver.getValue(f)
(lambda ((_arg_1 Int)) (ite (= _arg_1 1) 2 (ite (= _arg_1 2) 3 4)))
```
Does it mean `[1 -> 2, 2-> 3, else -> 4]`? Could I understand the result in this way?

**Comment by yoni206** [comment]
Yes, that exactly what it means.
In more detail:
lambda (for any) _arg_1 of type Int, if _arg_1 equals 1, then return 2. Otherwise, if _arg_1 equals 2, then return 3. And otherwise, return 4.
