### ISSUE TITLE
Refutational Soundness issue on QF_S

### ISSUE THREAD

**Issue by fwangdo** [cvc5/cvc5#9990]
Greetings,
For this instance, cvc5 gives `unsat`. However, we checked the instance is solved as `sat` in z3. The instance is as follows.
```
(set-logic QF_S)
(assert (str.prefixof "/signin" "/signin^@"))
(check-sat)
```
In this instance, `^@` is null(`\x00`) according to ASCII code(https://en.wikipedia.org/wiki/Null_character). I report this instance since I think it would be `sat`. If my opinion is wrong, I truly hope that you will let me know.

commit version:  [5b3fb0d](https://github.com/cvc5/cvc5/commit/5b3fb0d4a4a884b43123d4cf30cd16da5215bbdb)
release version: 1.0.7

**Comment by ajreynol** [comment]
I can't reproduce this, can you show me the result `cvc5 --show-config` you are using?

Also, I'm guessing that the file in question actually has the null character and not the text `^@`, which should be interpreted as two characters according to SMT-LIB (there are no escape sequences in SMT-LIB apart from unicode characters `\u...` and double quote `""`).  Is this right?

**Comment by fwangdo** [comment]
@ajreynol I guess we both talk about the same thing. As you said, `^@` is not the text itself but null character. I intended to say that the bug would be reproduced when `^@` would be replaced with real null character. The reason why I wrote `^@` is I have no method to write null character in this issue.

To organize, I think this instance above would be reproduced when `^@` would be substituted by null character. And here is my `--show-config`.
```
This is cvc5 version 1.0.8-dev.22.5b3fb0d4a [git 5b3fb0d4a on branch main]
compiled with GCC version 11.2.0
on Aug 29 2023 13:15:19

Copyright (c) 2009-2023 by the authors and their institutional
affiliations listed at https://cvc5.github.io/people.html

cvc5 is open-source and is covered by the BSD license (modified).

THIS SOFTWARE IS PROVIDED AS-IS, WITHOUT ANY WARRANTIES.
USE AT YOUR OWN RISK.

This version of cvc5 is linked against the following non-(L)GPL'ed
third party libraries.

  CaDiCaL - Simplified Satisfiability Solver
  See https://github.com/arminbiere/cadical for copyright information.

  SymFPU - The Symbolic Floating Point Unit
  See https://github.com/martin-cs/symfpu/tree/CVC4 for copyright information.

This version of cvc5 is linked against the following third party
libraries covered by the LGPLv3 license.
See licenses/lgpl-3.0.txt for more information.

  GMP - Gnu Multi Precision Arithmetic Library
  See http://gmplib.org for copyright information.

  LibPoly polynomial library
  See https://github.com/SRI-CSL/libpoly for copyright and
  licensing information.

See the file COPYING (distributed with the source code, and with
all binaries) for the full cvc5 copyright, licensing, and (lack of)
warranty information.

version       : 1.0.8-dev.22.5b3fb0d4a
scm           : git 5b3fb0d4a on branch main

library       : 1.0.8-dev.22.5b3fb0d4a

debug code    : no
statistics    : yes
tracing       : no
muzzled       : no
assertions    : yes
coverage      : no
profiling     : no
asan          : no
ubsan         : no
tsan          : no
competition   : no

cln           : no
glpk          : no
cryptominisat : no
gmp           : yes
kissat        : no
poly          : yes
cocoa         : no
editline      : no
```

**Comment by fwangdo** [comment]
@ajreynol I attach the file. Hope that it will be helpful. If you have any question, I wish that you would let me know. Thanks for your effort always!
[report.txt](https://github.com/cvc5/cvc5/files/12470882/report.txt)

**Comment by ajreynol** [comment]
I see, as I understand, this is not an SMT-LIB compliant benchmark, as it uses a string literal that contains a non-printable, non-whitespace character.  See Section 3.1 "String literals" of https://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf.

Nevertheless, we should throw an error in this example.

**Comment by fwangdo** [comment]
@ajreynol Thanks for your kind reply. I got it right. Thanks again!
