### ISSUE TITLE
pypi macos support for 13.5

### ISSUE THREAD

**Issue by florianschanda** [cvc5/cvc5#9997]
Hi,

We have a few people on the latest OSX (13.5.1) (on Py3.9) and it's not possible to install the PyPI packages for them. Is there any way you could also build the CVC5 packages for that version?

Many thanks in advance!

**Comment by vrcamillo** [comment]
I will talk to the team about support for OSX 13.5.1. 
Thanks for the report!

**Comment by daniel-larraz** [comment]
Hi @florianschanda. We have published Python bindings for macOS arm64 in PyPI with the latest release of cvc5 (1.1.1). Could you please double-check this is not an issue anymore? Thanks!

**Comment by daniel-larraz** [comment]
Closing this as resolved. Please feel free to open a new issue if you encounter any further problems.
