### ISSUE TITLE
Inconsistent printing for quoted identifiers

### ISSUE THREAD

**Issue by rachitnigam** [cvc5/cvc5#9998]
Quoted identifiers are sometimes printed without `|` from a `get-value` call.

**Command line arguments**: `-L smtlib`
**cvc5 version/commit**: 
This is cvc5 version 1.0.6 [git tag 1.0.6 branch HEAD]
compiled with GCC version Apple LLVM 14.0.0 (clang-1400.0.29.202)

**Operating system**: Mac OS

For the following input file:
```racket
(set-option :produce-models true)
(declare-fun |Aparam0| () Int)
(declare-fun |Eparam1| () Int)
(declare-fun |BZ0::Eparam2| () Int)
(declare-fun |BZ1::Eparam3| () Int)
(declare-fun |'Gevent0| () Int)
(define-fun e2 () Int |Aparam0|)
(define-fun e3 () Int |Eparam1|)
(define-fun e4 () Int |BZ0::Eparam2|)
(define-fun e5 () Int |BZ1::Eparam3|)
(define-fun e6 () Int (+ e4 e5))
(define-fun prop0 () Bool false)
(define-fun prop1 () Bool true)
(define-fun prop2 () Bool (> e3 e2))
(define-fun prop3 () Bool (> e4 e2))
(define-fun prop4 () Bool (> e5 e2))
(define-fun prop5 () Bool (= e3 e6))
(define-fun prop6 () Bool (and prop3 prop5))
(define-fun prop7 () Bool (and prop4 prop6))
(define-fun prop8 () Bool (=> prop7 prop2))
(assert (not prop8))
(check-sat)
(get-value (|Eparam1|))
```

When running with Z3, we get:
```
% z3 -smt2 model.smt      
sat
((|Eparam1| (- 2)))
```

When running cvc5:
```
% cvc5 model.smt -L smtlib
model.smt:2.2: No set-logic command was given before this point.
model.smt:2.2: cvc5 will make all theories available.
model.smt:2.2: Consider setting a stricter logic for (likely) better performance.
model.smt:2.2: To suppress this warning in the future use (set-logic ALL).
sat
((Eparam1 (- 2)))
```

Note that the cvc5 output is missing the `|` around `Eparam1`.

**Comment by ajreynol** [comment]
This is SMT-LIB compliant behavior.

See the note on page 24, "enclosing a simple symbol in vertical bars does not produce a new symbol."
https://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf

In particular, this means that `Eparam1` and `|Eparam1|` denote the same symbol according to the standard.  This means that cvc5 has the choice of which one to print.

In general, cvc5 will enclose symbols in `||` only if it has to. For details, this is determined via this check: https://github.com/cvc5/cvc5/blob/main/src/util/smt2_quote_string.cpp#L26.

**Comment by rachitnigam** [comment]
Ah, I see. I'm using the solver using an API that interns the SExpr symbols and expects them to match exactly in the generated model. Out of curiosity, does this simplification enable something for CVC5? It seems Z3 just generates the same strings regardless of the complexity of the quoted text.

**Comment by ajreynol** [comment]
By design, the cvc5 solver API is agnostic to parsing issues that do not impact solving, thus, we don't have a way to track whether a symbol was passed to our parser as `x` or `|x|`.  Note that it also would lead to complications if both `x` and `|x|` were parsed, this would refer to the same variable but then we could not have a 1-to-1 mapping with what the user provided.

**Comment by rachitnigam** [comment]
Ah, I see! That does seem like a substantial change in that case. Regardless, thanks for the quick response!
